<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Patología especial – Microcurrículos — Programa de Medicina</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./0297073-psicopatologia.html" rel="next">
<link href="./0297071-medicina-interna-i.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-27c261d06b905028a18691de25d09dde.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./0201074-seminario-de-geriatria-y-gerontologia.html">Semestre 7</a></li><li class="breadcrumb-item"><a href="./0297072-patologia-especial.html"><span class="chapter-title">Patología especial</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Microcurrículos — Programa de Medicina</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Presentación</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 1</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0204011-biologia-celular-molecular-y-bioquimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Biología celular molecular y Bioquímica</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297012-fundamentos-de-investigacion-i.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fundamentos de Investigación I</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297015-etica-medica-i.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Ética Médica I</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297017-introduccion-a-la-medicina.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introducción a la Medicina</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 2</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297020-fundamentos-de-investigacion-ii.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fundamentos de Investigación II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297021-morfologia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Morfología</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 3</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297032-psicobiologia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Psicobiología</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297034-fisiologia-general-y-de-sistemas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fisiología general y de sistemas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297035-fundamentos-de-investigacion-iii.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fundamentos de Investigación III</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297036-genetica-basica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Genética básica</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 4</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297041-microbiologia-y-parasitologia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Microbiología y Parasitología</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297042-patologia-general.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Patología general</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297045-fundamentos-de-investigacion-iv.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fundamentos de Investigación IV</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 5</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297051-farmacologia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Farmacología</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297052-semiologia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Semiología</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297053-psicologia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Psicología</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 6</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0201063-salud-familiar.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Salud Familiar</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297061-cirugia-general.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Cirugía general</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297063-seminario-historia-de-la-medicina.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Seminario Historia de la Medicina</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 7</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0201074-seminario-de-geriatria-y-gerontologia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Seminario de Geriatría y Gerontología</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297071-medicina-interna-i.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Medicina Interna I</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297072-patologia-especial.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Patología especial</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297073-psicopatologia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Psicopatología</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 8</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297081-medicina-interna-ii.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Medicina Interna II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297083-psiquiatria.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Psiquiatría</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297084-etica-medica-ii.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Ética Médica II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297096-seminario-de-tanatologia-y-medicina-paliativa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Seminario de Tanatología y Medicina Paliativa</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 9</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297091-cirugia-de-especialidades.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Cirugía de Especialidades</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297092-seminario-de-desastres.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Seminario de Desastres</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 10</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297101-pediatria.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Pediatría</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297102-administracion-en-salud.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Administración en Salud</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 11</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297082-medicina-legal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Medicina Legal</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297112-ginecologia-y-obstetricia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Ginecología y Obstetricia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297113-medicina-preventiva-y-salud-publica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Medicina Preventiva y Salud Pública</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#identificación" id="toc-identificación" class="nav-link active" data-scroll-target="#identificación">1 Identificación</a>
  <ul class="collapse">
  <li><a href="#datos-de-identificación" id="toc-datos-de-identificación" class="nav-link" data-scroll-target="#datos-de-identificación">1.1 Datos de identificación</a></li>
  <li><a href="#prerrequisitos" id="toc-prerrequisitos" class="nav-link" data-scroll-target="#prerrequisitos">1.2 Prerrequisitos</a></li>
  </ul></li>
  <li><a href="#profesores" id="toc-profesores" class="nav-link" data-scroll-target="#profesores">2 Profesores</a>
  <ul class="collapse">
  <li><a href="#coordinador" id="toc-coordinador" class="nav-link" data-scroll-target="#coordinador">2.1 Coordinador</a></li>
  <li><a href="#cuerpo-docente" id="toc-cuerpo-docente" class="nav-link" data-scroll-target="#cuerpo-docente">2.2 Cuerpo docente</a></li>
  </ul></li>
  <li><a href="#presentación" id="toc-presentación" class="nav-link" data-scroll-target="#presentación">3 Presentación</a></li>
  <li><a href="#competencias" id="toc-competencias" class="nav-link" data-scroll-target="#competencias">4 Competencias</a>
  <ul class="collapse">
  <li><a href="#matriz-de-competencias" id="toc-matriz-de-competencias" class="nav-link" data-scroll-target="#matriz-de-competencias">4.1 Matriz de competencias</a></li>
  </ul></li>
  <li><a href="#metodología-y-contenidos" id="toc-metodología-y-contenidos" class="nav-link" data-scroll-target="#metodología-y-contenidos">5 Metodología y Contenidos</a>
  <ul class="collapse">
  <li><a href="#temas-y-estrategias-pedagógicas" id="toc-temas-y-estrategias-pedagógicas" class="nav-link" data-scroll-target="#temas-y-estrategias-pedagógicas">5.1 Temas y estrategias pedagógicas</a></li>
  </ul></li>
  <li><a href="#sistema-de-evaluación" id="toc-sistema-de-evaluación" class="nav-link" data-scroll-target="#sistema-de-evaluación">6 Sistema de Evaluación</a>
  <ul class="collapse">
  <li><a href="#proceso-de-evaluación" id="toc-proceso-de-evaluación" class="nav-link" data-scroll-target="#proceso-de-evaluación">6.1 Proceso de evaluación</a></li>
  <li><a href="#tabla-de-calificación" id="toc-tabla-de-calificación" class="nav-link" data-scroll-target="#tabla-de-calificación">6.2 Tabla de calificación</a></li>
  </ul></li>
  <li><a href="#cronograma" id="toc-cronograma" class="nav-link" data-scroll-target="#cronograma">7 Cronograma</a>
  <ul class="collapse">
  <li><a href="#distribución-semanal-de-temas" id="toc-distribución-semanal-de-temas" class="nav-link" data-scroll-target="#distribución-semanal-de-temas">7.1 Distribución semanal de temas</a></li>
  <li><a href="#distribución-semanal-de-rotaciones-prácticas-o-laboratorios" id="toc-distribución-semanal-de-rotaciones-prácticas-o-laboratorios" class="nav-link" data-scroll-target="#distribución-semanal-de-rotaciones-prácticas-o-laboratorios">7.2 Distribución semanal de rotaciones, prácticas o laboratorios</a></li>
  </ul></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias">8 Referencias</a></li>
  <li><a href="#anexos" id="toc-anexos" class="nav-link" data-scroll-target="#anexos">9 Anexos</a>
  <ul class="collapse">
  <li><a href="#anexo-a-competencias-y-criterios-de-desempeño" id="toc-anexo-a-competencias-y-criterios-de-desempeño" class="nav-link" data-scroll-target="#anexo-a-competencias-y-criterios-de-desempeño">Anexo A — Competencias y criterios de desempeño</a></li>
  <li><a href="#anexo-b-contenidos-detallados-por-sistema" id="toc-anexo-b-contenidos-detallados-por-sistema" class="nav-link" data-scroll-target="#anexo-b-contenidos-detallados-por-sistema">Anexo B — Contenidos detallados por sistema</a></li>
  <li><a href="#anexo-c-directrices-de-la-correlación-clínico-patológica" id="toc-anexo-c-directrices-de-la-correlación-clínico-patológica" class="nav-link" data-scroll-target="#anexo-c-directrices-de-la-correlación-clínico-patológica">Anexo C — Directrices de la correlación clínico-patológica</a></li>
  <li><a href="#anexo-d-cronograma-de-rotaciones" id="toc-anexo-d-cronograma-de-rotaciones" class="nav-link" data-scroll-target="#anexo-d-cronograma-de-rotaciones">Anexo D — Cronograma de Rotaciones</a></li>
  </ul></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1"></a></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2"></a></li>
  <li><a href="#rúbrica-evaluativa" id="toc-rúbrica-evaluativa" class="nav-link" data-scroll-target="#rúbrica-evaluativa">Rúbrica evaluativa</a></li>
  <li><a href="#rúbrica-evaluativa-1" id="toc-rúbrica-evaluativa-1" class="nav-link" data-scroll-target="#rúbrica-evaluativa-1">Rúbrica evaluativa</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./0201074-seminario-de-geriatria-y-gerontologia.html">Semestre 7</a></li><li class="breadcrumb-item"><a href="./0297072-patologia-especial.html"><span class="chapter-title">Patología especial</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Patología especial</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="identificación" class="level2">
<h2 class="anchored" data-anchor-id="identificación">1 Identificación</h2>
<section id="datos-de-identificación" class="level3">
<h3 class="anchored" data-anchor-id="datos-de-identificación">1.1 Datos de identificación</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Campo</th>
<th>Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nombre</td>
<td>Patología especial</td>
</tr>
<tr class="even">
<td>Código</td>
<td>0297072</td>
</tr>
<tr class="odd">
<td>Semestre</td>
<td>7</td>
</tr>
<tr class="even">
<td>Créditos</td>
<td>5</td>
</tr>
<tr class="odd">
<td>Dimensión curricular</td>
<td>Del campo específico de formación</td>
</tr>
<tr class="even">
<td>Área de formación</td>
<td>Humanístico; Clínico</td>
</tr>
<tr class="odd">
<td>Horas presenciales semanales</td>
<td>8</td>
</tr>
<tr class="even">
<td>Horas teóricas semanales</td>
<td>5</td>
</tr>
<tr class="odd">
<td>Horas prácticas semanales</td>
<td>3</td>
</tr>
<tr class="even">
<td>Horas de trabajo independiente semanal</td>
<td>7</td>
</tr>
<tr class="odd">
<td>Horas de trabajo presencial semestrales</td>
<td>128</td>
</tr>
<tr class="even">
<td>Total de horas de trabajo independiente semestrales</td>
<td>112</td>
</tr>
<tr class="odd">
<td>Horas teóricas por semestre</td>
<td>80</td>
</tr>
<tr class="even">
<td>Horas prácticas por semestre</td>
<td>48</td>
</tr>
<tr class="odd">
<td>Habilitable</td>
<td>No</td>
</tr>
<tr class="even">
<td>Prácticas de laboratorio</td>
<td>Sí</td>
</tr>
<tr class="odd">
<td>Prácticas clínicas</td>
<td>Sí</td>
</tr>
<tr class="even">
<td>Prácticas sociales</td>
<td>No</td>
</tr>
</tbody>
</table>
</section>
<section id="prerrequisitos" class="level3">
<h3 class="anchored" data-anchor-id="prerrequisitos">1.2 Prerrequisitos</h3>
<ol type="1">
<li><p>0297042 — Patología general</p></li>
<li><p>Cirugía General – Código: 0297061</p></li>
</ol>
</section>
</section>
<section id="profesores" class="level2">
<h2 class="anchored" data-anchor-id="profesores">2 Profesores</h2>
<section id="coordinador" class="level3">
<h3 class="anchored" data-anchor-id="coordinador">2.1 Coordinador</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 41%">
<col style="width: 58%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Campo</th>
<th style="text-align: left;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Nombre</td>
<td style="text-align: left;">Victoria Eugenia Niño</td>
</tr>
<tr class="even">
<td style="text-align: left;">Email</td>
<td style="text-align: left;">vnino@unicauca.edu.co</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Perfil profesional</td>
<td style="text-align: left;">Bióloga, Magíster en Ciencias Básicas Médicas con énfasis en Inmunología y Doctora en Biotecnología y Biociencias énfasis en Inmunología, con experiencia en docencia universitaria, investigación y gestión académica en las áreas de Patología, Inmunología, Microbiología y Biología Celular y Molecular.</td>
</tr>
</tbody>
</table>
</section>
<section id="cuerpo-docente" class="level3">
<h3 class="anchored" data-anchor-id="cuerpo-docente">2.2 Cuerpo docente</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 27%">
<col style="width: 49%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Nombre</th>
<th style="text-align: left;">Email</th>
<th style="text-align: left;">Perfil profesional</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sofía Benavides</td>
<td style="text-align: left;">monicasbenavides@unicauca.edu.co</td>
<td style="text-align: left;">Médica patóloga del Departamento de Patología. Docente de clases teóricas.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ivonne Meza</td>
<td style="text-align: left;"><mark>imeza@unicauca.edu.co</mark></td>
<td style="text-align: left;">Médica patóloga del Departamento de Patología. Docente de clases teóricas.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Harold Bolaños</td>
<td style="text-align: left;">haroldbolanos@unicauca.edu.co</td>
<td style="text-align: left;">Médico patólogo del Departamento de Patología. Docente de clases teóricas.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jaime Alvarez Soler</td>
<td style="text-align: left;">jalvarezs@unicauca.edu.co</td>
<td style="text-align: left;">Médico Patólogo del Departamento de Patología. Docente encargado de la Rotación.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jeison Casallas</td>
<td style="text-align: left;">jeisoncasallas@unicauca.edu.co</td>
<td style="text-align: left;">Histotecnólogo del Departamento de Patología. Docente encargado de la Rotación.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rosa Amalia Dueñas</td>
<td style="text-align: left;">raduenasc@unicauca.edu.co</td>
<td style="text-align: left;">Bióloga, PhD en Biología Molecular con énfasis en Biología Molecular, adscrita al Departamento de Patología. Docente encargada de la Rotación de Patología.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Victoria Eugenia Niño</td>
<td style="text-align: left;">vnino@unicauca.edu.co</td>
<td style="text-align: left;">Bióloga, Magíster en Ciencias Básicas Médicas con énfasis en Inmunología y Doctora en Biotecnología y Biociencias con énfasis en Inmunología, del Departamento de Patología. Docente encargada de la Rotación.</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="presentación" class="level2">
<h2 class="anchored" data-anchor-id="presentación">3 Presentación</h2>
<section id="presentación-de-la-asignatura" class="level4">
<h4 class="anchored" data-anchor-id="presentación-de-la-asignatura">Presentación de la Asignatura</h4>
<p>Patología especial es un curso teórico-práctico del Departamento de Patología del Programa de Medicina de la Facultad de Ciencias de la Salud de la Universidad del Cauca. Ofrece al estudiante los conocimientos sobre etiología, patogénesis y manifestaciones morfológicas y funcionales de las enfermedades específicas por órganos y sistemas, para que aplique los conocimientos de patología general y de las demás ciencias básicas no solo a nivel morfológico, sino también en relación con las manifestaciones clínicas, en beneficio de la prevención, el diagnóstico, el tratamiento y la rehabilitación del paciente.</p>
<p>El componente teórico abarca, por sistemas, las diferentes entidades patológicas —etiología, patogenia, cambios morfológicos macroscópicos y microscópicos y su correlación con la clínica—, mediante clases orientadas por los docentes del Departamento. El componente práctico se desarrolla en rotaciones en las que el estudiante interactúa con los docentes y conoce las técnicas que la patología actual utiliza para un diagnóstico preciso y para orientar la conducta terapéutica del clínico. De forma transversal, cada grupo de estudiantes elabora una correlación clínico-patológica de un caso asignado, con tutor, que se socializa al final del semestre en formato de reporte de caso publicable en la revista de la Facultad.</p>
<p>La misión del Departamento de Patología es brindar docencia y servicios de diagnóstico, prevención y seguimiento de enfermedades mediante exámenes anatomopatológicos y citológicos. El Departamento cuenta con el Grupo de Investigación en Inmunología y Enfermedades Infecciosas y su semillero de investigación.</p>
</section>
<section id="objetivo-general" class="level4">
<h4 class="anchored" data-anchor-id="objetivo-general">Objetivo General</h4>
<p>Analizar las alteraciones propias de cada órgano y sistema, para una mejor comprensión de la fase anatomopatológica de las enfermedades que se presentan en el ser humano, estudiando la dinámica y los mecanismos de producción de la enfermedad.</p>
</section>
<section id="objetivos-específicos" class="level4">
<h4 class="anchored" data-anchor-id="objetivos-específicos">Objetivos Específicos</h4>
<ul>
<li><p>Describir la historia natural de las principales enfermedades por órganos y sistemas para actuar en sus diferentes etapas.</p></li>
<li><p>Estudiar la dinámica y el mecanismo de producción de la enfermedad.</p></li>
<li><p>Interpretar las historias clínicas de acuerdo con la terminología médica y los laboratorios.</p></li>
<li><p>Explicar la enfermedad enfatizando en las entidades más frecuentes del medio, destacando su distribución, etiología y cambios morfológicos con las manifestaciones clínicas resultantes.</p></li>
<li><p>Elaborar y presentar las correlaciones clínico-patológicas de los casos estudiados.</p></li>
<li><p>Despertar en el estudiante el espíritu de investigación y autoformación, y manejar datos de instrumentos de investigación bajo la tutoría de un profesor.</p></li>
<li><p>Analizar problemas de salud pertinentes a la ciudad, el Departamento o la Nación cuando sea necesario.</p></li>
</ul>
</section>
<section id="justificación-de-la-asignatura" class="level4">
<h4 class="anchored" data-anchor-id="justificación-de-la-asignatura">Justificación de la Asignatura</h4>
<p>Patología especial es el puente entre las ciencias básicas y la clínica: al estudiar las alteraciones anatomopatológicas de cada órgano y sistema, el estudiante integra los conocimientos de patología general y ciencias básicas con las manifestaciones clínicas de las enfermedades, lo que le permite comprender los mecanismos de producción de la enfermedad y actuar en la prevención, el diagnóstico, el tratamiento y la rehabilitación del paciente. En coherencia con el perfil de egreso del Programa de Medicina, la asignatura desarrolla la capacidad de investigar y comprender los cinco aspectos comunes a toda enfermedad —etiología, patogenia, cambios morfológicos, cambios funcionales y significancia clínica— y de elaborar correlaciones clínico-patológicas con rigor y vocación de servicio.</p>
</section>
<section id="descripción-general-de-la-asignatura" class="level4">
<h4 class="anchored" data-anchor-id="descripción-general-de-la-asignatura">Descripción General de la Asignatura</h4>
<p>El curso se organiza por sistemas en trece unidades temáticas —páncreas y riñón; vías urinarias bajas y genital masculino; sistema nervioso central; sistema endocrino; corazón y vasos sanguíneos; tubo digestivo; leucocitos, ganglio linfático y timo; cabeza y cuello; hueso, articulaciones y tejidos blandos; hígado y vía biliar; pulmón; aparato genital femenino; y patología de mama—, cada una con clases teóricas (5 horas semanales) y rotación práctica orientada por un docente (3 horas semanales), más 7 horas semanales de trabajo independiente y correlación clínico-patológica. La asignatura comprende 128 horas de trabajo presencial y 112 de trabajo independiente en el semestre. La metodología combina clases magistrales, rotaciones prácticas de patología y la correlación clínico-patológica tutorada. El detalle de contenidos por sistema y el cronograma se recogen en los anexos.</p>
</section>
<section id="espacios-de-asesorías" class="level4">
<h4 class="anchored" data-anchor-id="espacios-de-asesorías">Espacios de Asesorías</h4>
<p>Los docentes del departamento de patología tienen a cargo un grupo de estudiantes para la correlación clínico-patológica y realizan tutorías con su grupo los viernes de 2:00 a 3:00 p.m. La comunicación con el Departamento se canaliza a través del coordinador de la asignatura (vnino@unicauca.edu.co), quien recibe las solicitudes de asesoría y consejería y orienta el encuentro virtual o presencial con el docente específico.</p>
<p>Horario regular de clases (I período académico 2026):</p>
<ul>
<li><p>Jueves, 2:00 a 4:00 p.m. — Salón 108 (clases teóricas).</p></li>
<li><p>Viernes, 3:00 a 6:00 p.m. — Salón 106 (clases teóricas).</p></li>
<li><p>Viernes, 2:00 a 3:00 p.m. — Correlación clínico-patológica.</p></li>
<li><p>Lunes y miércoles, 2:00 a 3:00 p.m. — Rotaciones (sitio de rotación).</p></li>
</ul>
</section>
</section>
<section id="competencias" class="level2">
<h2 class="anchored" data-anchor-id="competencias">4 Competencias</h2>
<section id="matriz-de-competencias" class="level3">
<h3 class="anchored" data-anchor-id="matriz-de-competencias">4.1 Matriz de competencias</h3>
<p>Resumen de las competencias que declara la asignatura, agrupadas como en el syllabus original. La información completa —cada competencia con su criterio de desempeño— puede consultarse en el Anexo A.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 69%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Grupo de competencia</th>
<th style="text-align: left;">Competencias de la asignatura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Generales (cognitivas, ciudadanas, inglés, TIC)</td>
<td style="text-align: left;">Respeta los principios, leyes y normas que protegen la vida, la dignidad y el bienestar de personas y colectivos, actuando con autonomía, ética y compromiso en la protección, el cuidado y la recuperación de la salud; comprende textos científicos en inglés y desarrolla habilidades de comunicación</td>
</tr>
<tr class="even">
<td style="text-align: left;">Del ser (actitudinales, afectivas, éticas/bioéticas)</td>
<td style="text-align: left;">Cultiva, a través de las correlaciones clínico-patológicas, los valores de ética, respeto, confidencialidad, responsabilidad, veracidad y vocación de servicio; práctica los principios de convivencia ciudadana y ética médica; se interesa por su aprendizaje de manera permanente, responsable y participativa</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Del saber (conocimientos, comprensión, problematización)</td>
<td style="text-align: left;">Indaga, analiza y discierne la información científica, tecnológica y legal para tomar decisiones pertinentes; investiga y comprende los cinco aspectos comunes a toda enfermedad (etiología, patogenia, cambios morfológicos y funcionales y significancia clínica); establece diferencias morfológicas macro y microscópicas en los tejidos y órganos afectados</td>
</tr>
<tr class="even">
<td style="text-align: left;">Del saber-hacer (aptitudes, habilidades, destrezas)</td>
<td style="text-align: left;">Correlaciona los conceptos teóricos de la enfermedad con los aspectos prácticos y clínicos; interpreta y analiza estudios citológicos y de anatomía patológica; realiza un enfoque sistemático de la enfermedad para orientar los estudios diagnósticos y de manejo; orienta al paciente y su familia sobre el cuidado de la salud</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Del convivir y comunicar (relacionales, interculturales, educativas)</td>
<td style="text-align: left;">Fomenta una comunicación asertiva sobre la condición clínico-patológica del paciente, involucrando a su grupo familiar; respeta los derechos del paciente en el marco del ejercicio ético e idóneo; establece una comunicación académica abierta y comprensiva con compañeros y docentes</td>
</tr>
</tbody>
</table>
<section id="resultados-de-aprendizaje" class="level4">
<h4 class="anchored" data-anchor-id="resultados-de-aprendizaje">Resultados de aprendizaje</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td>☑</td>
<td>a. Realizar un ejercicio médico integral y resolutivo en ámbitos comunitarios e institucionales en todas las etapas de la atención en salud, en concordancia con sus determinantes.</td>
</tr>
</tbody>
</table>
</section>
</section>
</section>
<section id="metodología-y-contenidos" class="level2">
<h2 class="anchored" data-anchor-id="metodología-y-contenidos">5 Metodología y Contenidos</h2>
<section id="temas-y-estrategias-pedagógicas" class="level3">
<h3 class="anchored" data-anchor-id="temas-y-estrategias-pedagógicas">5.1 Temas y estrategias pedagógicas</h3>
<p>Síntesis de las trece unidades temáticas. El contenido detallado de cada sistema, con sus horas, puede consultarse en el Anexo B. Cada tema comprende 5 horas semanales de clase teórica, 3 de rotación práctica y 7 de trabajo independiente y correlación clínico-patológica.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 23%">
<col style="width: 17%">
<col style="width: 41%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">#</th>
<th style="text-align: left;">Tema / Unidad</th>
<th style="text-align: left;">Estrategia(s)</th>
<th style="text-align: left;">Trabajo independiente</th>
<th style="text-align: left;">Bibliografía</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Páncreas y riñón</td>
<td style="text-align: left;">MEP</td>
<td style="text-align: left;">Trabajo independiente y correlación clínico-patológica orientada por docente. Detalle en el Anexo B</td>
<td style="text-align: left;">[1]</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Vías urinarias bajas y genital masculino</td>
<td style="text-align: left;">MEP</td>
<td style="text-align: left;">Trabajo independiente y correlación clínico-patológica. Detalle en el Anexo B</td>
<td style="text-align: left;">[1]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Sistema nervioso central</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">[1]</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Sistema endocrino</td>
<td style="text-align: left;">MEP</td>
<td style="text-align: left;">Trabajo independiente y correlación clínico-patológica. Detalle en el Anexo B</td>
<td style="text-align: left;">[1]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Corazón y vasos sanguíneos</td>
<td style="text-align: left;">MEP</td>
<td style="text-align: left;">Trabajo independiente y correlación clínico-patológica. Detalle en el Anexo B</td>
<td style="text-align: left;">[1]</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">Tubo digestivo</td>
<td style="text-align: left;">MEP</td>
<td style="text-align: left;">Trabajo independiente y correlación clínico-patológica. Detalle en el Anexo B</td>
<td style="text-align: left;">[1]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">Leucocitos, ganglio linfático y timo</td>
<td style="text-align: left;">MEP</td>
<td style="text-align: left;">Trabajo independiente y correlación clínico-patológica. Detalle en el Anexo B</td>
<td style="text-align: left;">[1]</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">Cabeza y cuello</td>
<td style="text-align: left;">MEP</td>
<td style="text-align: left;">Trabajo independiente y correlación clínico-patológica. Detalle en el Anexo B</td>
<td style="text-align: left;">[1]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">Hueso, articulaciones y tejidos blandos</td>
<td style="text-align: left;">MEP</td>
<td style="text-align: left;">Trabajo independiente y correlación clínico-patológica. Detalle en el Anexo B</td>
<td style="text-align: left;">[1]</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">Hígado y vía biliar</td>
<td style="text-align: left;">MEP</td>
<td style="text-align: left;">Trabajo independiente y correlación clínico-patológica. Detalle en el Anexo B</td>
<td style="text-align: left;">[1]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: left;">Pulmón</td>
<td style="text-align: left;">MEP</td>
<td style="text-align: left;">Trabajo independiente y correlación clínico-patológica. Detalle en el Anexo B</td>
<td style="text-align: left;">[1]</td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: left;">Aparato genital femenino</td>
<td style="text-align: left;">MEP</td>
<td style="text-align: left;">Trabajo independiente y correlación clínico-patológica. Detalle en el Anexo B</td>
<td style="text-align: left;">[1]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: left;">Patología de mama</td>
<td style="text-align: left;">MEP</td>
<td style="text-align: left;">Trabajo independiente y correlación clínico-patológica. Detalle en el Anexo B</td>
<td style="text-align: left;">[1]</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="sistema-de-evaluación" class="level2">
<h2 class="anchored" data-anchor-id="sistema-de-evaluación">6 Sistema de Evaluación</h2>
<section id="proceso-de-evaluación" class="level3">
<h3 class="anchored" data-anchor-id="proceso-de-evaluación">6.1 Proceso de evaluación</h3>
<p>La evaluación de la asignatura se organiza en dos parciales acumulativos y un examen final, todos con componente oral (Anexos E y F) y escrito, más la evaluación de las rotaciones y las correlaciones clínico-patológicas. Las evaluaciones orales y escritas son acumulativas. El estudiante que no presente una de las pruebas (oral o escrita) debe notificar al coordinador de la asignatura y realizar la evaluación supletoria, que en todos los casos será oral y realizada por dos o más docentes del Departamento.</p>
<p>La correlación clínico-patológica se desarrolla a lo largo del semestre: los estudiantes, en grupos con tutor, trabajan un caso clínico asignado y lo socializan en la última semana (30 minutos de exposición y 10 de preguntas), con formato libre; además presentan el caso redactado como reporte de caso, publicable en la revista de la Facultad de Ciencias de la Salud.</p>
</section>
<section id="tabla-de-calificación" class="level3">
<h3 class="anchored" data-anchor-id="tabla-de-calificación">6.2 Tabla de calificación</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 23%">
<col style="width: 39%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Tiempo evaluativo</th>
<th style="text-align: left;">Momento</th>
<th style="text-align: left;">Tipo de evaluación</th>
<th style="text-align: left;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Nota Previa (70%)</td>
<td style="text-align: left;">Primer Parcial (35%)</td>
<td style="text-align: left;">Examen oral</td>
<td style="text-align: left;">39%</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Examen escrito</td>
<td style="text-align: left;">39%</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Evaluación de las rotaciones</td>
<td style="text-align: left;">20%</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Autoevaluación</td>
<td style="text-align: left;">2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Segundo Parcial (35%)</td>
<td style="text-align: left;">Examen oral</td>
<td style="text-align: left;">39%</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Examen escrito</td>
<td style="text-align: left;">39%</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Evaluación de las rotaciones</td>
<td style="text-align: left;">20%</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Examen Final (30%)</td>
<td style="text-align: left;">Examen Final (30%)</td>
<td style="text-align: left;">Examen escrito</td>
<td style="text-align: left;">29%</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Examen oral</td>
<td style="text-align: left;">29%</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Correlaciones clínico-patológicas</td>
<td style="text-align: left;">30%</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Autoevaluación</td>
<td style="text-align: left;">2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">Evaluación de las rotaciones</td>
<td style="text-align: left;">10%</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="cronograma" class="level2">
<h2 class="anchored" data-anchor-id="cronograma">7 Cronograma</h2>
<section id="distribución-semanal-de-temas" class="level3">
<h3 class="anchored" data-anchor-id="distribución-semanal-de-temas">7.1 Distribución semanal de temas</h3>
<p>Programación de clases teóricas del II período académico 2026 (jueves 2:00 a 4:00 p.m., salón 108; viernes 3:00 a 6:00 p.m., salón 106).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 9%">
<col style="width: 30%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Tema / Unidad</th>
<th style="text-align: left;">Semana</th>
<th style="text-align: left;">Fecha(s)</th>
<th style="text-align: left;">Observaciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Páncreas y riñón</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">03-08-2026 al 06-08-2026</td>
<td style="text-align: left;">Dra. Sofía Benavides</td>
</tr>
<tr class="even">
<td style="text-align: left;">Vías urinarias bajas y genital masculino</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">10-08-2026 al 14-08-2026</td>
<td style="text-align: left;">Dra. Sofía Benavides</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sistema nervioso central</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">18-08-2026 al 21-08-2026</td>
<td style="text-align: left;">Dra. Sofía Benavides</td>
</tr>
<tr class="even">
<td style="text-align: left;">Corazón y vasos sanguíneos</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">24-08-2026 al 28-08-2026</td>
<td style="text-align: left;">Dra. Sofía Benavides</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sistema endocrino</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">31-08-2026 al 04-09-2026</td>
<td style="text-align: left;">Dra. Ivonne Meza</td>
</tr>
<tr class="even">
<td style="text-align: left;">Primera evaluación teórico-práctica (35%)</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">07-09-2026 al 11-09-2026</td>
<td style="text-align: left;">Todos los docentes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tubo digestivo</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">14-09-2026 al 18-09-2026</td>
<td style="text-align: left;">Dra. Sofía Benavides</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leucocitos, ganglio y timo</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">21-09-2026 al 25-09-2026</td>
<td style="text-align: left;">Dra. Sofía Benavides</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cabeza y cuello</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">28-09-2026 al 02-10-2026</td>
<td style="text-align: left;">Dra. Sofía Benavides</td>
</tr>
<tr class="even">
<td style="text-align: left;">Huesos, articulaciones y tejidos blandos</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">05-10-2026 al 09-10-2026</td>
<td style="text-align: left;">Dra. Sofía Benavides</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Segunda evaluación teórico-práctica (35%)</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">13-010-2026 al 16-10-2026</td>
<td style="text-align: left;">Todos los docentes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hígado y vía biliar</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">19-10-2026 al 23-10-2026</td>
<td style="text-align: left;">Dr.&nbsp;Harold Bolaños</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pulmón</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">26-10-2026 al 30-10-2026</td>
<td style="text-align: left;">Dr.&nbsp;Harold Bolaños</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aparato genital femenino</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">03-11-2026 al 06-11-2026</td>
<td style="text-align: left;">Dra. Sofía Benavides</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Patología de mama</td>
<td style="text-align: left;">15</td>
<td style="text-align: left;">09-11-2026 al 13-11-2026</td>
<td style="text-align: left;">Dra. Sofía Benavides</td>
</tr>
<tr class="even">
<td style="text-align: left;">Correlación clínico-patológica</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">17-11-2026 al 20-11-2026</td>
<td style="text-align: left;">Todos los docentes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Semana Universitarias</td>
<td style="text-align: left;">17</td>
<td style="text-align: left;">23-11-2026 al 27-11-2026</td>
<td style="text-align: left;">Todos</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tercera evaluación teórico-práctica (30%)</td>
<td style="text-align: left;">18</td>
<td style="text-align: left;">30-11-2026 al 04-12-2026</td>
<td style="text-align: left;">Todos los docentes; la fecha de diciembre figura así en el original</td>
</tr>
</tbody>
</table>
</section>
<section id="distribución-semanal-de-rotaciones-prácticas-o-laboratorios" class="level3">
<h3 class="anchored" data-anchor-id="distribución-semanal-de-rotaciones-prácticas-o-laboratorios">7.2 Distribución semanal de rotaciones, prácticas o laboratorios</h3>
<p>Las rotaciones prácticas de patología se realizan los lunes y miércoles de 2:00 a 3:00 p.m. en el sitio de rotación <a href="#bookmark=id.q3bqtfr76qf">Anexo D</a> y G. La correlación clínico-patológica se desarrolla de forma transversal a lo largo del semestre, en grupos con tutor.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 10%">
<col style="width: 20%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Rotación / Práctica / Laboratorio</th>
<th style="text-align: left;">Semana</th>
<th style="text-align: left;">Fecha(s)</th>
<th style="text-align: left;">Observaciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rotaciones prácticas de patología</td>
<td style="text-align: left;">1–17</td>
<td style="text-align: left;">Por definir.</td>
<td style="text-align: left;">Lunes y miércoles, 2:00 a 3:00 p.m., en el sitio de rotación; orientadas por un docente. Una rotación por unidad temática</td>
</tr>
<tr class="even">
<td style="text-align: left;">Correlación clínico-patológica (caso asignado por grupo)</td>
<td style="text-align: left;">1–16</td>
<td style="text-align: left;">Por definir.</td>
<td style="text-align: left;">Viernes, 2:00 a 3:00 p.m., con tutor; socialización y reporte de caso en la última semana</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="referencias" class="level2">
<h2 class="anchored" data-anchor-id="referencias">8 Referencias</h2>
<ol type="1">
<li><p>Robbins. Patología Humana. 9ª Edición. Elsevier.</p></li>
<li><p>Kumar V, Cotran RS, Robbins SL. Patología Estructural y Funcional. 6ª Edición. McGraw-Hill.</p></li>
<li><p>Chandrasoma P, Taylor CR. Patología General. 1ª Edición. Editorial El Manual Moderno.</p></li>
<li><p>Atlas of Tumor Pathology. AFIP. Colección de la biblioteca del Departamento de Patología.</p></li>
<li><p>Ackerman, Rosai. Patología Quirúrgica.</p></li>
<li><p>Anderson, Kissane. Pathology.</p></li>
<li><p>Human Pathology. Revistas mensuales.</p></li>
<li><p>Schaumburg, Lever. Histopathology of the Skin, Vol. I. Editorial Lippincott.</p></li>
<li><p>Lever. Atlas of Histopathology of the Skin. Biblioteca del Departamento de Patología.</p></li>
<li><p>Patología General. Fundamentos de Medicina. Universidad de Antioquia. 1ª Edición.</p></li>
</ol>
</section>
<section id="anexos" class="level2">
<h2 class="anchored" data-anchor-id="anexos">9 Anexos</h2>
<section id="anexo-a-competencias-y-criterios-de-desempeño" class="level3">
<h3 class="anchored" data-anchor-id="anexo-a-competencias-y-criterios-de-desempeño">Anexo A — Competencias y criterios de desempeño</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 41%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Categoría</th>
<th style="text-align: left;">Competencia de la asignatura</th>
<th style="text-align: left;">Criterio de desempeño</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Generales · Cognitivas, Ciudadanas, Inglés, TIC</td>
<td style="text-align: left;">Respetar los principios, leyes y normas que protejan la vida, la dignidad y el bienestar de personas y colectivos, actuando con autonomía, ética y compromiso en la protección, el cuidado y la recuperación de la salud de personas, familias y comunidades.</td>
<td style="text-align: left;">En el desempeño de la asignatura los estudiantes aplican actitudes basadas en la ética profesional, la autonomía, los conocimientos clínicos, el análisis crítico, la responsabilidad social y el trabajo en equipo; muestran comprensión de textos científicos en inglés y habilidades de comunicación, asegurando su preparación para la práctica médica.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Del ser · Actitudinales, Afectivas, Éticas/bioéticas</td>
<td style="text-align: left;">1. Cultivar en los estudiantes de Patología Especial, a través de las correlaciones clínico-patológicas, los valores de ética, respeto, confidencialidad, responsabilidad, veracidad y vocación de servicio. 2. Practicar los principios de convivencia ciudadana y de ética médica que contribuyen al ejercicio profesional idóneo, honesto, integral y pertinente. 3. Interesarse por su aprendizaje de manera permanente, responsable y participativa.</td>
<td style="text-align: left;">1. Los estudiantes manifiestan un compromiso con los valores de ética, respeto y responsabilidad en las correlaciones clínico-patológicas, mostrando su vocación de servicio hacia los pacientes. 2. Los estudiantes aplican principios de convivencia ciudadana y ética médica, garantizando un ejercicio profesional honesto e integral. 3. Los estudiantes demuestran un interés activo y permanente en su aprendizaje, participando de manera responsable y colaborando en el proceso educativo.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Del saber · Conocimientos, Comprensión, Problematización</td>
<td style="text-align: left;">1. Indagar, analizar y discernir la información científica, tecnológica y legal que le sirva de base para tomar decisiones y conductas pertinentes con su labor profesional. 2. Investigar y comprender los cinco aspectos comunes a toda enfermedad: etiología, patogenia, cambios morfológicos y funcionales, y su significancia clínica. 3. Establecer diferencias morfológicas, tanto macroscópicas como microscópicas, en cada uno de los tejidos y órganos afectados por una enfermedad.</td>
<td style="text-align: left;">1. Los estudiantes muestran habilidad para indagar, analizar y discernir información científica y legal, utilizándola para tomar decisiones informadas. 2. Los estudiantes investigan y comprenden los cinco aspectos comunes a toda enfermedad, aplicando este conocimiento a la interpretación de casos clínicos. 3. Los estudiantes establecen diferencias morfológicas macro y microscópicas en los tejidos y órganos afectados, aplicando conocimientos teóricos al análisis de muestras y casos.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Del saber-hacer · Aptitudes, Habilidades, Destrezas</td>
<td style="text-align: left;">1. Correlacionar los conceptos teóricos de las bases de la enfermedad con los aspectos prácticos y clínicos de las patologías de órganos y sistemas especializados. 2. Interpretar y analizar correctamente la información de todo estudio citológico y de anatomía patológica, incluyendo los recursos tecnológicos disponibles. 3. Utilizar los conocimientos adquiridos para realizar un enfoque sistemático de la enfermedad y orientar los estudios diagnósticos y de manejo. 4. Orientar al paciente y su familia sobre el cuidado de la salud y el entendimiento de su enfermedad.</td>
<td style="text-align: left;">1. Los estudiantes relacionan conceptos teóricos con aspectos prácticos y clínicos, mejorando su comprensión de las patologías. 2. Los estudiantes interpretan y analizan correctamente los estudios citológicos y de anatomía patológica, con conocimiento de los recursos tecnológicos de diagnóstico. 3. Los estudiantes realizan un enfoque sistemático en el diagnóstico y manejo de la enfermedad. 4. Los estudiantes orientan al paciente y su familia sobre el cuidado de la salud, promoviendo una comunicación efectiva y el empoderamiento del paciente.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Del convivir y comunicar · Relaciones, Interculturales, Educativas</td>
<td style="text-align: left;">1. Fomentar una comunicación asertiva frente a la condición clínico-patológica del paciente, involucrando al grupo familiar. 2. Respetar los derechos del paciente en el marco del ejercicio profesional ético e idóneo. 3. Establecer una comunicación académica abierta y comprensiva con los compañeros de estudio y los docentes.</td>
<td style="text-align: left;">1. Los estudiantes fomentan una comunicación asertiva sobre la condición clínico-patológica del paciente, involucrando al grupo familiar. 2. Los estudiantes respetan los derechos del paciente, asegurando un ejercicio profesional ético e idóneo. 3. Los estudiantes establecen una comunicación académica abierta y comprensiva con compañeros y docentes, promoviendo un ambiente de colaboración y aprendizaje.</td>
</tr>
</tbody>
</table>
</section>
<section id="anexo-b-contenidos-detallados-por-sistema" class="level3">
<h3 class="anchored" data-anchor-id="anexo-b-contenidos-detallados-por-sistema">Anexo B — Contenidos detallados por sistema</h3>
<p>Cada tema comprende 5 horas semanales de clase teórica (CM), 3 horas semanales de rotación práctica orientada por un docente y 7 horas semanales de trabajo independiente y correlación clínico-patológica (TU). Libro guía de todos los temas: Robbins. Patología Humana. 9ª edición. Elsevier.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 29%">
<col style="width: 62%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">#</th>
<th style="text-align: left;">Tema</th>
<th style="text-align: left;">Contenido</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Páncreas y riñón</td>
<td style="text-align: left;">Malformaciones congénitas, pancreatitis, neoplasias. Glomerulopatías, enfermedades tubulointersticiales, vasculopatías, nefropatías quísticas, obstrucciones.</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Vías urinarias bajas y genital masculino</td>
<td style="text-align: left;">Vías urinarias bajas: uréter, vejiga, uretra. Pene, testículos y epidídimo, próstata.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Sistema nervioso central</td>
<td style="text-align: left;">Edema cerebral, hidrocefalia, malformaciones, traumatismos, enfermedad cerebrovascular, infecciones, tumores.</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Sistema endocrino</td>
<td style="text-align: left;">Hipófisis, glándula tiroides, paratiroides, páncreas endocrino, glándula suprarrenal.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Corazón y vasos sanguíneos</td>
<td style="text-align: left;">Generalidades, insuficiencia cardíaca, cardiopatías congénitas, cardiopatía isquémica, cardiopatía hipertensiva, cardiopatía valvular, miocardiopatías.</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">Tubo digestivo</td>
<td style="text-align: left;">Malformaciones congénitas; esófago, estómago, intestino delgado y grueso; tumores.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">Leucocitos, ganglio linfático y timo</td>
<td style="text-align: left;">Desarrollo del sistema hematopoyético, leucopenias, proliferaciones reactivas, neoplasias linfoides y mieloides, esplenomegalia, timo.</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">Cabeza y cuello</td>
<td style="text-align: left;">Cavidad oral: lesiones inflamatorias y pseudotumorales, infecciones, tumores. Vías respiratorias altas, oído, cuello, glándulas salivales.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">Hueso, articulaciones y tejidos blandos</td>
<td style="text-align: left;">Crecimiento y desarrollo óseo, anomalías congénitas, fracturas, infecciones, tumores.</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">Hígado y vía biliar</td>
<td style="text-align: left;">Características generales de la enfermedad hepática, infecciones, hepatitis autoinmune, hepatopatía metabólica, cirrosis, tumores.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: left;">Pulmón</td>
<td style="text-align: left;">Anomalías congénitas, edema pulmonar, neumopatías obstructivas y restrictivas, enfermedades intersticiales, enfermedades granulomatosas, enfermedades vasculares, infecciones, tumores.</td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: left;">Aparato genital femenino</td>
<td style="text-align: left;">Trastornos del desarrollo, inflamaciones, lesiones epiteliales benignas, tumores estromales.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: left;">Patología de mama</td>
<td style="text-align: left;">Carcinoma de mama y su clasificación, tumores estromales.</td>
</tr>
</tbody>
</table>
</section>
<section id="anexo-c-directrices-de-la-correlación-clínico-patológica" class="level3">
<h3 class="anchored" data-anchor-id="anexo-c-directrices-de-la-correlación-clínico-patológica">Anexo C — Directrices de la correlación clínico-patológica</h3>
<p>La correlación clínico-patológica se lleva a cabo durante el semestre. Los estudiantes se dividen en grupos; a cada grupo se le asigna un tutor y un caso clínico en el que trabaja a lo largo del semestre. En la última semana se realiza la socialización, con estos aspectos:</p>
<ul>
<li><p>Cada grupo dispone de 30 minutos para la exposición y 10 minutos para responder preguntas.</p></li>
<li><p>El formato de la presentación es libre.</p></li>
<li><p>La evaluación de la exposición la realizan los docentes del Departamento y se califica.</p></li>
<li><p>Los estudiantes presentan a cada tutor el caso clínico redactado en formato de reporte de caso, para su posible publicación en la revista de la Facultad de Ciencias de la Salud (<a href="https://revistas.unicauca.edu.co/index.php/rfcs/about/submissions">https://revistas.unicauca.edu.co/index.php/rfcs/about/submissions</a>).</p></li>
</ul>
</section>
<section id="anexo-d-cronograma-de-rotaciones" class="level3">
<h3 class="anchored" data-anchor-id="anexo-d-cronograma-de-rotaciones">Anexo D — Cronograma de Rotaciones</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>CADA GRUPO REALIZARÁ ACTIVIDAD DURANTE 4 DÍAS HÁBILES POR CADA ROTACIÓN</th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>Citología cervicouterina</td>
<td>Patología quirúrgica</td>
<td>Patología molecular</td>
<td>Inmunología básica aplicada.</td>
<td>Patología Endocrina</td>
<td>Patología Gastrointestinal</td>
</tr>
<tr class="even">
<td>SITIO DE PRÁCTICA</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>Centro Universitario en Salud “Alfonso López”</td>
<td>CPC compañía de patólogos del cauca</td>
<td>FCS</td>
<td>FCS</td>
<td>FCS</td>
<td>FCS</td>
</tr>
<tr class="even">
<td>Docentes</td>
<td>Jeison Casallas</td>
<td>Jaime Álvarez</td>
<td>Rosa Dueñas</td>
<td>Victoria Niño</td>
<td>Ivonne Meza</td>
<td>Harold Bolaños</td>
</tr>
<tr class="odd">
<td>3 al 24 de agosto</td>
<td>Semana de inducción</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>26 de agosto al 14 de septiembre</td>
<td>Grupo 1</td>
<td>Grupo 2</td>
<td>Grupo 3</td>
<td>Grupo 4</td>
<td>Grupo 5</td>
<td>Grupo 6</td>
</tr>
<tr class="odd">
<td>16 al 28 de septiembre</td>
<td>Grupo 6</td>
<td>Grupo 1</td>
<td>Grupo 2</td>
<td>Grupo 3</td>
<td>Grupo 4</td>
<td>Grupo 5</td>
</tr>
<tr class="even">
<td>30 de septiembre al 7 de octubre</td>
<td>Grupo 5</td>
<td>Grupo 6</td>
<td>Grupo 1</td>
<td>Grupo 2</td>
<td>Grupo 3</td>
<td>Grupo 4</td>
</tr>
<tr class="odd">
<td>19 al 26 de octubre</td>
<td>Grupo 4</td>
<td>Grupo 5</td>
<td>Grupo 6</td>
<td>Grupo 1</td>
<td>Grupo 2</td>
<td>Grupo 3</td>
</tr>
<tr class="even">
<td>28 de octubre al 9 de noviembre</td>
<td>Grupo 3</td>
<td>Grupo 4</td>
<td>Grupo 5</td>
<td>Grupo 6</td>
<td>Grupo 1</td>
<td>Grupo 2</td>
</tr>
<tr class="odd">
<td>11, 17 y 18 de noviembre</td>
<td>Grupo 2</td>
<td>Grupo 3</td>
<td>Grupo 4</td>
<td>Grupo 5</td>
<td>Grupo 6</td>
<td>Grupo 1</td>
</tr>
</tbody>
</table>
<p><strong>Anexo E. Rúbrica para evaluación oral general</strong></p>
<p>Nota 1: Insuficiente. Necesita mejorar con apoyo</p>
<p>Tiene un discurso no coherente con la información, no es fiable ni relevante en sus afirmaciones, además tiene dificultades para expresar las ideas y conceptos básicos, no demuestra la lectura de los mismos. Además, los análisis y la interpretación no son congruentes con los resultados de aprendizaje. No relaciona la terminología médica nueva con conceptos básicos de fisiopatología tampoco demuestra conocimientos prácticos recibidos.</p>
<p>Nota 2: Insuficiente. Necesidad de mejora superable</p>
<p>Tiene un discurso coherente, con la información tiene dificultades para expresar las ideas y conceptos básicos, pero demuestra la lectura de los mismos. Además, los análisis y la interpretación no son congruentes con los resultados de aprendizaje. No relaciona la terminología médica nueva con conceptos básicos de fisiopatología ni la práctica.</p>
<p>Nota 3: Regular</p>
<p>Tiene un discurso coherente, con la información, puede expresar las ideas y conceptos básicos y demuestra la lectura de los mismos. Pero los análisis y la interpretación no son congruentes con los resultados de aprendizaje. Relaciona la terminología médica nueva con conceptos básicos de fisiopatología, pero sin correlacionar con la práctica.</p>
<p>Nota 4: Bueno</p>
<p>Tiene un discurso coherente, con la información expresa las ideas y conceptos básicos, de la menta clara, demuestra la lectura de los mismos. Demuestra en su discurso los análisis y la interpretación de manera congruente y lógica de acuerdo con los resultados de aprendizaje. No relaciona la terminología médica nueva con conceptos básicos de fisiopatología ni la práctica.</p>
<p>Nota 5: Excelente</p>
<p>Tiene un discurso coherente, con la información expresa las ideas y conceptos básicos, de la menta clara, demuestra la lectura de los mismos. Demuestra en su discurso los análisis y la interpretación de manera congruente y lógica de acuerdo con los resultados de aprendizaje. Relaciona la terminología médica nueva con conceptos básicos de fisiopatología y demuestra con la práctica.</p>
<p><strong>Anexo F. Evaluación Oral Utilizando Powerpoint</strong></p>
<p><strong>Introducción</strong></p>
<p>Entre las prácticas de evaluación tradicionales de los aprendizajes, para los estudiantes de medicina, se usan las evaluaciones orales y las evaluaciones escritas. Las evaluaciones orales han sido utilizadas durante muchos años y, a pesar de algunas críticas y limitaciones, se continúan aplicando en la actualidad, como una manera de medir los aprendizajes de los estudiantes, así como sus competencias comunicativas.</p>
<p><strong>Se describen varios tipos de evaluaciones orales</strong>:</p>
<ul>
<li><p>De base no estructurada, que no parten de una guía de preguntas, sino que dejan en libertad al estudiante para responder alrededor del tema, por ejemplo: “Hable sobre sobre la falla cardiaca…”</p>
<p>De base estructurada, que utilizan preguntas o situaciones problémicas, previamente elaboradas, para que el estudiante responda de forma breve, clara y precisa.</p></li>
</ul>
<p><strong>Ventajas y desventajas de la evaluación oral</strong></p>
<p>Los procesos evaluativos no son ajenos a tener ventajas y desventajas para cada una de las partes que participan en el proceso (estudiante – docente), por lo que a continuación se describen algunas de ellas:</p>
<p><strong>Ventajas de la evaluación oral</strong></p>
<ul>
<li><p>Sirven para evaluar los aprendizajes a niveles taxonómicos complejos, que incluyen entre otros el dominio del lenguaje específico de la disciplina que se aprende</p>
<p>Son útiles para confirmar las competencias adquiridas a nivel oral</p>
<p>Benefician a los estudiantes que tienen mayor facilidad con la expresión oral</p>
<p>Se logran unos mejores resultados, pues los estudiantes deben invertir más tiempo y dedicación en su preparación</p>
<p>Durante la evaluación los estudiantes pueden recibir algunas pistas, por parte del docente, que le ayuden a elaborar la respuesta</p>
<p>Permiten una mayor argumentación por parte del estudiante, con el fin de dar a entender al docente el dominio del tema</p>
<p>La revisión y retroalimentación se hace de manera inmediata</p></li>
</ul>
<p><strong>Desventajas de la evaluación oral</strong></p>
<ul>
<li><p>Genera mayor ansiedad en el estudiante en comparación con una evaluación escrita</p>
<p>El número de preguntas que se pueden realizar es limitado cuando se manejan grupos de estudiantes numerosos y en ocasiones no es posible abarcar la totalidad de los temas a evaluar, lo que en ocasiones genera inconformidad en los estudiantes.</p>
<p>El estudiante se queja del poco tiempo para elaborar la respuesta y en ocasiones afirma que se ha “bloqueado” mentalmente.</p>
<p>Esta influenciada por los rendimientos anteriores de los estudiantes</p>
<p>Generalmente no queda registro de las respuestas</p>
<p>Algunas veces no son bien planificadas</p>
<p>Tienen baja confiabilidad</p>
<p>Exigen habilidad verbal (buena competencia comunicativa)</p>
<p>Puede presentarse fatiga del examinador, que está relacionada con el número de estudiantes a evaluar</p>
<p>Se presentan influencias por parte del grupo, los estudiantes se intimidan a veces frente a sus propios compañeros y frente al docente</p>
<p>Por parte del docente, pueden influir sus simpatías o antipatías con el estudiante a evaluar, el estado de ánimo, la capacidad de atención del docente, entre otras</p>
<p>Falta de entrenamiento por parte de los estudiantes y evaluadores en la realización de evaluaciones orales.</p></li>
</ul>
<blockquote class="blockquote">
<p>Con base en estas características, en las evaluaciones orales, la confiabilidad y validez de las pruebas orales han sido durante mucho tiempo cuestionadas, no obstante, se deben buscar iniciativas tendientes a disminuir las desventajas, sin que esta pierda las ventajas que tienen las evaluaciones orales, a través del uso de procesos de estandarización que reduzcan la heterogeneidad de su aplicación y mejoren su objetividad y reproducibilidad.</p>
</blockquote>
<p><strong>Propósito</strong></p>
<p>Buscar un método de evaluación, alternativo a la evaluación oral tradicional, utilizando una herramienta de office como el PowerPoint que, sin sustituirla, permita disminuir algunas de las desventajas de la evaluación oral y potenciar las ventajas de este proceso evaluativo.</p>
<p><strong>Recursos tecnológicos a utilizar</strong></p>
<p>Computador portátil o de mesa que cuente con el programa office y dentro de ella la aplicación PowerPoint, un micrófono con diadema. (micrófono y audífono)</p>
<p>!(media/image7.png){width=“2.2604166666666665in” height=“1.6131944444444444in”}</p>
<p><strong>Metodología</strong></p>
<p>Para la realización de esta evaluación se estructuran, una serie de preguntas relacionadas con los temas que se abordan durante la asignatura, incluyendo preguntas de base no estructurada y estructurada.</p>
<p>La evaluación se lleva a cabo utilizando la aplicación PowerPoint, que se muestra a continuación, la cual está al alcance de cualquier profesor, sin que se requiera una gran infraestructura de tipo audiovisual. Imagen 1</p>
<p>!(media/image5.png){width=“5.327293307086614in” height=“2.844676290463692in”}</p>
<p>Imagen 1. Pantalla de presentación de la plantilla PowerPoint de inicio.</p>
<p>En primer lugar, se hace la presentación a los estudiantes de la metodología que se va a usar durante la prueba como se ilustra a continuación. Imagen 2</p>
<p>!(media/image6.png){width=“6.1375in” height=“3.2521008311461066in”}</p>
<p>Imagen 2. Pantalla inicial donde el estudiante puede, además de las instrucciones del docente, volver a leer la forma como debe proceder para grabar sus respuestas.</p>
<p>Antes de iniciar la prueba el docente debe estar seguro que los estudiantes han comprendido y asimilado bien la metodología a usar.</p>
<p>El docente debe estar pendiente de las posibles preguntas o inquietudes que se puedan presentar, por parte de los estudiantes, durante el desarrollo de la prueba.</p>
<p>A continuación, se muestra algunos de los ejemplos de los tipos de preguntas que se pueden realizar de base no estructurada y estructurada. Imágenes 3,4,5,6.</p>
<p>!(media/image9.png){width=“6.1375in” height=“3.260504155730534in”}</p>
<p>Imagen 3. Pregunta de tipo estructurada, en donde se muestra un contexto, sobre el tema central de la pregunta.</p>
<p>!(media/image10.png){width=“6.1375in” height=“3.2521008311461066in”}</p>
<p>Imagen 4. Pregunta de tipo estructurada en donde, con la ayuda de una imagen de un paciente, se ilustra el contexto clínico, sobre el cual se elabora la pregunta.</p>
<p>!(media/image1.png){width=“6.1375in” height=“3.2521008311461066in”}</p>
<p>Imagen 5. Pregunta estructurada, en la cual con la ayuda de un cuadro sinóptico, que aparece en el libro guía de estudio, se pregunta sobre algunos de los temas que complementan la patología en estudio.</p>
<p>!(media/image8.png){width=“6.1375in” height=“3.260504155730534in”}</p>
<p>Imagen 6. Pregunta no estructurada en la cual, con la ayuda de un espécimen quirúrgico, se propicia un contexto, para que el estudiante, con base en el tema de revisión, elabore una propuesta tendiente a prevenir el desarrollo de esta enfermedad.</p>
<p>Al terminar la prueba, el estudiante se lleva el archivo que incluye las preguntas y el audio gravado, el cual debe confrontar con las respuestas que aparecen en la guía de la evaluación, con el fin de garantizar un proceso de retroalimentación y favorecer la evaluación como otro espacio para el aprendizaje.</p>
<p>Una vez realizada la revisión del audio por parte del estudiante, se cita nuevamente para una revisión con el tutor y de esta manera despejar las dudas o inquietudes que aún persistan por parte de los estudiantes y sacar la nota definitiva de la evaluación.</p>
<p>Buscando estandarizar la calificación de las respuestas, por parte del docente, se usa la siguiente rúbrica.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Criterio de evaluación</th>
<th>Escala de valoración</th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>0</td>
<td>0</td>
<td>25%</td>
<td>50%</td>
<td>75%</td>
<td>100%</td>
</tr>
<tr class="even">
<td>Contenido</td>
<td>No contesta</td>
<td>Contesta, pero la respuesta es incorrecta</td>
<td>Contesta solo la menor parte de la pregunta</td>
<td>Contesta la mitad de la pregunta</td>
<td>Faltó poco para lograr una respuesta completa</td>
<td>Contesta correctamente la pregunta en su totalidad</td>
</tr>
<tr class="odd">
<td>Vocabulario</td>
<td>No contesta</td>
<td>Contesta, pero no usa el vocabulario correcto para sustentar su respuesta</td>
<td>Contesta usando solo algunas veces el vocabulario propio de la disciplina</td>
<td>En su respuesta usa el vocabulario propio de la disciplina en de manera parcial.</td>
<td>En su respuesta usa en la mayor parte de las veces el vocabulario apropiado de la disciplina</td>
<td>Contesta a la pregunta usando palabras y frases que están en relación con el vocabulario propio de la disciplina</td>
</tr>
<tr class="even">
<td>Capacidad comunicativa</td>
<td>No contesta</td>
<td>No elabora respuestas de una manera lógica y organizada</td>
<td>Las respuestas solo muestran una ligera estructuración y claridad en su contenido</td>
<td>Las respuestas son parcialmente estructuradas y claras en su contenido</td>
<td>La respuesta en un gran porcentaje está bien estructurada y clara en su contenido</td>
<td>La respuesta muestra una adecuada estructuración y claridad en su contenido</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Aspectos que se esperan mejorar con esta propuesta</strong></p>
<ul>
<li><p>Disminuir el factor estresor que se presenta en los estudiantes cuando están frente a una evaluación oral tradicional, pues en este tipo de propuesta, el estudiante está contestando cada una de las preguntas frente al ordenador, con el acompañamiento del docente.</p>
<p>Aumentar el número de preguntas de la prueba, que permita una evaluación mas global de las temáticas tratadas y de esta manera mejorar también la probabilidad de obtener por parte de los grupos unos mejores resultados.</p>
<p>Evaluar a los estudiantes con el mismo tipo de preguntas en cuanto al nivel de complejidad y numero de oportunidades.</p>
<p>Dejar un registro de la prueba de tal forma que pueda servir para procesos de autoevaluación y de revisión de la misma, en caso de ser necesario</p>
<p>Mejorar la confiabilidad de la prueba.</p>
<p>Disminuir la fatiga del examinador, quien en un segundo tiempo puede, de una manera mas relajada, evaluar la calidad de las respuestas de los estudiantes, repasando cada uno de los audios grabados por los estudiantes</p>
<p>Evitar que las simpatías o antipatías del docente con los estudiantes influyen de manera favorable o desfavorable en los resultados de la prueba, pues las preguntas están organizadas de la misma manera para todos los estudiantes.</p>
<p>Las respuestas de la prueba van a estar consignadas en una rúbrica, en los cuales están establecidos los criterios mínimos, medios y altos de cada una de las respuestas, la cual debe ser tenida en cuenta por el evaluador.</p></li>
</ul>
<p>Aspectos que aún quedan pendientes por mejorar</p>
<ul>
<li><p>Trabajar sobre una mejor estructuración de las preguntas con la participación de los docentes de la disciplina.</p>
<p>Buscar que no se pierda del todo la interacción directa entre el docente y el estudiante durante el proceso evaluativo.</p>
<p>Crear una rubrica conjunta de evaluación con la participación de todos los docentes de la asignatura, la cual deberá ser socializada a los estudiantes antes de la evaluación.</p></li>
</ul>
<p>BIBLIOGRAFÍA</p>
<ol start="3" type="1">
<li><p>Jabif Liliana, Orientaciones prácticas para la docencia. La docencia universitaria bajo un enfoque de competencias. Universidad Austral de Chile. 2007</p></li>
<li><p>Venturelli José, Educación Médica. Nuevos enfoques, metas y métodos. Organización Panamericana de la Salud. 1997</p></li>
<li><p>Merino Luis A, exámenes orales vs exámenes escritos, ventajas e inconvenientes. Facultad de Medicina UNNE. Corrientes Argentina. 2001.</p></li>
<li><p>Salazar Claudia, informe sobre pruebas orales. Universidad Católica Andrés Bello. Marzo 2012.</p></li>
<li><p>Panaccio Matias, la evaluación oral, en el proceso de la evaluación final. 2011.</p></li>
<li><p>Muller Martha, texto sobre técnicas de comunicación oral. 2014</p></li>
<li><p>Pruebas y exámenes orales, procedimientos de evaluación auténtica, procedimientos evaluativos utilizados en el aula. Universidad de las Américas. <a href="http://www.udla.cl/portales/tp9e00af339c16/uploadImg/File/fichas/Ficha-13-pruebas-examenes-orales.pdf">http://www.udla.cl/portales/tp9e00af339c16/uploadImg/File/fichas/Ficha-13-pruebas-examenes-orales.pdf</a></p></li>
</ol>
<p><strong>Anexo G. Formato De Prácticas Formativas</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>FORMATO DE PRÁCTICAS FORMATIVAS</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>Universidad del Cauca Facultad Ciencias de la Salud</td>
<td>Periodo Académico: 2026 - 2</td>
<td>Versión</td>
</tr>
<tr class="even">
<td></td>
<td>Asignatura: Patología Especial – Rote de citología ginecológica</td>
<td>Docentes: Jeison Andrés Casallas Beltrán</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>Coordinador de asignatura: Victoria Niño</td>
<td>Rotación: citología ginecológica</td>
<td></td>
</tr>
<tr class="even">
<td>Fecha de Inicio: 26 de agosto de 2026</td>
<td>Correo electrónico: jeisoncasallas@unicauca.edu.co Teléfono de contacto: 3147757899</td>
<td></td>
<td>Horario y días de rotación: lunes de 2 a 4 p.m. Miércoles de 2 a 4 pm</td>
</tr>
<tr class="odd">
<td>Fecha de terminación: 18 de noviembre de 2026</td>
<td>Escenario de Práctica: Centro de salud – Alfonso López</td>
<td>Lugar: Consultorio Amigo</td>
<td></td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Objetivo de la rotación</th>
<th>Competencias</th>
<th>Actividades y Procedimientos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OBJETIVO DEL ROTE DE CITOLOGÍA GINECOLÓGICA Realizar una adecuada recolección de la muestra cervical y estudio microscópico de la misma.</td>
<td>Reconocimiento de los diferentes tipos celulares que se observan en un extendido de citología ginecológica “exocérvix, zona de transformación, endocérvix y endometrio”, pasando por los cambios de tipo benigno, hasta alcanzar un espectro de malignidad.</td>
<td>Manipula el microscópico binocular Reconocimiento macroscópico de un extendido citológico Evalúa la calidad de la muestra Reconoce los diferentes tipos celulares Emite juicios sobre las diferentes características morfológicas de la celularidad estudiada Reconoce en las células criterios que sugieren alteraciones a nivel nuclear y citoplasmático</td>
</tr>
<tr class="even">
<td></td>
<td>Desarrolla habilidad y destreza en la manipulación de los diferentes equipos y aplicación de la correcta técnica a la hora de hacer la recolección de la muestra ginecológica.</td>
<td>Conoce y aplica la técnica de recolección de la muestra “Laboratorio de simulaciones” Conoce y aplica el consentimiento informado. Brinda atención humanizada. Conoce y diligencia el formato universal de Bethesda. Conoce y aplica la técnica de recolección de la muestra “CUS”</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Delegación Progresiva</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Actividades y/o Procedimientos</td>
<td>Observa</td>
<td>Actúa acompañado con su docente</td>
<td>Actúa solo supervisado por el docente</td>
</tr>
<tr class="even">
<td>1. Buen manejo del microscopio binocular</td>
<td>x</td>
<td>x</td>
<td>X</td>
</tr>
<tr class="odd">
<td>2. Reconoce características microscópicas de las diferentes estirpes celulares</td>
<td>x</td>
<td>x</td>
<td>X</td>
</tr>
<tr class="even">
<td>3. Reconoce en las células cambios asociados a procesos reactivos</td>
<td>x</td>
<td>x</td>
<td>x</td>
</tr>
<tr class="odd">
<td>4. Identifica microscópicamente los diferentes microorganismos que podemos encontrar en un extendido de citología ginecológica.</td>
<td>x</td>
<td>x</td>
<td>x</td>
</tr>
<tr class="even">
<td>5. Analiza e identifica cambios que sugieren malignidad en los diferentes epitelios</td>
<td>x</td>
<td>x</td>
<td>X</td>
</tr>
<tr class="odd">
<td>7. Realiza práctica en el laboratorio de simulaciones de la facultad</td>
<td>x</td>
<td>x</td>
<td>x</td>
</tr>
<tr class="even">
<td>8. Se familiariza con los insumos y escenario de práctica.</td>
<td>x</td>
<td>x</td>
<td>x</td>
</tr>
<tr class="odd">
<td>9. Realiza la recolección de la muestra.</td>
<td>x</td>
<td>x</td>
<td>x</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Estrategias pedagógicas utilizadas durante la rotación</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aplica (X)</td>
<td>Estrategia pedagógica</td>
<td>Descripción</td>
<td>Evidencia esperada</td>
</tr>
<tr class="even">
<td>X</td>
<td>Demostración guiada</td>
<td>Observación y análisis de piezas macroscópicas, preparados histológicos y citológicos bajo supervisión docente.</td>
<td>Identificación correcta de lesiones y estructuras.</td>
</tr>
<tr class="odd">
<td>X</td>
<td>Práctica supervisada</td>
<td>Interpretación de láminas histopatológicas y citológicas con acompañamiento del docente.</td>
<td>Registro de actividades y retroalimentación.</td>
</tr>
<tr class="even">
<td>X</td>
<td>Seminarios de actualización</td>
<td>Presentación de temas asignados con soporte en literatura científica reciente.</td>
<td>Exposición y discusión académica.</td>
</tr>
<tr class="odd">
<td>X</td>
<td>Aula invertida</td>
<td>Revisión previa de guías y artículos científicos para favorecer la discusión durante la rotación.</td>
<td>Participación activa durante las sesiones.</td>
</tr>
<tr class="even">
<td>X</td>
<td>Retroalimentación formativa</td>
<td>Retroalimentación individual y grupal posterior a cada actividad académica.</td>
<td>Plan de mejora individual.</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
</section>
<section id="section-1" class="level2">
<h2 class="anchored" data-anchor-id="section-1"></h2>
</section>
<section id="section-2" class="level2">
<h2 class="anchored" data-anchor-id="section-2"></h2>
</section>
<section id="rúbrica-evaluativa" class="level2">
<h2 class="anchored" data-anchor-id="rúbrica-evaluativa">Rúbrica evaluativa</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>1. Rúbrica para interpretación de láminas citológicas 50%</th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Criterio</td>
<td>Excelente (5)</td>
<td>Bueno (4)</td>
<td>Aceptable (3)</td>
<td>Insuficiente (1-2)</td>
</tr>
<tr class="even">
<td>Reconocimiento morfológico</td>
<td>Identifica correctamente células normales que recubren el exocérvix, endocérvix, endometrio y las células pertenecientes a la zona de transformación</td>
<td>Presenta pocas imprecisiones.</td>
<td>Reconoce parcialmente las diferentes estirpes celulares.</td>
<td>No identifica las diferentes estirpes celulares.</td>
</tr>
<tr class="odd">
<td>Reconocimiento morfológico</td>
<td>Identifica correctamente células normales y anormales.</td>
<td>Presenta pocas imprecisiones.</td>
<td>Reconoce parcialmente los cambios estructurales.</td>
<td>No identifica los diferentes cambios estructurales.</td>
</tr>
<tr class="even">
<td>Reconocimiento morfológico</td>
<td>Identifica correctamente las características microscópicas presentes en un proceso infeccioso.</td>
<td>Presenta pocas imprecisiones</td>
<td>Reconoce parcialmente las características microscópicas presentes en un proceso infeccioso.</td>
<td>No identifica las características microscópicas presentes en un proceso infeccioso.</td>
</tr>
<tr class="odd">
<td>Diagnóstico diferencial</td>
<td>Formula interpretaciones diferenciales pertinentes.</td>
<td>Interpretación adecuada con leves omisiones.</td>
<td>Interpretación limitada.</td>
<td>No propone interpretaciones pertinentes.</td>
</tr>
<tr class="even">
<td>Interpretación final</td>
<td>Concordancia mayor al 90 % respecto de la emitida y debidamente argumentada por la persona encargada de guiar la practica formativa.</td>
<td>Concordancia igual 80% respecto de la emitida y debidamente argumentada por la persona encargada de guiar la practica formativa.</td>
<td>Concordancia igual al 60 % respecto de la emitida y debidamente argumentada por la persona encargada de guiar la practica formativa.</td>
<td>Concordancia menor al 50 % respecto de la emitida y debidamente argumentada por la persona encargada de guiar la practica formativa.</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>2. Rúbrica para practica guiada y/o examen 50%</th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Criterio</td>
<td>Excelente (5)</td>
<td>Bueno (4)</td>
<td>Aceptable (3)</td>
<td>Insuficiente (1-2)</td>
</tr>
<tr class="even">
<td>Relación médico – paciente</td>
<td>Demuestra ética, responsabilidad, puntualidad y respeto de manera permanente para con su paciente.</td>
<td>Cumple la mayoría de los criterios.</td>
<td>Presenta algunas dificultades.</td>
<td>Incumple normas básicas.</td>
</tr>
<tr class="odd">
<td>Identificación de la paciente</td>
<td>Diligencia de manera correcta, clara y precisa el formato de Bethesda.</td>
<td>Cumple la mayoría de los criterios.</td>
<td>Presenta algunas dificultades.</td>
<td>No diligencia el formato de Bethesda.</td>
</tr>
<tr class="even">
<td>Bioseguridad</td>
<td>Utiliza de forma correcta los protocolos y elementos de bioseguridad.</td>
<td></td>
<td></td>
<td>No utiliza de forma correcta los protocolos y elementos de bioseguridad.</td>
</tr>
<tr class="odd">
<td>Desempeño práctico – rotulación y especuloscopia.</td>
<td>Realiza correctamente la rotulación de la lámina y el posicionamiento del especulo en la cavidad vaginal, logrando la correcta visualización del cuello uterino.</td>
<td>Desempeño adecuado.</td>
<td>Requiere apoyo frecuente.</td>
<td>No alcanza las competencias esperadas.</td>
</tr>
<tr class="even">
<td>Desempeño práctico – toma de muestras.</td>
<td>Realiza correctamente la técnica para recolectar las muestras propias de la citología ginecológica, empleado para ello el cito cepilló y la espátula de ayre.</td>
<td>Desempeño adecuado.</td>
<td>Presenta algunas dificultades.</td>
<td>No alcanza las competencias esperadas.</td>
</tr>
<tr class="odd">
<td>Desempeño práctico – extendido y fijación celular.</td>
<td>Realiza correctamente el extendido en el porta objetos e inmediatamente fija las células obtenidas.</td>
<td>Desempeño adecuado.</td>
<td>Presenta algunas dificultades.</td>
<td>No alcanza las competencias esperadas.</td>
</tr>
<tr class="even">
<td>Examen escrito “opcional”</td>
<td>Responde correctamente más del 90% de las preguntas, demostrando comprensión integral de la etiología, patogenia y cambios morfológicos.</td>
<td>Responde entre el 80-89%.</td>
<td>Responde entre el 70-79%.</td>
<td>Menos del 70% de respuestas correctas.</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Cronograma de la Rotación de Patología Molecular – 4 sesiones (8 horas totales)</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Día</td>
<td>Horario</td>
<td>Contenido</td>
<td>Responsable</td>
</tr>
<tr class="even">
<td>1</td>
<td>Lunes 2:00 – 4:00 p.m.</td>
<td>Concepto amplio de citología Introducción a la citología ginecológica Celularidad normal, microorganismos y anormalidades celulares.</td>
<td>Jeison Casallas</td>
</tr>
<tr class="odd">
<td>2</td>
<td>Miércoles 2:00 – 4:00 p.m.</td>
<td>Taller guiado de microscopia, donde se observan 5 láminas, con interpretaciones diferentes, casos que incluyen todo lo visto la clase inmediatamente anterior. El taller tiene lugar en la sala de microscopia perteneciente al laboratorio de Microbiología de la facultad.</td>
<td>Jeison Casallas</td>
</tr>
<tr class="even">
<td>3</td>
<td>Lunes 2:00 – 4:00 p.m.</td>
<td>Aspectos generales sobre la recolección de la muestra ginecológica, respondiendo interrogantes como: ¿por qué?, ¿cómo?, ¿desde cuándo?, ¿con que frecuencia?, ¿hasta cuándo? Practica sobre la correcta técnica a la hora hacer la recolección de la muestra citológica. Esta practica tiene lugar en el laboratorio de simulaciones de la facultad.</td>
<td>Jeison Casallas</td>
</tr>
<tr class="odd">
<td>4</td>
<td>Miércoles 2:00 – 4:00 p.m.</td>
<td>Recolección de la muestra de citología ginecológica, la cual se realiza en las instalaciones del Centro Universitario de Salud del barrio Alfonso López. El estudiante también podrá presentar el examen en caso de así querer ser evaluado.</td>
<td>Jeison Casallas</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th>Instrucciones para la recolección de la muestra “opcional” (Día 4)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Respecto de la paciente: No menores de edad. No mujeres embarazadas. Diligenciar el consentimiento informado Informar los tiempos estipulados para la entrega de resultados. Resaltar que en caso de requerir y/o querer realizar consulta con ginecología, tendrá toda la ayuda para ello. Impulsar de manea activa los servicios que presta el Centro Universitario de Salud Respecto del estudiante: Uniforme completo. Carnet estudiantil. Bata limpia. Presentarse a la hora indicada. Consideraciones logísticas: • Cada estudiante se deberá presentar con su paciente en intervalos de 20 minutos.</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Distribución de la Evaluación de la Rotación</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Componente evaluado</td>
<td>Rúbrica</td>
<td>Porcentaje</td>
</tr>
<tr class="even">
<td>Taller de microscopia (día 2)</td>
<td>Rúbrica 1</td>
<td>50%</td>
</tr>
<tr class="odd">
<td>Recolección la muestra y/o examen (Día 4)</td>
<td>Rúbrica 2</td>
<td>50%</td>
</tr>
<tr class="even">
<td>TOTAL</td>
<td></td>
<td>100%</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th>Bibliografía de Referencia Recomendada para la Rotación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>¨ SOLOMON, Diana. El Sistema Bethesda para informar la citología cervical: definiciones, criterios y notas aclaratorias. 1ra ed.&nbsp;Buenos Aires: Journal, 2005. 224 p.;23x16 cm.¨ ¨SOLOMON, Diana. El Sistema Bethesda para informar la citología cervical: definiciones, criterios y notas aclaratorias. 2da ed.&nbsp;Buenos Aires: Journal, 2014. 274 p.;23x16 cm.¨ ¨ DIAZ, Martha. Guía control de calidad para la toma procesamiento e interpretación en muestras de citología de cuello uterino. 1ra ed.&nbsp;Bogotá: Instituto Nacional de Salud y Ministerio de protección social, 2009. 81 p.¨</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>FORMATO DE PRÁCTICAS FORMATIVAS</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>Universidad del Cauca Facultad Ciencias de la Salud</td>
<td>Periodo Académico: 2026 - 2</td>
<td>Versión</td>
</tr>
<tr class="even">
<td></td>
<td>Asignatura: Patología Especial – Rote Inmunología Básica Aplicada.</td>
<td>Docentes: Victoria Eugenia Niño Castaño</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>Coordinador de asignatura: Victoria Niño</td>
<td>Rotación: citología ginecológica</td>
<td></td>
</tr>
<tr class="even">
<td>Fecha de Inicio: 26 de agosto de 2026</td>
<td>Correo electrónico: vnino@unicauca.edu.co Teléfono de contacto: 3108399823</td>
<td></td>
<td>Horario y días de rotación: lunes de 2 a 3 p.m. Miércoles de 2 a 3 pm</td>
</tr>
<tr class="odd">
<td>Fecha de terminación: 18 de noviembre de 2026</td>
<td>Escenario de Práctica: Facultad Ciencias de la Salud</td>
<td>Lugar:</td>
<td></td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Objetivo de la rotación</th>
<th>Competencias</th>
<th>Actividades y Procedimientos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Comprender los fundamentos de la inmunología aplicada y reconocer la utilidad de los anticuerpos y la citometría de flujo como herramientas para el diagnóstico y tratamiento de diferentes enfermedades, mediante la integración de conceptos básicos con el análisis de casos clínicos.</td>
<td>• Explica el origen, estructura y clasificación de los anticuerpos y su función en la respuesta inmune. • Reconoce las aplicaciones diagnósticas y terapéuticas de los anticuerpos.</td>
<td>Sesión 1 (1 hora): Origen, estructura, clasificación y funciones de los anticuerpos. Sesión 2 (1 hora): Aplicaciones de los anticuerpos en el diagnóstico (ELISA, inmunofluorescencia e inmunohistoquímica) y en la terapia (anticuerpos monoclonales).</td>
</tr>
<tr class="even">
<td></td>
<td>• Describe los fundamentos y aplicaciones de la citometría de flujo en el diagnóstico de enfermedades. • Correlaciona los principios de la inmunología con el diagnóstico y manejo de enfermedades mediante el análisis de casos clínicos.</td>
<td>Sesión 3 (1 hora): Fundamentos de la citometría de flujo y aplicaciones en el diagnóstico de inmunodeficiencias, leucemias, linfomas y enfermedades autoinmunes. Sesión 4 (1 hora): Socialización y discusión de casos clínicos, integrando los conceptos de anticuerpos, pruebas inmunológicas y citometría de flujo en el diagnóstico y seguimiento de pacientes.</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Delegación Progresiva</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Actividades y/o Procedimientos</td>
<td>Observa</td>
<td>Actúa acompañado con su docente</td>
<td>Actúa solo supervisado por el docente</td>
</tr>
<tr class="even">
<td>1. Reconoce los componentes de la respuesta inmune innata y adaptativa.</td>
<td>x</td>
<td>x</td>
<td>X</td>
</tr>
<tr class="odd">
<td>2. Identifica el origen, la clasificación y las funciones de las inmunoglobulinas.</td>
<td>x</td>
<td>x</td>
<td>X</td>
</tr>
<tr class="even">
<td>3. Analiza las aplicaciones de los anticuerpos en el diagnóstico y la terapia de enfermedades.</td>
<td>x</td>
<td>x</td>
<td>x</td>
</tr>
<tr class="odd">
<td>4. Reconoce los principios de las pruebas inmunológicas (ELISA, inmunofluorescencia e inmunohistoquímica) y su utilidad clínica.</td>
<td>x</td>
<td>x</td>
<td>x</td>
</tr>
<tr class="even">
<td>5. Comprende los fundamentos de la citometría de flujo y reconoce sus principales aplicaciones diagnósticas.</td>
<td>x</td>
<td>x</td>
<td>X</td>
</tr>
<tr class="odd">
<td>6. Interpreta resultados básicos de citometría de flujo y otras pruebas inmunológicas en casos clínicos.</td>
<td></td>
<td>x</td>
<td>x</td>
</tr>
<tr class="even">
<td>7. Analiza y correlaciona hallazgos inmunológicos con enfermedades infecciosas, autoinmunes, hematológicas y neoplásicas mediante casos clínicos.</td>
<td></td>
<td>x</td>
<td>x</td>
</tr>
<tr class="odd">
<td>8. Participa en la discusión y sustentación de un caso clínico utilizando conceptos de inmunología aplicada.</td>
<td></td>
<td>x</td>
<td>x</td>
</tr>
<tr class="even">
<td>9. Integra los conocimientos adquiridos para plantear el uso de herramientas inmunológicas en el diagnóstico y seguimiento de pacientes.</td>
<td></td>
<td></td>
<td>x</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Estrategias pedagógicas utilizadas durante la rotación</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aplica (X)</td>
<td>Estrategia pedagógica</td>
<td>Descripción</td>
<td>Evidencia esperada</td>
</tr>
<tr class="even">
<td>☐x</td>
<td>Aprendizaje basado en casos clínicos (ABC)</td>
<td>Discusión de casos clínico-patológicos integrando historia clínica, imágenes, hallazgos macroscópicos, microscópicos y otros.</td>
<td>Participación argumentada en la discusión del caso.</td>
</tr>
<tr class="odd">
<td>☐</td>
<td>Correlación clínico-patológica</td>
<td>Integración de los hallazgos clínicos, radiológicos y anatomopatológicos para establecer diagnósticos diferenciales.</td>
<td>Presentación oral del razonamiento diagnóstico.</td>
</tr>
<tr class="even">
<td>☐</td>
<td>Aprendizaje basado en problemas (ABP)</td>
<td>Resolución de problemas diagnósticos utilizando evidencia científica.</td>
<td>Resolución del problema planteado.</td>
</tr>
<tr class="odd">
<td>☐</td>
<td>Demostración guiada</td>
<td>Observación y análisis de piezas macroscópicas, preparados histológicos y citológicos bajo supervisión docente.</td>
<td>Identificación correcta de lesiones y estructuras.</td>
</tr>
<tr class="even">
<td>☐</td>
<td>Práctica supervisada</td>
<td>Interpretación de láminas histopatológicas y citológicas con acompañamiento del docente.</td>
<td>Registro de actividades y retroalimentación.</td>
</tr>
<tr class="odd">
<td>☐</td>
<td>Seminarios de actualización</td>
<td>Presentación de temas asignados con soporte en literatura científica reciente.</td>
<td>Exposición y discusión académica.</td>
</tr>
<tr class="even">
<td>☐</td>
<td>Aula invertida</td>
<td>Revisión previa de guías y artículos científicos para favorecer la discusión durante la rotación.</td>
<td>Participación activa durante las sesiones.</td>
</tr>
<tr class="odd">
<td>☐x</td>
<td>Retroalimentación formativa</td>
<td>Retroalimentación individual y grupal posterior a cada actividad académica.</td>
<td>Plan de mejora individual.</td>
</tr>
</tbody>
</table>
</section>
<section id="rúbrica-evaluativa-1" class="level2">
<h2 class="anchored" data-anchor-id="rúbrica-evaluativa-1">Rúbrica evaluativa</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>2. Rúbrica para presentación de caso clínico-patológico (90%)</th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Criterio</td>
<td>Excelente (5)</td>
<td>Bueno (4)</td>
<td>Aceptable (3)</td>
<td>Insuficiente (1-2)</td>
</tr>
<tr class="even">
<td>Organización de la presentación</td>
<td>Presentación clara, lógica y estructurada.</td>
<td>Presentación organizada con pequeñas dificultades.</td>
<td>Organización aceptable.</td>
<td>Desorganizada.</td>
</tr>
<tr class="odd">
<td>Correlación clínico-patológica</td>
<td>Integra completamente clínica, laboratorio, imágenes y anatomía patológica.</td>
<td>Buena integración con pocas omisiones.</td>
<td>Integración parcial.</td>
<td>No establece correlación.</td>
</tr>
<tr class="even">
<td>Fundamentación científica</td>
<td>Sustenta con literatura actual y evidencia científica.</td>
<td>Bibliografía suficiente.</td>
<td>Bibliografía limitada.</td>
<td>Sin soporte científico.</td>
</tr>
<tr class="odd">
<td>Comunicación oral</td>
<td>Expone con claridad, precisión y responde adecuadamente preguntas.</td>
<td>Comunicación adecuada.</td>
<td>Presenta dificultades.</td>
<td>Comunicación deficiente.</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>5. Rúbrica para desempeño durante la rotación (10%)</th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Criterio</td>
<td>Excelente (5)</td>
<td>Bueno (4)</td>
<td>Aceptable (3)</td>
<td>Insuficiente (1-2)</td>
</tr>
<tr class="even">
<td>Profesionalismo</td>
<td>Demuestra ética, responsabilidad, puntualidad y respeto de manera permanente.</td>
<td>Cumple la mayoría de los criterios.</td>
<td>Presenta algunas dificultades.</td>
<td>Incumple normas básicas.</td>
</tr>
<tr class="odd">
<td>Compromiso con el aprendizaje</td>
<td>Muestra iniciativa, autonomía y preparación previa.</td>
<td>Generalmente preparado.</td>
<td>Preparación irregular.</td>
<td>Escaso interés por aprender.</td>
</tr>
<tr class="even">
<td>Desempeño práctico</td>
<td>Realiza correctamente las actividades asignadas bajo supervisión.</td>
<td>Desempeño adecuado.</td>
<td>Requiere apoyo frecuente.</td>
<td>No alcanza las competencias esperadas.</td>
</tr>
<tr class="odd">
<td>Comunicación</td>
<td>Mantiene comunicación efectiva con docentes y compañeros.</td>
<td>Comunicación adecuada.</td>
<td>Presenta algunas dificultades.</td>
<td>Comunicación deficiente.</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th>Bibliografía de Referencia Recomendada para la Rotación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Kumar V, Abbas AK, Aster JC. Robbins &amp; Cotran Patología Estructural y Funcional. 10ª ed.&nbsp;Elsevier; 2021. 2. Shapiro, H. M. (2003). Practical Flow Cytometry (4th ed.). Wiley-Liss. doi.org 3. Leach, M., Drummond, M., &amp; Doig, A. (2013). Practical Flow Cytometry in Haematology Diagnosis: 100 Worked Examples. Wiley-Blackwell. doi.org</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>ELABORA:</p>
<p>Victoria Eugenia Niño</p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th>FORMATO DE PRACTICAS FORMATIVAS PARA LA ROTACIÓN DE PATOLOGÍA DEL TRACTO GASTROINTESTINAL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
</tr>
<tr class="even">
<td></td>
</tr>
<tr class="odd">
<td></td>
</tr>
<tr class="even">
<td>Fecha de Inicio: 26 de agosto de 2026</td>
</tr>
<tr class="odd">
<td>Fecha de terminación: 18 de noviembre de 2026</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Objetivo de la Rotación</th>
<th>Competencias</th>
<th>Actividades y Procedimientos por Día</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OBJETIVO GENERAL: Brindar al estudiante de medicina de pregrado los fundamentos morfológicos, clínicos y moleculares de las principales patologías del tracto gastrointestinal (estómago, colon y recto), promoviendo la integración de los hallazgos histopatológicos con el diagnóstico, pronóstico y abordaje del paciente. Objetivos específicos: 1. Reconocer y diferenciar las características histopatológicas de las gastritis, aplicando los sistemas de estadificación de riesgo (OLGA/OLGIM), y correlacionarlas con el desarrollo y clasificación del cáncer gástrico. 2. Clasificar los pólipos intestinales, la enfermedad inflamatoria intestinal y el cáncer colorrectal, integrando sus manifestaciones clínicas, paraclínicas y vías moleculares de carcinogénesis.</td>
<td>Cognitivas (Saber): • Diferencia los conceptos de gastropatía y gastritis, y sus factores de riesgo. • Explica las clasificaciones de OLGA/OLGIM y los tipos histológicos y moleculares del cáncer gástrico y colorrectal. • Clasifica la EII y los distintos tipos de pólipos colorrectales. Procedimentales (Saber hacer): • Identifica hallazgos microscópicos clave de inflamación, displasia y neoplasia en patología gastrointestinal. • Correlaciona signos, síntomas y estudios paraclínicos con el diagnóstico histopatológico. Actitudinales (Ser): • Demuestra pensamiento crítico en la correlación clínico-patológica. • Trabaja colaborativamente en la resolución de casos clínicos.</td>
<td>· Sesión 1 - Patología Gástrica: o Clase interactiva enfocada en: gastropatía, gastritis y cáncer gástrico. o Análisis guiado de imágenes histológicas representativas con el docente.</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>· Sesión 2 - Patología del Colon: o Clase interactiva enfocada en: enfermedad inflamatoria intestinal, pólipos del colon y cáncer de colon. o Análisis guiado de imágenes histológicas representativas con el docente.</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>· Sesión 3 – Sesión de preguntas y respuestas sobre cada uno de los temas tratados o Presentación de casos clínicos reales por grupos de 2-3 estudiantes (12-15 min + 5-8 min de preguntas). o Estructura del caso: presentación clínica → fisiopatología → morfología → diagnóstico. o Discusión grupal moderada por el docente. o Retroalimentación formativa individual y grupal inmediata.</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;">Delegación progresiva de actividades</td>
</tr>
<tr class="even">
<td style="text-align: center;">Actividades y/o procedimientos</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1. Participación activa en la revisión de hallazgos histopatológicos</td>
</tr>
<tr class="even">
<td style="text-align: center;">2. Cálculo teórico de OLGA y OLGIM en descripciones patológicas</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3. Diferenciación morfológica de EII (Crohn vs CU) en imágenes</td>
</tr>
<tr class="even">
<td style="text-align: center;">4. Integración de clínica, paraclínicos y patología en casos de cáncer de colon</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5. Clasificación molecular del cáncer gástrico y colorrectal en discusión</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: center;">Estrategias pedagógicas utilizadas durante la rotación</td>
</tr>
<tr class="even">
<td style="text-align: center;">Aplica</td>
</tr>
<tr class="odd">
<td style="text-align: center;">X</td>
</tr>
<tr class="even">
<td style="text-align: center;">X</td>
</tr>
<tr class="odd">
<td style="text-align: center;">X</td>
</tr>
<tr class="even">
<td style="text-align: center;">X</td>
</tr>
<tr class="odd">
<td style="text-align: center;">X</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;">Cronograma de la rotación en patología del tracto gastrointestinal</td>
</tr>
<tr class="even">
<td style="text-align: center;">Día</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th>Instrucciones para la preparación de los casos clínicos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Estructura obligatoria del caso clínico 1. Presentación del paciente: edad, sexo, antecedentes relevantes, motivo de consulta. 2. Hallazgos clínicos y paraclínicos relevantes (laboratorios, imágenes diagnósticas). 3. Reconocimiento de los factores de riesgo de cada entidad patológica 4. Explicación fisiopatológica de cada una de las patologías revisadas 5. Descripción macroscópica e histopatológica (morfología convencional con H&amp;E, estudios con inmunohistoquímica y biología molecular). 6. Correlación clínico patológica</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;">Distribución de la Evaluación de la Rotación</td>
</tr>
<tr class="even">
<td style="text-align: center;">Componente evaluado</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Participación y dominio teórico - Evaluado mediante Aula Invertida.</td>
</tr>
<tr class="even">
<td style="text-align: center;">Análisis y correlación de casos clínicos - Evaluado durante la práctica.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Trabajo colaborativo y profesionalismo - Actitud durante las sesiones.</td>
</tr>
<tr class="even">
<td style="text-align: center;">TOTAL</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: center;">Rúbrica 1: Dominio teórico y aula invertida (40%)</td>
</tr>
<tr class="even">
<td style="text-align: center;">Criterio</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Preparación previa (aula invertida)</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: center;">Rúbrica 2: Análisis y correlación de casos clínicos (40%)</td>
</tr>
<tr class="even">
<td style="text-align: center;">Criterio</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Análisis y Correlación de Casos Clínicos</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: center;">Rúbrica 3: Profesionalismo y trabajo colaborativo (20%)</td>
</tr>
<tr class="even">
<td style="text-align: center;">Criterio</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Participación activa en todos los casos</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th>Bibliografía de Referencia Recomendada para la Rotación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Kumar V, Abbas AK, Aster JC. Robbins &amp; Cotran Patología Estructural y Funcional. 10ª ed.&nbsp;Barcelona: Elsevier; 2021. (Libro base de la asignatura - Capítulos de Patología del Tubo Digestivo). WHO Classification of Tumours Editorial Board. Digestive System Tumours. WHO Classification of Tumours. 5th ed.&nbsp;Lyon (France): International Agency for Research on Cancer; 2019. Rugge M, Genta RM, Di Mario F, et al.&nbsp;Gastric Cancer as a Preventable Disease: Clinical Implications of Helicobacter pylori Infection and OLGA/OLGIM Staging. Gut. 2018;67(1):15-20. The Cancer Genome Atlas (TCGA) Research Network. Comprehensive molecular characterization of gastric adenocarcinoma. Nature. 2014;513(7517):202-209. Guinney J, Dienstmann R, Wang X, et al.&nbsp;The consensus molecular subtypes of colorectal cancer. Nat Med. 2015;21(11):1350-1356.</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./0297071-medicina-interna-i.html" class="pagination-link" aria-label="Medicina Interna I">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Medicina Interna I</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./0297073-psicopatologia.html" class="pagination-link" aria-label="Psicopatología">
        <span class="nav-page-text"><span class="chapter-title">Psicopatología</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>