<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Pediatría – Microcurrículos — Programa de Medicina</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./0297102-administracion-en-salud.html" rel="next">
<link href="./0297092-seminario-de-desastres.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-27c261d06b905028a18691de25d09dde.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./0297101-pediatria.html">Semestre 10</a></li><li class="breadcrumb-item"><a href="./0297101-pediatria.html"><span class="chapter-title">Pediatría</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Microcurrículos — Programa de Medicina</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Presentación</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 1</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0204011-biologia-celular-molecular-y-bioquimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Biología celular molecular y Bioquímica</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297012-fundamentos-de-investigacion-i.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fundamentos de Investigación I</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297015-etica-medica-i.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Ética Médica I</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297017-introduccion-a-la-medicina.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introducción a la Medicina</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 2</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297020-fundamentos-de-investigacion-ii.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fundamentos de Investigación II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297021-morfologia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Morfología</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 3</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297032-psicobiologia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Psicobiología</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297034-fisiologia-general-y-de-sistemas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fisiología general y de sistemas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297035-fundamentos-de-investigacion-iii.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fundamentos de Investigación III</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297036-genetica-basica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Genética básica</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 4</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297041-microbiologia-y-parasitologia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Microbiología y Parasitología</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297042-patologia-general.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Patología general</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297045-fundamentos-de-investigacion-iv.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fundamentos de Investigación IV</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 5</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297051-farmacologia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Farmacología</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297052-semiologia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Semiología</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297053-psicologia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Psicología</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 6</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0201063-salud-familiar.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Salud Familiar</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297061-cirugia-general.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Cirugía general</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297063-seminario-historia-de-la-medicina.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Seminario Historia de la Medicina</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 7</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0201074-seminario-de-geriatria-y-gerontologia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Seminario de Geriatría y Gerontología</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297071-medicina-interna-i.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Medicina Interna I</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297072-patologia-especial.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Patología especial</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297073-psicopatologia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Psicopatología</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 8</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297081-medicina-interna-ii.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Medicina Interna II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297083-psiquiatria.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Psiquiatría</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297084-etica-medica-ii.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Ética Médica II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297096-seminario-de-tanatologia-y-medicina-paliativa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Seminario de Tanatología y Medicina Paliativa</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 9</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297091-cirugia-de-especialidades.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Cirugía de Especialidades</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297092-seminario-de-desastres.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Seminario de Desastres</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 10</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297101-pediatria.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Pediatría</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297102-administracion-en-salud.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Administración en Salud</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true">
 <span class="menu-text">Semestre 11</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297082-medicina-legal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Medicina Legal</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297112-ginecologia-y-obstetricia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Ginecología y Obstetricia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0297113-medicina-preventiva-y-salud-publica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Medicina Preventiva y Salud Pública</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#identificación" id="toc-identificación" class="nav-link active" data-scroll-target="#identificación">1 Identificación</a>
  <ul class="collapse">
  <li><a href="#datos-de-identificación" id="toc-datos-de-identificación" class="nav-link" data-scroll-target="#datos-de-identificación">1.1 Datos de identificación</a></li>
  <li><a href="#prerrequisitos" id="toc-prerrequisitos" class="nav-link" data-scroll-target="#prerrequisitos">1.2 Prerrequisitos</a></li>
  </ul></li>
  <li><a href="#profesores" id="toc-profesores" class="nav-link" data-scroll-target="#profesores">2 Profesores</a>
  <ul class="collapse">
  <li><a href="#coordinadora" id="toc-coordinadora" class="nav-link" data-scroll-target="#coordinadora">2.1 Coordinadora</a></li>
  <li><a href="#cuerpo-docente" id="toc-cuerpo-docente" class="nav-link" data-scroll-target="#cuerpo-docente">2.2 Cuerpo docente</a></li>
  </ul></li>
  <li><a href="#presentación" id="toc-presentación" class="nav-link" data-scroll-target="#presentación">3 Presentación</a></li>
  <li><a href="#competencias" id="toc-competencias" class="nav-link" data-scroll-target="#competencias">4 Competencias</a>
  <ul class="collapse">
  <li><a href="#matriz-de-competencias" id="toc-matriz-de-competencias" class="nav-link" data-scroll-target="#matriz-de-competencias">4.1 Matriz de competencias</a></li>
  </ul></li>
  <li><a href="#metodología-y-contenidos" id="toc-metodología-y-contenidos" class="nav-link" data-scroll-target="#metodología-y-contenidos">5 Metodología y Contenidos</a>
  <ul class="collapse">
  <li><a href="#temas-y-estrategias-pedagógicas" id="toc-temas-y-estrategias-pedagógicas" class="nav-link" data-scroll-target="#temas-y-estrategias-pedagógicas">5.1 Temas y estrategias pedagógicas</a></li>
  <li><a href="#el-detalle-de-temas-horas-metodología-y-bibliografía-de-cada-rotación-puede-consultarse-en-los-anexos-c-a-h." id="toc-el-detalle-de-temas-horas-metodología-y-bibliografía-de-cada-rotación-puede-consultarse-en-los-anexos-c-a-h." class="nav-link" data-scroll-target="#el-detalle-de-temas-horas-metodología-y-bibliografía-de-cada-rotación-puede-consultarse-en-los-anexos-c-a-h.">El detalle de temas, horas, metodología y bibliografía de cada rotación puede consultarse en los Anexos C a H.</a></li>
  </ul></li>
  <li><a href="#sistema-de-evaluación" id="toc-sistema-de-evaluación" class="nav-link" data-scroll-target="#sistema-de-evaluación">6 Sistema de Evaluación</a>
  <ul class="collapse">
  <li><a href="#proceso-de-evaluación" id="toc-proceso-de-evaluación" class="nav-link" data-scroll-target="#proceso-de-evaluación">6.1 Proceso de evaluación</a></li>
  <li><a href="#rúbrica-de-evaluación-de-cada-rotación" id="toc-rúbrica-de-evaluación-de-cada-rotación" class="nav-link" data-scroll-target="#rúbrica-de-evaluación-de-cada-rotación">6.2 Rúbrica de evaluación de cada rotación:</a></li>
  <li><a href="#componentes-de-evaluación-de-la-asignatura" id="toc-componentes-de-evaluación-de-la-asignatura" class="nav-link" data-scroll-target="#componentes-de-evaluación-de-la-asignatura">6.3 Componentes de evaluación de la asignatura:</a></li>
  </ul></li>
  <li><a href="#cronograma" id="toc-cronograma" class="nav-link" data-scroll-target="#cronograma">7 Cronograma</a>
  <ul class="collapse">
  <li><a href="#distribución-semanal-de-temas" id="toc-distribución-semanal-de-temas" class="nav-link" data-scroll-target="#distribución-semanal-de-temas">7.1 Distribución semanal de temas</a></li>
  <li><a href="#distribución-semanal-de-rotaciones-prácticas-o-laboratorios" id="toc-distribución-semanal-de-rotaciones-prácticas-o-laboratorios" class="nav-link" data-scroll-target="#distribución-semanal-de-rotaciones-prácticas-o-laboratorios">7.2 Distribución semanal de rotaciones, prácticas o laboratorios</a></li>
  </ul></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias">8 Referencias</a></li>
  <li><a href="#anexos" id="toc-anexos" class="nav-link" data-scroll-target="#anexos">9 Anexos</a>
  <ul class="collapse">
  <li><a href="#anexo-a-competencias-y-criterios-de-desempeño" id="toc-anexo-a-competencias-y-criterios-de-desempeño" class="nav-link" data-scroll-target="#anexo-a-competencias-y-criterios-de-desempeño">Anexo A — Competencias y criterios de desempeño</a></li>
  <li><a href="#anexo-b-contenidos-de-la-semana-de-inducción" id="toc-anexo-b-contenidos-de-la-semana-de-inducción" class="nav-link" data-scroll-target="#anexo-b-contenidos-de-la-semana-de-inducción">Anexo B — Contenidos de la semana de inducción</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1"></a></li>
  <li><a href="#anexo-c-programación-semana-de-inducción." id="toc-anexo-c-programación-semana-de-inducción." class="nav-link" data-scroll-target="#anexo-c-programación-semana-de-inducción.">Anexo C — Programación semana de inducción.</a></li>
  <li><a href="#anexo-d-rotación-de-pediatría-social" id="toc-anexo-d-rotación-de-pediatría-social" class="nav-link" data-scroll-target="#anexo-d-rotación-de-pediatría-social">Anexo D — Rotación de Pediatría Social</a></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2"></a></li>
  <li><a href="#section-45" id="toc-section-45" class="nav-link" data-scroll-target="#section-45"></a></li>
  <li><a href="#cuadro-semanal-de-prácticas-de-pediatría-social" id="toc-cuadro-semanal-de-prácticas-de-pediatría-social" class="nav-link" data-scroll-target="#cuadro-semanal-de-prácticas-de-pediatría-social">CUADRO SEMANAL DE PRÁCTICAS DE PEDIATRÍA SOCIAL</a></li>
  <li><a href="#anexo-e-rotación-de-medicina-interna" id="toc-anexo-e-rotación-de-medicina-interna" class="nav-link" data-scroll-target="#anexo-e-rotación-de-medicina-interna">Anexo E — Rotación de Medicina Interna</a></li>
  <li><a href="#section-53" id="toc-section-53" class="nav-link" data-scroll-target="#section-53"></a></li>
  <li><a href="#section-131" id="toc-section-131" class="nav-link" data-scroll-target="#section-131"></a></li>
  <li><a href="#cuadro-semanal-de-prácticas-de-medicina-interna" id="toc-cuadro-semanal-de-prácticas-de-medicina-interna" class="nav-link" data-scroll-target="#cuadro-semanal-de-prácticas-de-medicina-interna">CUADRO SEMANAL DE PRÁCTICAS DE MEDICINA INTERNA</a></li>
  <li><a href="#anexo-f-rotación-de-infecciosas" id="toc-anexo-f-rotación-de-infecciosas" class="nav-link" data-scroll-target="#anexo-f-rotación-de-infecciosas">Anexo F — Rotación de Infecciosas</a></li>
  <li><a href="#section-132" id="toc-section-132" class="nav-link" data-scroll-target="#section-132"></a></li>
  <li><a href="#section-169" id="toc-section-169" class="nav-link" data-scroll-target="#section-169"></a></li>
  <li><a href="#cuadro-semanal-de-prácticas-de-infecciosas" id="toc-cuadro-semanal-de-prácticas-de-infecciosas" class="nav-link" data-scroll-target="#cuadro-semanal-de-prácticas-de-infecciosas">CUADRO SEMANAL DE PRÁCTICAS DE INFECCIOSAS</a></li>
  <li><a href="#anexo-g-rotación-de-urgencias" id="toc-anexo-g-rotación-de-urgencias" class="nav-link" data-scroll-target="#anexo-g-rotación-de-urgencias">Anexo G — Rotación de Urgencias</a></li>
  <li><a href="#section-170" id="toc-section-170" class="nav-link" data-scroll-target="#section-170"></a></li>
  <li><a href="#section-199" id="toc-section-199" class="nav-link" data-scroll-target="#section-199"></a></li>
  <li><a href="#cuadro-semanal-de-prácticas-de-urgencias" id="toc-cuadro-semanal-de-prácticas-de-urgencias" class="nav-link" data-scroll-target="#cuadro-semanal-de-prácticas-de-urgencias">CUADRO SEMANAL DE PRÁCTICAS DE URGENCIAS</a></li>
  <li><a href="#anexo-h-rotación-de-consulta-externa" id="toc-anexo-h-rotación-de-consulta-externa" class="nav-link" data-scroll-target="#anexo-h-rotación-de-consulta-externa">Anexo H — Rotación de Consulta Externa</a></li>
  <li><a href="#section-200" id="toc-section-200" class="nav-link" data-scroll-target="#section-200"></a></li>
  <li><a href="#cuadro-semanal-de-prácticas-de-consulta-externa" id="toc-cuadro-semanal-de-prácticas-de-consulta-externa" class="nav-link" data-scroll-target="#cuadro-semanal-de-prácticas-de-consulta-externa">CUADRO SEMANAL DE PRÁCTICAS DE CONSULTA EXTERNA</a></li>
  <li><a href="#anexo-i-rotación-de-neonatología" id="toc-anexo-i-rotación-de-neonatología" class="nav-link" data-scroll-target="#anexo-i-rotación-de-neonatología">Anexo I — Rotación de Neonatología</a></li>
  <li><a href="#section-201" id="toc-section-201" class="nav-link" data-scroll-target="#section-201"></a></li>
  <li><a href="#section-203" id="toc-section-203" class="nav-link" data-scroll-target="#section-203"></a></li>
  <li><a href="#section-204" id="toc-section-204" class="nav-link" data-scroll-target="#section-204"></a></li>
  <li><a href="#cuadro-semanal-de-prácticas-de-neonatos" id="toc-cuadro-semanal-de-prácticas-de-neonatos" class="nav-link" data-scroll-target="#cuadro-semanal-de-prácticas-de-neonatos">CUADRO SEMANAL DE PRÁCTICAS DE NEONATOS</a></li>
  <li><a href="#section-205" id="toc-section-205" class="nav-link" data-scroll-target="#section-205"></a></li>
  <li><a href="#section-227" id="toc-section-227" class="nav-link" data-scroll-target="#section-227"></a></li>
  <li><a href="#anexo-j-programación-taller-de-estrategia-aiepi" id="toc-anexo-j-programación-taller-de-estrategia-aiepi" class="nav-link" data-scroll-target="#anexo-j-programación-taller-de-estrategia-aiepi">Anexo J — Programación Taller de estrategia AIEPI</a></li>
  <li><a href="#anexo-k-cronograma-de-rotaciones-exámenes-parciales-final-y-casos-clínicos" id="toc-anexo-k-cronograma-de-rotaciones-exámenes-parciales-final-y-casos-clínicos" class="nav-link" data-scroll-target="#anexo-k-cronograma-de-rotaciones-exámenes-parciales-final-y-casos-clínicos">Anexo K — Cronograma de rotaciones, exámenes parciales, final y casos clínicos</a></li>
  <li><a href="#anexo-l-formatos-de-evaluación-cualitativa" id="toc-anexo-l-formatos-de-evaluación-cualitativa" class="nav-link" data-scroll-target="#anexo-l-formatos-de-evaluación-cualitativa">Anexo L — Formatos de evaluación cualitativa</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./0297101-pediatria.html">Semestre 10</a></li><li class="breadcrumb-item"><a href="./0297101-pediatria.html"><span class="chapter-title">Pediatría</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Pediatría</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="identificación" class="level2">
<h2 class="anchored" data-anchor-id="identificación">1 Identificación</h2>
<section id="datos-de-identificación" class="level3">
<h3 class="anchored" data-anchor-id="datos-de-identificación">1.1 Datos de identificación</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Campo</th>
<th>Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nombre</td>
<td>Pediatría</td>
</tr>
<tr class="even">
<td>Código</td>
<td>0297101</td>
</tr>
<tr class="odd">
<td>Semestre</td>
<td>10</td>
</tr>
<tr class="even">
<td>Créditos</td>
<td>16</td>
</tr>
<tr class="odd">
<td>Dimensión curricular</td>
<td>Científico-Tecnológica</td>
</tr>
<tr class="even">
<td>Área de formación</td>
<td>Clínico</td>
</tr>
<tr class="odd">
<td>Horas presenciales semanales</td>
<td>28</td>
</tr>
<tr class="even">
<td>Horas teóricas semanales</td>
<td>17</td>
</tr>
<tr class="odd">
<td>Horas prácticas semanales</td>
<td>11</td>
</tr>
<tr class="even">
<td>Horas de trabajo independiente semanal</td>
<td>9</td>
</tr>
<tr class="odd">
<td>Horas de trabajo presencial semestrales</td>
<td>481</td>
</tr>
<tr class="even">
<td>Total de horas de trabajo independiente semestrales</td>
<td>286</td>
</tr>
<tr class="odd">
<td>Horas teóricas por semestre</td>
<td>161</td>
</tr>
<tr class="even">
<td>Horas prácticas por semestre</td>
<td>320</td>
</tr>
<tr class="odd">
<td>Habilitable</td>
<td>No</td>
</tr>
<tr class="even">
<td>Prácticas de laboratorio</td>
<td>Sí</td>
</tr>
<tr class="odd">
<td>Prácticas clínicas</td>
<td>Sí</td>
</tr>
<tr class="even">
<td>Prácticas sociales</td>
<td>Sí</td>
</tr>
</tbody>
</table>
</section>
<section id="prerrequisitos" class="level3">
<h3 class="anchored" data-anchor-id="prerrequisitos">1.2 Prerrequisitos</h3>
<ol type="1">
<li><p>0297091 — Cirugía de Especialidades</p></li>
<li><p>0297083 — Psiquiatría</p></li>
</ol>
</section>
</section>
<section id="profesores" class="level2">
<h2 class="anchored" data-anchor-id="profesores">2 Profesores</h2>
<section id="coordinadora" class="level3">
<h3 class="anchored" data-anchor-id="coordinadora">2.1 Coordinadora</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 68%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Campo</th>
<th style="text-align: left;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Nombre</td>
<td style="text-align: left;">Claudia Patricia Guzmán López</td>
</tr>
<tr class="even">
<td style="text-align: left;">Email</td>
<td style="text-align: left;">cpguzman@unicauca.edu.co</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Perfil profesional</td>
<td style="text-align: left;">Especialista en Psiquiatría, subespecialista en Psiquiatría infantil y del adolescente. Docente de la rotación de Pediatría Social.</td>
</tr>
</tbody>
</table>
</section>
<section id="cuerpo-docente" class="level3">
<h3 class="anchored" data-anchor-id="cuerpo-docente">2.2 Cuerpo docente</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 27%">
<col style="width: 46%">
</colgroup>
<thead>
<tr class="header">
<th>Nombre</th>
<th>Email</th>
<th>Perfil profesional</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Álvaro Iván Narváez Gómez</td>
<td>angomez@unicauca.edu.co</td>
<td>Especialista en Pediatría. Jefe del Departamento de Pediatría. Coordinador de la rotación de Pediatría Social y del taller de estrategia AIEPI.</td>
</tr>
<tr class="even">
<td>Claudia Guzmán</td>
<td>cpguzman@unicauca.edu.co</td>
<td>Especialista en Psiquiatría, subespecialista en Psiquiatría infantil y del adolescente. Docente de la rotación de Pediatría Social. Coordinadora de la asignatura de Pediatría del programa de Medicina.</td>
</tr>
<tr class="odd">
<td>Ana María Velasco Restrepo</td>
<td>amariarestrepo@unicauca.edu.co</td>
<td>Especialista en Pediatría, Subespecialista en Neonatología. Coordinadora de la rotación de Neonatología.</td>
</tr>
<tr class="even">
<td>Diana Marcela Muñoz</td>
<td>dianammunoz@unicauca.edu.co</td>
<td>Especialista en Pediatría. Docente de la rotación de Infectología</td>
</tr>
<tr class="odd">
<td>Martha Isabel Caicedo Rodríguez</td>
<td>micaicedo@unicauca.edu.co</td>
<td>Especialista en Pediatría. Coordinadora de la rotación de Consulta Externa.</td>
</tr>
<tr class="even">
<td>María Eugenia Miño Arango</td>
<td>memino@unicauca.edu.co</td>
<td>Especialista en Neuropediatría. Especialista en Docencia Universitaria. Docente de la rotación de Consulta Externa.</td>
</tr>
<tr class="odd">
<td>Gloria Elizabeth Martínez Orozco</td>
<td>gloriaemartinez@unicauca.edu.co</td>
<td>Especialista en Pediatría, Subespecialista en Neonatología. Docente de la rotación de Neonatología.</td>
</tr>
<tr class="even">
<td>Alex Jair Ortiz Bolaños</td>
<td>alexortiz@unicauca.edu.co</td>
<td>Especialista en Pediatría, Subespecialista en Neonatología. Docente de la rotación de Neonatología.</td>
</tr>
<tr class="odd">
<td>Alicia Ortega</td>
<td>aliortega@unicauca.edu.co</td>
<td>Especialista en Pediatría. Docente de la rotación de Pediatría Social.</td>
</tr>
<tr class="even">
<td>Dolly Vidal Castro</td>
<td>dollyvidal@unicauca.edu.co</td>
<td>Especialista en Pediatría. Subespecialista en Neumología Pediátrica. Especialista en Educación y Pedagogía. Docente de la rotación de Consulta Externa.</td>
</tr>
<tr class="odd">
<td>Olga Lucía Cújar</td>
<td>olgacujar@unicauca.edu.co</td>
<td>Especialista en Pediatría. Especialista en Educación y Pedagogía. Docente de la rotación de Medicina Interna.</td>
</tr>
<tr class="even">
<td>Jennifer Tatiana Henao</td>
<td>jthenao@unicauca.edu.co</td>
<td>Especialista en Pediatría. Especialista en Docencia universitaria. Docente de la rotación de Urgencias.</td>
</tr>
<tr class="odd">
<td>Janeth Lorena Benavides</td>
<td>benavides_lorenita@unicauca.edu.co</td>
<td>Especialista en Pediatría. Especialista en Educación y Pedagogía. Docente de la rotación de Medicina Interna</td>
</tr>
<tr class="even">
<td>Andrea Salas</td>
<td>asalas@unicauca.edu.co</td>
<td>Especialista en Pediatría. Especialista en Educación y Pedagogía. Docente de la rotación de Urgencias.</td>
</tr>
<tr class="odd">
<td>Camilo Garcés</td>
<td>cgarces@unicauca.edu.co</td>
<td>Especialista en Pediatría. Magíster en educación universitaria. Coordinador de la rotación de Urgencias</td>
</tr>
<tr class="even">
<td>Olga Lucía Prado</td>
<td>oprado@unicauca.edu.co</td>
<td>Especialista en Pediatría, Subespecialista en Nefrología Pediátrica. Magíster en Educación Universitaria. Coordinadora de la rotación de Medicina Interna.</td>
</tr>
<tr class="odd">
<td>Eliana Zemanate</td>
<td>ezemanate@unicauca.edu.co</td>
<td>Especialista en Pediatría, Subespecialista en Cuidado Intensivo Pediátrico. Especialista en Educación y Pedagogía. Docente de la rotación de Medicina Interna</td>
</tr>
<tr class="even">
<td>Yessica Bravo</td>
<td>adrianab@unicauca.edu.co</td>
<td>Especialista en Pediatría, Subespecialista en Cuidado Intensivo Pediátrico. Docente de la rotación de Infectología</td>
</tr>
<tr class="odd">
<td>Manuel Santiago Ordóñez</td>
<td>msordonez@unicauca.edu.co</td>
<td>Especialista en Pediatría, Subespecialista en Infectología Pediátrica. Coordinador de la rotación de Infectología.</td>
</tr>
<tr class="even">
<td>María Alejandra Palma</td>
<td>mariaalejandrapalma@gmail.com</td>
<td>Especialista en Pediatría, Magíster en Genética. Docente de la rotación de Neonatología</td>
</tr>
<tr class="odd">
<td>Ginna Paola Cabra</td>
<td>ginnapcabrab@unicauca.edu.co</td>
<td>Especialista en Pediatría, Magíster en Epidemiología Clínica. Directora del Grupo de Investigación de lactancia materna y alimentación complementaria. Docente de la rotación de Infectología</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="presentación" class="level2">
<h2 class="anchored" data-anchor-id="presentación">3 Presentación</h2>
<section id="presentación-de-la-asignatura" class="level4">
<h4 class="anchored" data-anchor-id="presentación-de-la-asignatura">Presentación de la Asignatura</h4>
<p>La Pediatría es la rama de la medicina dedicada a la atención de los procesos de salud y enfermedad de los niños, desde el nacimiento hasta el final de la adolescencia (18 años). La asignatura hace parte del Departamento de Pediatría del Programa de Medicina de la Facultad de Ciencias de la Salud de la Universidad del Cauca, cuya misión es la formación integral de profesionales comprometidos con la solución de los problemas de salud de la niñez colombiana, mediante la docencia, la investigación y la proyección social, con la niñez como sujeto y objeto de su quehacer.</p>
<p>La asignatura se cursa en décimo semestre y es eminentemente práctica y presencial: el estudiante rota por seis áreas —Pediatría Social, Neonatología, Infecciosas, Medicina Interna, Urgencias y Consulta Externa— en escenarios clínicos reales, precedidas de una semana de inducción en temas académicos de Pediatría básica y acompañadas de un curso transversal de la estrategia AIEPI (Atención Integrada a las Enfermedades Prevalentes de la Infancia). En cada rotación, en grupos pequeños con tutor, el estudiante elabora historias clínicas, participa en la toma de decisiones y desarrolla las habilidades semiológicas y clínicas propias de la atención del niño.</p>
<p>La proyección social es un eje de la asignatura, con espacios como el programa radial “Crianza Feliz” —emitido sin interrupción durante 25 años en la emisora de la Universidad—, la Red Interinstitucional y Comunitaria de Promoción del Buen Trato (RICO Buentrato) y la Clínica de Promoción del Buentrato del Hospital Universitario San José.</p>
<p>El Departamento cuenta además con el Grupo de Investigación en Lactancia Materna y Alimentación Complementaria y con la adhesión de la Facultad al Centro Cochrane Iberoamericano.</p>
</section>
<section id="objetivo-general" class="level4">
<h4 class="anchored" data-anchor-id="objetivo-general">Objetivo General</h4>
<p>Contribuir a la formación y capacitación integral del futuro profesional, articulando la formación técnica y científica con la social, humanística, ética y pedagógica, en el área de la Pediatría.</p>
</section>
<section id="objetivos-específicos" class="level4">
<h4 class="anchored" data-anchor-id="objetivos-específicos">Objetivos Específicos</h4>
<ul>
<li><p>Relacionar teoría, práctica e investigación formativa a partir del concepto salud-enfermedad en el país y la región, aprovechando los recursos de comunicación y tecnología para el aprendizaje, la autoformación y la retribución del conocimiento a la sociedad.</p></li>
<li><p>Contribuir, desde lo social, al abordaje de la problemática de la niñez, buscando alternativas de solución en la atención, la promoción, la prevención y la rehabilitación del niño, la familia y su entorno.</p></li>
<li><p>Reconocer que la Pediatría atiende los procesos de salud y enfermedad de los niños desde el nacimiento hasta el final de la adolescencia.</p></li>
<li><p>Adquirir las herramientas de la estrategia AIEPI, en las modalidades clínica y comunitaria, para aplicarlas en la práctica pediátrica.</p></li>
</ul>
</section>
<section id="justificación-de-la-asignatura" class="level4">
<h4 class="anchored" data-anchor-id="justificación-de-la-asignatura">Justificación de la Asignatura</h4>
<p>La situación de la niñez en Colombia y en la región determina la cantidad y la calidad de los contenidos programáticos que el Departamento utiliza para formar, en el décimo semestre, un médico comprometido con la niñez y con claridad sobre el contexto en el que transcurre el proceso vital humano. En coherencia con el Proyecto Educativo del Programa de Medicina, la asignatura se propone formar un ciudadano ejemplar, capaz de realizar un ejercicio médico integral y resolutivo en la atención de la salud del niño, y de participar en procesos de investigación, evaluación y gestión de los problemas prioritarios de la salud del niño y su familia, en el ámbito clínico, epidemiológico, cultural, médico-legal y social, acorde con el desarrollo científico y normativo vigente.</p>
</section>
<section id="descripción-general-de-la-asignatura" class="level4">
<h4 class="anchored" data-anchor-id="descripción-general-de-la-asignatura">Descripción General de la Asignatura</h4>
<p>El curso se organiza en una semana de inducción a la pediatría básica (23 horas de acompañamiento directo y 13 de trabajo independiente), seis rotaciones clínicas por áreas y un curso transversal de la estrategia AIEPI (58 horas de acompañamiento directo y 22 de trabajo independiente), el cual es certificado por la Universidad del Cauca, lo que les servirá posteriormente para la presentación al Servicio Social Obligatorio posterior a obtener su título de Médicos Generales. El cronograma para el semestre 2026-2 de AIEPI se especifica en el <strong>Anexo J.</strong></p>
<p>Las seis rotaciones son Pediatría Social, Neonatología, Infecciosas, Medicina Interna, Urgencias y Consulta Externa; cada una integra clases, revisiones de tema, prácticas clínicas en escenarios reales y turnos. En conjunto, la asignatura comprende 481 horas de trabajo presencial y 286 de trabajo independiente en el semestre. La metodología combina clases magistrales, pequeños grupos, estudio de casos, talleres, simulación y práctica clínica supervisada.</p>
<p>Para efectos de revisiones de tema realizados mediante mesas redondas, fechas de realización de parciales escritos y turnos, se han organizado las 6 rotaciones en 3 bloques:</p>
<ol type="1">
<li><p>Bloque 1: Recién nacidos y Consulta Externa</p></li>
<li><p>Bloque 2: Medicina Interna y Pediatría Social</p></li>
<li><p>Urgencias e Infecciosas</p></li>
</ol>
<p>Todos los estudiantes pasan por las 6 rotaciones.</p>
<p>Durante el semestre los estudiantes realizan adicionalmente los cursos de Reanimación básica y avanzada neonatal (NALS) y pediátrica (PALS), que son certificados por la Universidad del Cauca, sirviendo posteriormente para el internado, dado que es un requisito en las IPS donde se realiza el mismo. El detalle de contenidos, horas y bibliografía por rotación, así como los cuadros de práctica y los formatos de evaluación, se recogen en los anexos. Los días martes y viernes de 7 a 8 a.m. se realizan actividades académicas conjuntas para todo el semestre: Ateneos a cargo de docentes, residentes - Presentación de casos clínicos (con la participación de estudiantes de X semestre bajo la tutoría de un docente).</p>
<p>Al interior de cada rotación, se programa la revisión de temas a manera de mesas redondas, con contenido clínico o psicosocial, y es coordinada por los docentes del respectivo servicio.</p>
<p><strong>Turnos presenciales</strong></p>
<p>Los estudiantes realizan turnos presenciales nocturnos y festivos, según programación previa, en los servicios de Neonatos y Urgencias de Pediatría en el Hospital Universitario San José de Popayán y Hospital Susana López de Valencia que complementa su práctica clínica. Los turnos se realizan nocturnos de lunes a viernes de 7 p.m. a 12 m., fines de semana y festivos de 7 a.m. a 7 p.m. Durante cada bloque los estudiantes realizarán 1 turno semanal en días ordinarios y dos fines de semana con turnos de 12 horas.</p>
<p>Por bloques los turnos presenciales se realizan en:</p>
<ul>
<li><p>Bloque 1: Servicios de Neonatos del Hospital Universitario San José y Hospital Susana López de Valencia. Docente coordinadora de turnos Dra. Ana María Velasco.</p></li>
<li><p>Bloque 2: Servicio de urgencias Hospital Susana López de Valencia. Docente coordinadora de turnos Dra. Alicia Ortega</p></li>
<li><p>Bloque 3: Servicio de Urgencias Hospital Universitario San José. Docente coordinador de turnos Dr.&nbsp;Camilo Garcés</p></li>
</ul>
</section>
<section id="espacios-de-asesorías" class="level4">
<h4 class="anchored" data-anchor-id="espacios-de-asesorías">Espacios de Asesorías</h4>
<p>Las tutorías están a cargo de los coordinadores de cada rotación y su espacio se asigna individualmente dentro de los horarios de la asignatura, ya que se manejan grupos pequeños que permiten la enseñanza y la retroalimentación diarias. El jefe del Departamento atiende los lunes de 8:00 a 10:00 a.m. los casos especiales, y en otros horarios cuando el estudiante lo requiera.</p>
<p>Horario regular de la asignatura (II período académico 2026):</p>
<ul>
<li><p>Lunes y martes, 7:00 a.m. a 12:00 m. — Facultad de Ciencias de la Salud y escenarios de práctica clínica.</p></li>
<li><p>Miércoles a viernes, 7:00 a 11:00 a.m. y 2:00 a 4:00 p.m. — Facultad de Ciencias de la Salud y escenarios de práctica clínica.</p></li>
</ul>
</section>
</section>
<section id="competencias" class="level2">
<h2 class="anchored" data-anchor-id="competencias">4 Competencias</h2>
<section id="matriz-de-competencias" class="level3">
<h3 class="anchored" data-anchor-id="matriz-de-competencias">4.1 Matriz de competencias</h3>
<p>La información completa —cada competencia con su criterio de desempeño— puede consultarse en el Anexo A.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 70%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Grupo de competencia</th>
<th style="text-align: left;">Competencias de la asignatura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Generales (cognitivas, ciudadanas, inglés, TIC)</td>
<td style="text-align: left;">Conoce los derechos y deberes constitucionales y la organización del Estado; analiza la pertinencia y solidez de enunciados y reconoce distintas perspectivas en situaciones de conflicto; lee críticamente literatura médica en inglés; maneja instrumentos de investigación cuantitativa y cualitativa y la información bibliográfica e informática; formula preguntas clínicas estructuradas y aplica la medicina basada en la evidencia</td>
</tr>
<tr class="even">
<td style="text-align: left;">Del ser (actitudinales, afectivas, éticas/bioéticas)</td>
<td style="text-align: left;">Se relaciona con el niño, la familia, la comunidad y el equipo de salud de forma responsable, cordial y ética; valora al niño en su núcleo familiar y contexto sociocultural; desarrolla una mentalidad preventiva y comprometida con las clases más necesitadas; cumple las normas de bioseguridad, de conducta y de protección al medio ambiente</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Del saber (conocimientos, comprensión, problematización)</td>
<td style="text-align: left;">Conoce los patrones de crecimiento y los hitos del desarrollo; los aspectos de puericultura y nutrición infantil; la epidemiología, fisiopatología, clínica, diagnóstico, tratamiento y rehabilitación de las enfermedades agudas y crónicas, infecciosas y quirúrgicas más frecuentes de la infancia y la adolescencia; los determinantes sociales del proceso salud-enfermedad; y la estrategia AIEPI</td>
</tr>
<tr class="even">
<td style="text-align: left;">Del saber-hacer (aptitudes, habilidades, destrezas)</td>
<td style="text-align: left;">Realiza la historia clínica y el examen físico del niño; identifica factores de riesgo y protectores; interpreta datos clínicos y paraclínicos; presenta el paciente y participa en las decisiones médicas; ejecuta procedimientos diagnósticos y terapéuticos; conoce y maneja la estrategia AIEPI clínica y comunitaria</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Del convivir y comunicar (relacionales, interculturales, educativas)</td>
<td style="text-align: left;">Participa, organiza y planea programas comunitarios con el equipo de salud y la comunidad; optimiza los recursos institucionales y comunitarios; implementa la promoción y prevención mediante técnicas de enseñanza en el ámbito comunitario; desarrolla habilidades de comunicación y educación comunitarias, con el programa radial “Crianza Feliz” como instrumento</td>
</tr>
</tbody>
</table>
<section id="resultados-de-aprendizaje" class="level4">
<h4 class="anchored" data-anchor-id="resultados-de-aprendizaje">Resultados de aprendizaje</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td>☑</td>
<td>c.&nbsp;Interactuar con colegas, pacientes, familias, equipos de salud y colectivos, con respeto, empatía, idoneidad profesional, liderazgo y ética.</td>
</tr>
</tbody>
</table>
</section>
</section>
</section>
<section id="metodología-y-contenidos" class="level2">
<h2 class="anchored" data-anchor-id="metodología-y-contenidos">5 Metodología y Contenidos</h2>
<section id="temas-y-estrategias-pedagógicas" class="level3">
<h3 class="anchored" data-anchor-id="temas-y-estrategias-pedagógicas">5.1 Temas y estrategias pedagógicas</h3>
</section>
<section id="el-detalle-de-temas-horas-metodología-y-bibliografía-de-cada-rotación-puede-consultarse-en-los-anexos-c-a-h." class="level3">
<h3 class="anchored" data-anchor-id="el-detalle-de-temas-horas-metodología-y-bibliografía-de-cada-rotación-puede-consultarse-en-los-anexos-c-a-h.">El detalle de temas, horas, metodología y bibliografía de cada rotación puede consultarse en los Anexos C a H.</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 49%">
<col style="width: 15%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">#</th>
<th style="text-align: left;">Tema / Unidad</th>
<th style="text-align: left;">Estrategia(s)</th>
<th style="text-align: left;">Trabajo independiente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Semana de inducción: pediatría básica, historia clínica, triage, líquidos y electrolitos, medicina basada en la evidencia, desarrollo cerebral, Escala Abreviada del Desarrollo 3 (23 h directas)</td>
<td style="text-align: left;">MEP, TG, PLS, ACP</td>
<td style="text-align: left;">Lecturas y talleres. Detalle de temas en el Anexo B. Programación en el Anexo C.</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Rotación de Pediatría Social: crecimiento y desarrollo, puericultura, alimentación complementaria, maltrato infantil, salud mental (54 h directas)</td>
<td style="text-align: left;">MEP, TG, ACP</td>
<td style="text-align: left;">Revisiones de tema y turnos Detalle en el Anexo D</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Rotación de Medicina Interna: hematología, oncología, cardiología, nefrología, reumatología, endocrinología y metabolismo (61 h directas)</td>
<td style="text-align: left;">MEP, TG, ACP</td>
<td style="text-align: left;">Revisiones de tema y turnos. Detalle en el Anexo E</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Rotación de Infecciosas: tuberculosis, vacunación (PAI), infección respiratoria aguda, enfermedades febriles, meningitis (con AIEPI)</td>
<td style="text-align: left;">TG, ACP, RLC</td>
<td style="text-align: left;">Revisiones de tema y turnos. Detalle en el Anexo F</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Rotación de Urgencias: AIEPI de urgencias, equilibrio hídrico, estatus convulsivo, trauma craneoencefálico, crisis asmática, EDA, intoxicaciones, patología quirúrgica (con turnos)</td>
<td style="text-align: left;">ACP, PLS</td>
<td style="text-align: left;">Revisiones de tema y turnos. Detalle en el Anexo G</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">Rotación de Consulta Externa: crecimiento y desarrollo, AIEPI clínico, enfermedades infecciosas y por sistemas, asma, patología de piel, síndrome convulsivo (63 h directas)</td>
<td style="text-align: left;">MEP, TG, ACP</td>
<td style="text-align: left;">Revisiones de tema y turnos. Detalle en el Anexo H</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">Rotación de Neonatología: semiología neonatal, cuidado intensivo e intermedio, prematuro, dificultad respiratoria, asfixia, ictericia, sepsis (cuidado neonatal)</td>
<td style="text-align: left;">TG, PLS, ACP</td>
<td style="text-align: left;">Revisiones de tema y turnos. Detalle en el Anexo I</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">Curso transversal de estrategia AIEPI: atención integrada de casos, signos de peligro, evaluación y clasificación del niño enfermo, consejería a la madre (58 h directas)</td>
<td style="text-align: left;">MEP, TG, ACP</td>
<td style="text-align: left;">Curso, práctica. Detalle en el Anexo J</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">NALS</td>
<td style="text-align: left;">SI</td>
<td style="text-align: left;">Estudio de material</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">PALS</td>
<td style="text-align: left;">SI</td>
<td style="text-align: left;">Estudio de material</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="sistema-de-evaluación" class="level2">
<h2 class="anchored" data-anchor-id="sistema-de-evaluación">6 Sistema de Evaluación</h2>
<section id="proceso-de-evaluación" class="level3">
<h3 class="anchored" data-anchor-id="proceso-de-evaluación">6.1 Proceso de evaluación</h3>
<p>En cada rotación se realizan dos tipos de evaluación:</p>
<ul>
<li>La <strong>evaluación cuantitativa</strong> de cada rote considera las áreas cognitiva (saber), de habilidades y destrezas (saber hacer) y actitudinal (ser). La rúbrica de evaluación de las rotaciones se discrimina en la siguiente tabla.</li>
</ul>
</section>
<section id="rúbrica-de-evaluación-de-cada-rotación" class="level3">
<h3 class="anchored" data-anchor-id="rúbrica-de-evaluación-de-cada-rotación">6.2 Rúbrica de evaluación de cada rotación:</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 73%">
<col style="width: 26%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;">Aspecto Evaluado</td>
<td style="text-align: left;">Porcentaje</td>
</tr>
<tr class="even">
<td style="text-align: left;">EXAMEN ESCRITO 50%. Conocimientos teóricos</td>
<td style="text-align: left;">50%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QUICES: Evaluación de reuniones académicas, se hace sobre el tema tratado en la sesión respectiva al finalizar la misma.</td>
<td style="text-align: left;">10%</td>
</tr>
<tr class="even">
<td style="text-align: left;">GRADO DE CONOCIMIENTOS TEÓRICOS. Incluye mesas redondas y desempeño en rotaciones</td>
<td style="text-align: left;">10%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PSICOMOTORA. Capacidad para identificar problemas clínicos prioritarios, realizar diagnósticos diferenciales. Capacidad para determinar conductas terapéuticas apropiadas y pertinentes. Cada falta a un turno, suma CERO para promediar esta nota.</td>
<td style="text-align: left;">20%</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACTITUDES (10%). Capacidad para interrelacionarse con el paciente y su familia, compañeros de estudio, personal médico y paramédico. Motivación, iniciativa e interés en el proceso de aprendizaje y competencias clínicas. Cumplimiento y puntualidad en las labores asignadas</td>
<td style="text-align: left;">10%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TOTAL</td>
<td style="text-align: left;">100%</td>
</tr>
</tbody>
</table>
<ul>
<li>La <strong>evaluación formativa,</strong> de tipo cualitativo, consta de una autoevaluación del estudiante, una evaluación de la rotación realizada por él y una evaluación del estudiante realizada por los docentes. Está dirigida a un proceso de mejoramiento continuo del estudiante, de la rotación y de los docentes y no tiene valor numérico. El formato de evaluación cualitativa se recoge en el ANEXO L</li>
</ul>
<p><strong>NOTA PREVIA (70%).</strong></p>
<p>Cada rotación tiene un peso del 9% sobre la calificación final, para un total de 54%% de la nota final registrada en el sistema SIMCA. Un 16% adicional corresponde a la calificación de los casos clínicos (5%), el taller de AIEPI (5%) y los talleres NALS (3%) y PALS (3%). Todo lo anterior suma el 70% de la nota previa.</p>
<p><strong>La ausencia a un turno programado sin justificación se calificará con un 0 (cero) que será computado con la nota psicomotora de la rotación durante la cual no se hizo el turno.</strong></p>
<p><strong>EXAMEN FINAL (30%)</strong></p>
<p>El examen final vale el 30% restante de la nota definitiva. Está dividido en:</p>
<ul>
<li><p>Examen escrito de conocimientos con el 15%</p></li>
<li><p>Examen práctico en la modalidad <strong>ECOE (Examen Clínico Objetivo Estructurado)</strong> con un valor del 15%. Esta es una estrategia de evaluación auténtica que permite observar el desempeño clínico en escenarios controlados, estandarizados y comparables. En el área de Pediatría, su implementación favorece la valoración de competencias que integran comunicación con cuidadores, interrogatorio, examen físico, razonamiento clínico, toma de decisiones y tratamiento seguro. Dentro de los resultados del primer ECOE realizado en el semestre anterior con diseño multicaso, se logró evaluar dominios diferenciados del desempeño clínico pediátrico, con estandarización operativa mediante codificación de estaciones, docentes y recursos. Durante el transcurso del semestre y, previo al examen final, se hará claridad sobre esta modalidad de evaluación.</p></li>
</ul>
</section>
<section id="componentes-de-evaluación-de-la-asignatura" class="level3">
<h3 class="anchored" data-anchor-id="componentes-de-evaluación-de-la-asignatura">6.3 Componentes de evaluación de la asignatura:</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Tiempo evaluativo</th>
<th>Momento</th>
<th>Tipo de evaluación</th>
<th>%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nota Previa (70%)</td>
<td>Rotaciones (54%)</td>
<td>Tres fechas de parciales escritos, (cada uno comprendiendo 2 rotaciones). Cada rotación evaluada según el punto 6.2</td>
<td>54%</td>
</tr>
<tr class="even">
<td></td>
<td>Actividades complementarias (16%)</td>
<td>Curso de AIEPI</td>
<td>5%</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>Casos clínicos</td>
<td>5%</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>Taller NALS</td>
<td>3%</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>Taller PALS</td>
<td>3%</td>
</tr>
<tr class="even">
<td>Examen Final (30%)</td>
<td>Examen Final (30%)</td>
<td>Examen final escrito</td>
<td>15%</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>Examen práctico ECOE</td>
<td>15%</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="cronograma" class="level2">
<h2 class="anchored" data-anchor-id="cronograma">7 Cronograma</h2>
<section id="distribución-semanal-de-temas" class="level3">
<h3 class="anchored" data-anchor-id="distribución-semanal-de-temas">7.1 Distribución semanal de temas</h3>
<p>Se ofrece a continuación una sintética de la distribución semestral. El contenido detallado de cada rotación, con sus horas, está en los <strong>Anexos D a I</strong>. El cronograma de rotaciones en el semestre se recoge en el <strong>Anexo K.</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 10%">
<col style="width: 21%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Tema / Unidad</th>
<th style="text-align: left;">Semana</th>
<th style="text-align: left;">Fecha(s)</th>
<th style="text-align: left;">Observaciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Semana de inducción a la pediatría básica</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">3 al 10 de agosto de 2026</td>
<td style="text-align: left;">En el anexo C se estipula el cronograma</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rotaciones clínicas (6)</td>
<td style="text-align: left;">2–16</td>
<td style="text-align: left;">3 de agosto al 20 de noviembre de 2026</td>
<td style="text-align: left;">Cada estudiante rota por las seis áreas según la programación del Anexo K</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Taller transversal de estrategia AIEPI</td>
<td style="text-align: left;">1–17</td>
<td style="text-align: left;">21 de agosto al 23 de noviembre de 2026</td>
<td style="text-align: left;">Se desarrolla a lo largo del semestre. Anexo J.</td>
</tr>
</tbody>
</table>
</section>
<section id="distribución-semanal-de-rotaciones-prácticas-o-laboratorios" class="level3">
<h3 class="anchored" data-anchor-id="distribución-semanal-de-rotaciones-prácticas-o-laboratorios">7.2 Distribución semanal de rotaciones, prácticas o laboratorios</h3>
<p>Vista sintética de las seis rotaciones clínicas. Los cuadros de práctica semanales (horarios de lunes a viernes por rotación) se recogen en los anexos D a I. El cronograma de rotaciones por grupos de estudiantes se establece en el <strong>Anexo K.</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Rotación / Práctica / Laboratorio</th>
<th>Semana</th>
<th>Fecha(s)</th>
<th>Observaciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rotación de Pediatría Social</td>
<td>2–16</td>
<td>Anexo K</td>
<td>Consulta externa, salud mental, práctica comunitaria y clínica de promoción del buen trato. Temas y programación semanal en el Anexo D.</td>
</tr>
<tr class="even">
<td>Rotación de Medicina Interna</td>
<td>2–16</td>
<td></td>
<td>Hematología, cardiología, nefrología, endocrinología y turnos. Temas y programación semanal en el Anexo E.</td>
</tr>
<tr class="odd">
<td>Rotación de Infecciosas</td>
<td>2–16</td>
<td></td>
<td>Atención del niño infectado; AIEPI. Temas y programación semanal en el Anexo F.</td>
</tr>
<tr class="even">
<td>Rotación de Urgencias</td>
<td>2–16</td>
<td></td>
<td>Urgencias pediátricas, reanimación y turnos. Temas y programación semanal en el Anexo G.</td>
</tr>
<tr class="odd">
<td>Rotación de Consulta Externa</td>
<td>2–16</td>
<td></td>
<td>Consulta externa (HUSJ, HSLV, Nueva EPS, Minga IPSI). Temas y programación semanal en el Anexo H.</td>
</tr>
<tr class="even">
<td>Rotación de Neonatología</td>
<td>2–16</td>
<td></td>
<td>Unidad neonatal y sala de puerperio (HUSJ, HSLV, Clínica La Estancia). Temas y programación semanal en el Anexo I.</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="referencias" class="level2">
<h2 class="anchored" data-anchor-id="referencias">8 Referencias</h2>
<ol type="1">
<li><p>Fundamentos de Pediatría. Corporación para Investigaciones Biológicas (CIB), Medellín.</p></li>
<li><p>Estrategia AIEPI. Atención Integrada a las Enfermedades Prevalentes de la Infancia. OPS-OMS; 2016.</p></li>
<li><p>Plata Rueda E. El Pediatra Eficiente y Pediatría Práctica. Editorial Médica Panamericana.</p></li>
<li><p>El Niño Sano. Grupo de Puericultura de la Universidad de Antioquia. 4ª Edición. Editorial Médica Panamericana; 2016.</p></li>
<li><p>Cloherty JP, Stark AR. Manual de Neonatología. 8ª Edición; 2017.</p></li>
<li><p>Avery GB, MacDonald MG. Neonatología. Wolters Kluwer; 8ª Edición, 2022.</p></li>
<li><p>Ministerio de Salud y Protección Social de Colombia. Estrategia AIEPI, esquema PAI de vacunación, Resolución 3280 de 2018 y guías de práctica clínica pediátrica.</p></li>
<li><p>Kliegman RM, et al.&nbsp;Nelson. Tratado de Pediatría. Editorial Elsevier.</p></li>
</ol>
</section>
<section id="anexos" class="level2">
<h2 class="anchored" data-anchor-id="anexos">9 Anexos</h2>
<p>Dada la extensión del programa (seis rotaciones), las tablas de contenidos se recogen por rotación.</p>
<p>La columna de metodología de estos cuadros usa las abreviaturas del propio syllabus: ABP (Aprendizaje basado en problemas), AA (Aprendizaje autónomo), AT (Ateneo), CM (Clase magistral), EC (Estudio de caso), FO (Foro), ME (Método expositivo), MEC (Método expositivo combinado), M/P (Movilidad/Pasantías), PG (Pequeños grupos), PR (Práctica), PL (Prácticas de laboratorio), PO (Portafolio), ST (Salida a terreno), SE (Seminario), SI (Simulación), TS (Taller-Seminario), TU (Tutorías), TICS (Telemedicina) y TG (Trabajo en Grupos).</p>
<section id="anexo-a-competencias-y-criterios-de-desempeño" class="level3">
<h3 class="anchored" data-anchor-id="anexo-a-competencias-y-criterios-de-desempeño">Anexo A — Competencias y criterios de desempeño</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 46%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Categoría</th>
<th style="text-align: left;">Competencias de la asignatura</th>
<th style="text-align: left;">Criterios de desempeño</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Generales · Cognitivas, Ciudadanas, Inglés, TIC</td>
<td style="text-align: left;">Conoce los derechos y deberes que consagra la Constitución y la organización del Estado. Analiza y evalúa la pertinencia y solidez de enunciados y discursos. Reconoce y analiza diferentes perspectivas en situaciones donde interactúan distintas partes. Lee críticamente artículos de la literatura médica en inglés y analiza sus resultados. Maneja instrumentos de investigación cuantitativa y cualitativa y la información bibliográfica e informática. Identifica los problemas del paciente y construye una pregunta clínica estructurada; plantea estrategias de búsqueda de la literatura biomédica y recupera documentos válidos; desarrolla una actitud escéptica, honesta y ética para la solución de problemas y la actualización continua.</td>
<td style="text-align: left;">Conoce las características de la Constitución, el Estado social de derecho y los derechos fundamentales, sociales, colectivos y del ambiente. Valora la solidez y pertinencia de los argumentos; reconoce posiciones e intereses en un conflicto y compara perspectivas. Establece relaciones entre las dimensiones de una situación problemática y analiza los efectos de una solución. Contribuye a mejorar la salud, a utilizar racionalmente los recursos y a fortalecer la toma de decisiones en salud.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Del ser · Actitudinales, Afectivas, Éticas/bioéticas</td>
<td style="text-align: left;">Se relaciona con el niño, la familia, la comunidad, los compañeros y el equipo médico y docente dentro de un ambiente responsable, cordial y ético. Valora al niño como parte de un núcleo familiar y contexto sociocultural. Desarrolla una mentalidad preventiva, crítica y comprometida con las clases más necesitadas. Reconoce sus capacidades y limitaciones. Respeta el manual de conducta de la Universidad y de las IPS, y cumple las normas de bioseguridad y de protección al medio ambiente.</td>
<td style="text-align: left;">Actúa con responsabilidad e idoneidad ante el proceso salud-enfermedad; cumple las normas de conducta, bioseguridad y protección ambiental de las instituciones donde realiza la rotación.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Del saber · Conocimientos, Comprensión, Problematización</td>
<td style="text-align: left;">Conoce los estándares de crecimiento (curvas de la OMS adoptadas en Colombia) y los hitos del desarrollo; los aspectos de puericultura y de nutrición infantil (lactancia materna, alimentación complementaria). Obtiene los conocimientos de epidemiología, fisiopatología, clínica, diagnóstico, tratamiento y rehabilitación de las enfermedades agudas y crónicas, infecciosas, no infecciosas y quirúrgicas más frecuentes de la infancia y la adolescencia. Reconoce los determinantes sociales del proceso salud-enfermedad. Adquiere las herramientas de la estrategia AIEPI y de la medicina basada en la evidencia.</td>
<td style="text-align: left;">Diagnostica las anormalidades del crecimiento y del desarrollo y orienta su tratamiento con interdisciplinariedad. Emplea los conocimientos de crianza para la consejería a los padres. Establece el estado nutricional y orienta el tratamiento de la malnutrición. Identifica enfermedades infecciosas, no infecciosas y quirúrgicas para tratarlas o definir remisión. Clasifica las enfermedades prevalentes y el tratamiento según el nivel de atención.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Del saber-hacer · Aptitudes, Habilidades, Destrezas</td>
<td style="text-align: left;">Realiza la historia clínica con redacción adecuada del motivo de consulta y la anamnesis. Adquiere las habilidades semiológicas para un adecuado examen físico del niño. Analiza la historia clínica, identifica factores de riesgo y protectores y plantea planes preventivos, terapéuticos y de rehabilitación. Interpreta los datos clínicos y paraclínicos. Presenta el paciente al docente y participa en las decisiones médicas. Practica la técnica de procedimientos diagnósticos y terapéuticos. Conoce y maneja la estrategia AIEPI clínica y comunitaria.</td>
<td style="text-align: left;">Saluda, se presenta y muestra respeto por el paciente y su familia. Orienta la entrevista a partir del motivo de consulta; realiza el examen físico ordenado, completo y con maniobras correctas. Propone diagnósticos, plan diagnóstico y plan terapéutico; conoce la acción farmacológica, las dosis, los intervalos y los efectos colaterales de los medicamentos, y propone tratamientos no farmacológicos sustentados.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Del convivir y comunicar · Relacionales, Interculturales, Educativas</td>
<td style="text-align: left;">Participa, organiza y planea programas comunitarios con el equipo de salud y los sectores interesados. Planifica y optimiza los recursos institucionales y comunitarios en salud. Implementa la promoción y prevención mediante enfoques y técnicas de enseñanza en el ámbito comunitario. Desarrolla habilidades de comunicación y educación comunitarias, con el programa radial “Crianza Feliz” como instrumento principal. Comprende las limitaciones biomédicas, los costos en salud y el valor del trabajo interdisciplinario.</td>
<td style="text-align: left;">Conoce y respeta los derechos del paciente; interactúa de forma respetuosa y asertiva con el paciente, su familia y el equipo de salud. Educa al paciente y a su familia en cuestiones de salud y prevención de la enfermedad.</td>
</tr>
</tbody>
</table>
</section>
<section id="anexo-b-contenidos-de-la-semana-de-inducción" class="level3">
<h3 class="anchored" data-anchor-id="anexo-b-contenidos-de-la-semana-de-inducción">Anexo B — Contenidos de la semana de inducción</h3>
<p>Horas de acompañamiento directo (AD) y de trabajo independiente (TI).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 56%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Tema</th>
<th style="text-align: left;">AD (h)</th>
<th style="text-align: left;">TI (h)</th>
<th style="text-align: left;">Metodología</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Presentación del Departamento y del semestre</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">CM</td>
</tr>
<tr class="even">
<td style="text-align: left;">Situación de la niñez en Colombia</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">CM</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Historia clínica en Pediatría</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">CM</td>
</tr>
<tr class="even">
<td style="text-align: left;">Triage pediátrico</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">CM</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Líquidos y electrolitos en Pediatría: generalidades</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">CM</td>
</tr>
<tr class="even">
<td style="text-align: left;">Escala abreviada del desarrollo 3</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">CM</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lactancia materna</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">CM</td>
</tr>
<tr class="even">
<td style="text-align: left;">Desarrollo cerebral</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">CM</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Medicina basada en la evidencia; lectura crítica (taller)</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">PR</td>
</tr>
<tr class="even">
<td style="text-align: left;">Taller de reanimación neonatal básica y avanzada (NALS)</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">SI</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Taller de reanimación pediátrica básica y avanzada (PALS)</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">SI</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total horas</td>
<td style="text-align: left;">23</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</section>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"></h3>
</section>
<section id="section-1" class="level3">
<h3 class="anchored" data-anchor-id="section-1"></h3>
</section>
<section id="anexo-c-programación-semana-de-inducción." class="level3">
<h3 class="anchored" data-anchor-id="anexo-c-programación-semana-de-inducción.">Anexo C — Programación semana de inducción.</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Lunes 3 de agosto</th>
<th>Martes 4</th>
<th>Miércoles 5</th>
<th>Jueves 6</th>
<th>Lunes 10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7:00 – 8:00 a.m. Presentación del departamento. Dr.&nbsp;Alvaro Narváez 8:00 – 9:00 a.m. Situación de la niñez en Colombia. Dra. Alicia Ortega. 9:30 – 11:00 a.m. Historia clínica Pediátrica. Dr.&nbsp;Manuel Santiago Ordóñez</td>
<td>8:00 a.m. – 12:00 m. Inducción HUSJ. Auditorio Antonio José Lemus Guzmán</td>
<td>7:00 – 8:00 a.m. Triage pediátrico. Dr.&nbsp;Camilo Garcés. 8:00 a.m. – 10:00 a.m. Búsqueda de la literatura. Dra. Ginna Paola Cabra. 10:30 – 12:00 m. Lactancia materna. Dra. Gloria Martínez.</td>
<td>7:00 a.m. – 12:00 m NALS.</td>
<td>7:00 – 8:30 a.m. Etapas del desarrollo cerebral. Dra. María Eugenia Miño 8:30 – 9:30 a.m. Líquidos y electrolitos. Dra. Diana Muñoz 9:30 – 11:00 a.m. Escala abreviada del desarrollo 3. Dr.&nbsp;Alvaro Narváez</td>
</tr>
<tr class="even">
<td></td>
<td>2:00 – 5:00 p.m. Inducción CUS Alfonso López. Auditorio Antonio José Lemus Guzmán</td>
<td>1:30 – 5:00 p.m. Inducción Clínica La Estancia. Auditorio Antonio José Lemus Guzmán</td>
<td>1:00 – 5:00 p.m. NALS. Laboratorio de simulación</td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>NOTAS: La inducción del HSLV para los estudiantes se realizará de manera virtual - El PALS se programa para el 12, 13 y 14 de agosto de 1 a 5 p.m.</strong></p>
</section>
<section id="anexo-d-rotación-de-pediatría-social" class="level3">
<h3 class="anchored" data-anchor-id="anexo-d-rotación-de-pediatría-social">Anexo D — Rotación de Pediatría Social</h3>
<p>Docentes: Álvaro Iván Narváez (coordinador), Claudia Guzmán, Alicia Ortega.</p>
</section>
<section id="section-2" class="level3">
<h3 class="anchored" data-anchor-id="section-2"></h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Capítulos y Temas</th>
<th>Acompañamiento Directo</th>
<th></th>
<th>Trabajo Independiente</th>
<th></th>
<th>Apoyo bibliográfico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>Hs</td>
<td>Metodología</td>
<td>Hs</td>
<td>Metodología</td>
<td></td>
</tr>
<tr class="even">
<td>Elaboración de Historia Clínica Pediátrica</td>
<td>17</td>
<td>PR</td>
<td>4</td>
<td>PR</td>
<td>-Texto, manuales y videos AIEPI. -Fundamentos de Pediatría. CIB Medellín. -El Niño Sano 4 edición. Editorial Médica Panamericana, Grupo de Puericultura de la Universidad de Antioquia. 2016 -Resolución 3280 de 2018 del Ministerio de Salud de Colombia. -El Pediatra Eficiente y Pediatría Práctica. Ernesto Plata Rueda. -Desarrollo psicológico del niño. Asociación española de Pediatría. 2010. -Temas de psicología evolutiva y psiquiatría infantil, desde el modelo Biopsicosocial. Colección educación médica. Universidad El Bosque Tomo 1 y Mejor infancia Bogotá 2005. The Massachusetts. -General Hospital Guide to Learning Disabilities, H kent Wilson, Ellen B Braaten, -Humana Press; Springer Nature 2019 -Manuales de clasificación internacional de Enfermedades internacional CIE 11 y DSM V. -Manuales de clasificación internacional de enfermedades CIE 11 y DSMV -Kaplan y Sadock, Sinopsis de Psiquiatría, Lippincot Williams y Wilkins, 10 edición, 2009 . -Psiquiatría infantil Aspectos claves, Juan David Palacio O, 1ª edición, CIB fondo editorial.</td>
</tr>
<tr class="odd">
<td>Valoración integral en salud del niño menor de 5 años (Resolución 3280 de 2018 del Ministerio de Salud): AIEPI, EAD 3, Apgar familiar, instrumento VALE</td>
<td>8</td>
<td>TU</td>
<td>8</td>
<td>TG</td>
<td></td>
</tr>
<tr class="even">
<td>Conceptos generales de crecimiento normal del niño y adolescente</td>
<td>2</td>
<td>ME</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="odd">
<td>Desarrollo biopsicosocial del niño hasta la edad preescolar (6 años):</td>
<td>2</td>
<td>PR</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Desarrollo psicológico del niño y alteraciones más frecuentes.</td>
<td>4</td>
<td>PG</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Puericultura del lactante y del preescolar</td>
<td></td>
<td></td>
<td>4</td>
<td>TU</td>
<td></td>
</tr>
<tr class="even">
<td>Alimentación complementaria</td>
<td>3</td>
<td>ME</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="odd">
<td>Maltrato infantil y estrategias de promoción del buentrato</td>
<td>3</td>
<td>PG</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Abuso sexual</td>
<td>3</td>
<td>PG</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Trastornos de comportamiento más frecuentes en la infancia y adolescencia.</td>
<td>4</td>
<td>PR</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Depresión y conductas suicidas en la infancia y la adolescencia.</td>
<td>8</td>
<td>PR</td>
<td>4</td>
<td>PR</td>
<td></td>
</tr>
<tr class="odd">
<td>TOTAL HORAS</td>
<td>54</td>
<td></td>
<td>24</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="section-45" class="level3">
<h3 class="anchored" data-anchor-id="section-45"></h3>
</section>
<section id="cuadro-semanal-de-prácticas-de-pediatría-social" class="level3">
<h3 class="anchored" data-anchor-id="cuadro-semanal-de-prácticas-de-pediatría-social">CUADRO SEMANAL DE PRÁCTICAS DE PEDIATRÍA SOCIAL</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>LUNES</th>
<th>MARTES</th>
<th>MIERCOLES</th>
<th>JUEVES</th>
<th>VIERNES</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>8:00 a 12:00 AM. Consulta Externa Pediátrica Centro Universitario de Salud “Alfonso López” Dra. Alicia Ortega</td>
<td>7:00 a 8:00 a.m Actividad académica 8:00 a 11 AM. Consulta Salud Mental Dra. Claudia Guzmán</td>
<td>7:00 a 9 AM Programa de Radio Crianza Feliz 9:00 a 12:00 Práctica comunitaria Dra. Alicia Ortega</td>
<td>8:00 a 11 AM Clínica Promoción del Buen trato, HUSJ Dra. Claudia Guzmán, Dr.&nbsp;A. Narváez.</td>
<td>8:00 a12:00 AM. Consulta Salud Mental Dra. C. Guzmán</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>2:00p.m.-4:00 pm Mesa redonda</td>
<td>2:00 p.m.- 4:00p.m. Mesa redonda</td>
<td>Capacitación de AIEPI</td>
</tr>
</tbody>
</table>
</section>
<section id="anexo-e-rotación-de-medicina-interna" class="level3">
<h3 class="anchored" data-anchor-id="anexo-e-rotación-de-medicina-interna">Anexo E — Rotación de Medicina Interna</h3>
<p>Docentes: Olga Lucía Prado (coordinadora), Olga Cújar, Eliana Zemanate, Lorena Benavides</p>
</section>
<section id="section-53" class="level3">
<h3 class="anchored" data-anchor-id="section-53"></h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Capítulos Y Temas</th>
<th>Acompañamiento Directo</th>
<th></th>
<th>Trabajo Independiente</th>
<th></th>
<th>Apoyo bibliográfico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>Hs</td>
<td>Metodología</td>
<td>Hs</td>
<td>Metodología</td>
<td></td>
</tr>
<tr class="even">
<td>HEMATOLOGÍA</td>
<td>10</td>
<td></td>
<td>6</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Anemias</td>
<td>4</td>
<td>PG - TS</td>
<td>2</td>
<td>AA-PR</td>
<td>Iron Deficiency Anemia: An Updated Review. Leung AKC, Lam JM, Wong AHC, Hon KL, Li X.Curr Pediatr Rev.&nbsp;2024;20(3):339-356. doi: 10.2174/1573396320666230727102042</td>
</tr>
<tr class="even">
<td>Púrpura Trombocitopénica Autoinmune</td>
<td>4</td>
<td>PG -TS</td>
<td>2</td>
<td>AA</td>
<td>[Primary immune thrombocytopenia: Experience of a specialised clinic]. Rodríguez-Vigil Iturrate C, Sanz de Miguel MP, Martínez Faci C, Murillo Sanjuan L, MP.An Pediatr (Engl Ed). 2020 Jul;93(1):16-23. doi: 10.1016/j.anpedi.2019. Henoch-Schonlein Purpura in Children: An Updated Review. Leung AKC, Barankin B, Leong KF.Curr Pediatr Rev.&nbsp;2020;16(4):265-276. doi: 10.2174/1573396316666200508104708.PMID: 32384035</td>
</tr>
<tr class="odd">
<td>Púrpura Henoch - Schönlein</td>
<td>2</td>
<td>PG - PS</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="even">
<td>ONCOLOGIA</td>
<td>4</td>
<td></td>
<td>3</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Enfermedades Mieloproliferativas Signos Tempranos de cáncer</td>
<td>4</td>
<td>PG – PS</td>
<td>3</td>
<td>AA</td>
<td>Recent Advances in Pediatric Cancer Research. McEachron TA, Helman LJ.Cancer Res. 2021 Dec 1;81(23):5783-5799. doi: 10.1158/0008-5472.CAN-21-1191. Epub 2021 Sep 24.PMID: 34561271</td>
</tr>
<tr class="even">
<td>CARDIOLOGIA</td>
<td>9</td>
<td></td>
<td>6</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Cardiopatías congénitas</td>
<td>4</td>
<td>MEC – PG – PR</td>
<td>3</td>
<td>AA</td>
<td>Guidelines for Diagnosis and Management of Heart Failure in Children with CHD and Cardiomyopathies Chapter First Online: 30 July 2024 pp 471–484 https://doi.org/10.1007/978-981-19-8357-3_56</td>
</tr>
<tr class="even">
<td>Insuficiencia cardíaca</td>
<td>4</td>
<td>MEC – PG – PR</td>
<td>2</td>
<td>AA</td>
<td>Update of Pediatric Heart Failure. Watanabe K, Shih Pediatr Clin North Am. 2020 Oct;67(5):889-901. doi: 10.1016/j.pcl.2020.06.004. Epub 2020 Aug 11.PMID: 32888688 Review Falla cardíaca en pacientes pediátricos. Fisiopatología y manejo. DOI: 10.1016/j.rccar.2018.02.003 Vol. 25. Núm. 4. páginas 286-294 (julio - agosto 2018</td>
</tr>
<tr class="odd">
<td>Fiebre reumática</td>
<td>1</td>
<td>EC-PG</td>
<td>1</td>
<td>AA</td>
<td>Acute Rheumatic Fever. Lahiri S, Sanyahumbi A.Pediatr Rev.&nbsp;2021 May;42(5):221-232. doi: 10.1542/pir.2019-0288.PMID: 33931507</td>
</tr>
<tr class="even">
<td>Manejo de LEV de mantenimiento</td>
<td>4</td>
<td>APB-PR</td>
<td>3</td>
<td>AA 1</td>
<td>Balanced crystalloid solutions versus 0.9% saline for treating acute diarrhoea and severe dehydration in children. Florez ID, Sierra J, Pérez-Gaxiola G.Cochrane Database Syst Rev.&nbsp;2023 May 17;5(5):CD013640. doi: 10.1002/14651858.CD013640.pub2. http://hdl.handle.net/20.500.11912/11237</td>
</tr>
<tr class="odd">
<td>NEFROLOGIA</td>
<td>8</td>
<td>MEC-PR</td>
<td>5</td>
<td>AA</td>
<td></td>
</tr>
<tr class="even">
<td>Síndrome nefrítico y nefrótico</td>
<td>4</td>
<td>MEC-PR</td>
<td>3</td>
<td>AA-PR</td>
<td>Protocolos diagnósticos y terapéuticos de nefrología pediátrica serie: protocolos de la AEP asociación española de pediatría año de edición: 2022</td>
</tr>
<tr class="odd">
<td>Insuficiencia renal Aguda y Enfermedad renal crónica</td>
<td>4</td>
<td>MEC-PR</td>
<td>2</td>
<td>AA-PR</td>
<td>Kidney Disease: Improving Global Outcomes (KDIGO) CKD Work Group. (2024). KDIGO 2024 Clinical Practice Guideline for the Evaluation and Management of Chronic Kidney Disease. Kidney International, 105(4S), S117–S314</td>
</tr>
<tr class="even">
<td>REUMATOLOGIA</td>
<td>4</td>
<td>EC-PG</td>
<td>3</td>
<td>AA</td>
<td></td>
</tr>
<tr class="odd">
<td>Artritis</td>
<td>2</td>
<td>EC-PG</td>
<td>1</td>
<td>AA</td>
<td>Guía de práctica clínica para la detección temprana, el diagnóstico, el tratamiento y el seguimiento de los pacientes con artritis reumatoide. Asociación Colombiana de Reumatología, 2022 Asociación Colombiana de Reumatología, 2022. Rev Colomb Reumatol. 2023. https://doi.org/10.1016/j.rcreu.2023.02.001</td>
</tr>
<tr class="even">
<td>LES</td>
<td>2</td>
<td>EC-PG</td>
<td>2</td>
<td>AA</td>
<td>Clasificación del lupus eritematoso sistémico en niños y adultos. Inmunología clínica , 234 , 108898. 2022.</td>
</tr>
<tr class="odd">
<td>ENDOCRINOLOGIA Y METABOLISMO</td>
<td>6</td>
<td>EC-PG</td>
<td>3</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Obesidad</td>
<td>2</td>
<td>EC-PG</td>
<td>1</td>
<td>AA</td>
<td>Child and adolescent obesity. Lister NB, Baur LA, Felix JF, Hill AJ, Marcus C, Reinehr T, Summerbell C, Wabitsch M.Nat Rev Dis Primers. 2023 May 18;9(1):24. doi: 10.1038/s41572-023-00435-4.PMID: 37202378 Review.</td>
</tr>
<tr class="odd">
<td>Diabetes Mellitus</td>
<td>2</td>
<td>EC-PG</td>
<td>1</td>
<td>AA</td>
<td>Challenges in the diagnosis of diabetes type in pediatrics. Siller AF, Tosur M, Relan S, Astudillo M, McKay S, Dabelea D, Redondo MJ.Pediatr Diabetes. 2020 Nov;21(7):1064-1073. doi: 10.1111/pedi.13070. Epub 2020 Jul 23.PMID: 32562358 Review</td>
</tr>
<tr class="even">
<td>Pancreatitis</td>
<td>2</td>
<td>EC-PG</td>
<td>1</td>
<td>AA</td>
<td>Acute Pancreatitis in Children. Afzal S, Kleinhenz J.Pediatr Ann. 2021 Aug;50(8):e330-e335. doi: 10.3928/19382359-20210713-01. Epub 2021 Aug 1.PMID: 34398718</td>
</tr>
<tr class="odd">
<td>VACUNACIÓN</td>
<td>8</td>
<td>PG-PR-EC</td>
<td>3</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Esquema de vacunación y ESAVI Esquemas atrasados de vacunación</td>
<td></td>
<td>PG-PR-TS</td>
<td></td>
<td>AA</td>
<td>Lineamientos para la gestión y administración del programa ampliado de inmunizaciones - PAI – 2026</td>
</tr>
<tr class="odd">
<td>Turnos</td>
<td>8</td>
<td></td>
<td>15</td>
<td>PR</td>
<td></td>
</tr>
<tr class="even">
<td>TOTAL HORAS</td>
<td>61</td>
<td></td>
<td>44</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="section-131" class="level3">
<h3 class="anchored" data-anchor-id="section-131"></h3>
</section>
<section id="cuadro-semanal-de-prácticas-de-medicina-interna" class="level3">
<h3 class="anchored" data-anchor-id="cuadro-semanal-de-prácticas-de-medicina-interna">CUADRO SEMANAL DE PRÁCTICAS DE MEDICINA INTERNA</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Lunes</th>
<th>Martes</th>
<th>Miércoles</th>
<th>Jueves</th>
<th>Viernes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dra. Eliana Zemanate</td>
<td>UCIP HSLV 7am- 12m</td>
<td>UCIP HSLV 8:30 am –12m</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Dra. Lorena Benavides</td>
<td>Salas o urgencias HSLV 7am -12m</td>
<td></td>
<td></td>
<td>Salas o urgencias HSLV 7am -12m</td>
<td>Salas o urgencias HSLV 8:30 am–12m</td>
</tr>
<tr class="odd">
<td>Dra. Olga Lucia Prado</td>
<td></td>
<td></td>
<td>Consulta externa HUSJ 7:30 am-12 m</td>
<td>Consulta externa HSLV 7:30 am-12 m</td>
<td>Salas o urgencias HSLV 8:30 am–12m</td>
</tr>
<tr class="even">
<td>Dra. Olga Lucia Cujar</td>
<td></td>
<td>Salas o urgencias HUSJ 8:30 am - 12m</td>
<td>Vacunación CUS 7:30 – 12 m</td>
<td></td>
<td>Salas o urgencias HSLV 8:30 am–12m</td>
</tr>
</tbody>
</table>
</section>
<section id="anexo-f-rotación-de-infecciosas" class="level3">
<h3 class="anchored" data-anchor-id="anexo-f-rotación-de-infecciosas">Anexo F — Rotación de Infecciosas</h3>
<p>Docentes: Manuel Santiago Ordóñez (coordinador), Ginna Cabra, Yéssica Bravo, Olga Cújar, Diana Muñoz.</p>
</section>
<section id="section-132" class="level3">
<h3 class="anchored" data-anchor-id="section-132"></h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Capítulos y Temas</th>
<th>Acompañamiento Directo</th>
<th></th>
<th>Trabajo Independiente</th>
<th></th>
<th>Apoyo bibliográfico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>Hs</td>
<td>Metodología</td>
<td>Hs</td>
<td>Metodología</td>
<td></td>
</tr>
<tr class="even">
<td>Enfoque de la Historia clínica en el niño infectado, semiología</td>
<td>2</td>
<td>PG, PR</td>
<td>2</td>
<td>EC</td>
<td>1. Beltrán-Arroyave CP, López López P, editores. Infectología pediátrica para el día a día. Bogotá: Asociación Colombiana de Infectología (ACIN); 2020. 2. American Academy of Pediatrics. Red Book: 2024-2027 Report of the Committee on Infectious Diseases. Kimberlin DW, Banerjee R, Barnett ED, Lynfield R, Sawyer MH, editores. 33a ed.&nbsp;Itasca (IL): American Academy of Pediatrics; 2024.</td>
</tr>
<tr class="odd">
<td>Tuberculosis en Pediatría: Definición, epidemiología, criterios diagnósticos, tratamiento, vacuna BCG</td>
<td>4</td>
<td>PG, PR, TS</td>
<td>2</td>
<td>AA</td>
<td>1. Guía de Tuberculosis Ministerio de salud y protección social. 2. Tuberculosis in children, Pediatr Rev 2019 Apr, 3. AIEPI: capítulo de tuberculosis, cuadros de procedimientos.</td>
</tr>
<tr class="even">
<td>Infección Respiratoria Aguda baja: NAC y sus complicaciones, bronquiolitis, neumonía atípica. Prevalencia, factores de riesgo, cuadro clínico, uso racional de antibióticos, dx diferencial</td>
<td>10</td>
<td>PG, TS, EC, PR</td>
<td>2</td>
<td>AA</td>
<td>1. Mini-symposium:Lung diseases in children living in poverty Childhood pneumonia in low-and-middle-income countries: An update Diana Marangu a,b, Heather J. Zar b,⇑ 2. Department of Paediatrics and Child Health, University of Nairobi, Nairobi, Kenya 3. Department of Paediatrics and Child Health and SA Medical Research Council Unit on Child and Adolescent Health, University of Cape Town, Cape Town, South Africa 4. ELSEVIER Paediatric Respiratory Reviews 2019 5. PROGRAMA NACIONAL DE PREVENCION, MANEJO Y CONTROL DE LA INFECCION RESPIRATORIA AGUDA Y LA ENFERMEDAD DIARREICA AGUDA. LINEAMIENTOS TECNICOS Y OPERATIVOS Versión 1. Subdirección de Enfermedades Transmisibles. 2023. 6. BES Boletin epidemiologico semanal. Infección respiratoria aguda Colombia. Reporte semanas epidemiológicas. Instituto Nacional de Salud. LINK: https://www.ins.gov.co/buscador-eventos/Paginas/Vista-Boletin-Epidemilogico.aspx 7. Estrategia de Atención integrada a las enfermedades prevalentes de la infancia. AIEPI. OPS-OMS.2016.</td>
</tr>
<tr class="odd">
<td>Enfermedades febriles: Fiebre sin foco aparente: evaluación clínica, indicación de laboratorios, uso racional de antipiréticos y antibióticos</td>
<td>4</td>
<td>PG, PR, EC, SE</td>
<td>2</td>
<td>AA</td>
<td>1. Validation of the “Step-by-Step” Approach in the Management of Young Febrile Infants 2. Borja Gomez, MD, a, b Santiago Mintegi, MD, PhD, a, b Silvia Bressan, MD, PhD, c Liviana Da Dalt, MD, d Alain Gervaix, MD, e Laurence Lacroix, MD, e on behalf of the European Group for Validation of the Step-by-Step Approach 3. PEDIATRICS Volume 1 38, number 2 , A ugust 2016: e2 0154381 4. Manejo del paciente pediátrico con fiebre sin foco. Josefa Ares Alvarez. 17º Congreso Asociación Española de Pediatría (AEP) 2020 5. Estrategia de Atención integrada a las enfermedades prevalentes de la infancia. AIEPI. OPS-OMS.2016.</td>
</tr>
<tr class="even">
<td>Meningitis Bacteriana: Epidemiología, Prevención, cuadro clínico, ayudas diagnósticas, tratamiento</td>
<td>4</td>
<td>PG, PR, EC, SI</td>
<td>2</td>
<td>AA</td>
<td>1. Meningitis bacteriana aguda 1. Sonia Sanchez Cárdenas, Juan Francisco Collado Caparrós, Cinta Téllez García,Susana Beatriz Reyes Domínguez Hospital Universitario Virgen de la Arrixaca. Murcia Tellez Gonzalez C, Reyes Dominguez S, Sanchiz Cardenas S, Collado Caparros JF. Meningitis bacteriana aguda. Protoc diagn ter pediatr. 2021;1:611-25. 2. Infectología Pediátrica para el día a día, editores Claudia P. Beltrán-Arroyave - Pio López López, capitulo 33 Meningitis y encefalitis 257 Juan Pablo Rojas Hernández,Oskar Andrey Oliveros Andrade. 3. Tratamiento: Enlace del vídeo https://youtu.be/3oTUcOfbbQk 4. Diagnóstico Enlace del vídeo https://youtu.be/_QeQfJDzTNM 5. CLINICA. Enlace del vídeo. https://youtu.be/e-5rZ_G7j7U 8. DEFINICION. Enlace del vídeo https://youtu.be/hjIeyydFy1k 9. PROTOCOLO DE MENINGITIS BACTERIANA AGUDA, sociedad Española de Cuidados intensivos 2023.</td>
</tr>
<tr class="odd">
<td>Antibióticos: uso racional indicaciones, dosis, efectos adversos de Betalactámicos, aminoglucócidos, macrólidos, quinolonas, lincosamidas</td>
<td>4</td>
<td>PG, PR, EC, TS</td>
<td>2</td>
<td>AA</td>
<td>1. Antibiotic Basics for Clinicians. The ABCs for choosing the right antibacterial agent. Secont edition. Departments of Microbiology/Immunology and Medicine Northwestern University, Chicago, Illinois Alan R. Hauser 2013</td>
</tr>
<tr class="even">
<td>Infecciones de tejidos blandos y osteomielitis: infecciones por E. Aureus, S. Piógenes</td>
<td>4</td>
<td>PG, TS, PR, EC</td>
<td>4</td>
<td>AA</td>
<td>1. Beltrán-Arroyave CP, López López P, editores. Infectología pediátrica para el día a día. Bogotá: Asociación Colombiana de Infectología (ACIN); 2020. 2. American Academy of Pediatrics. Red Book: 2024-2027 Report of the Committee on Infectious Diseases. Kimberlin DW, Banerjee R, Barnett ED, Lynfield R, Sawyer MH, editores. 33a ed.&nbsp;Itasca (IL): American Academy of Pediatrics; 2024. 3. Infecciones por Estafilococo aureus meticilino resistente adquirido en la comunidad en la población pediátrica en dos hospitales en Popayán-Colombia. Figueroa, Arteaga, Aguirre, Solano, Delgado. Revista de la Facultad Ciencias de la Salud de la Universidad del Cauca. Vol 12. Nº 4. 2010 Guia para el tratamiento de las Infecciones de tejidos blandos en niños. Guido de Rosa. 2013</td>
</tr>
<tr class="odd">
<td>Otras infecciones transmisibles y emergentes: difteria, tosferina, tétanos, exantemáticas, infecciones virales</td>
<td>8</td>
<td>PG, TS, PR, EC</td>
<td>6</td>
<td>AA</td>
<td>1. American Academy of Pediatrics. Red Book: 2024-2027 Report of the Committee on Infectious Diseases. Kimberlin DW, Banerjee R, Barnett ED, Lynfield R, Sawyer MH, editores. 33a ed.&nbsp;Itasca (IL): American Academy of Pediatrics; 2024.</td>
</tr>
<tr class="even">
<td>Infección de vías Urinarias: Pielonefritis</td>
<td>2</td>
<td>PG, PR, EC</td>
<td>1</td>
<td>AA</td>
<td>1. Etiología y sensibilidad bacteriana en infección urinaria en niños. Hospital Infantil Club Noel y Hospital Universitario del valle, Cali, Colombia. Castaño, Gonzalez, Buitrago, De Rovetto. Colombia Médica. Vol 38, Nº 2 de 2007. 2. Etiología bacteriana y sensibilidad antibiótica en niños con infección urinaria de dos centros hospitalarios de Popayán. Czeczotta, Molano, Cerón, Castro, Solano, Delgado. Revista de la Facultad Ciencias de la Salud de la Universidad del Cauca. 2013 3. Guía NICE 2017 (NG54): Guía de diagnóstico y tratamiento de infección de tracto urinario en lactantes, niños y adolescentes. https://www.nice.org</td>
</tr>
<tr class="odd">
<td>Medicina basada en la evidencia</td>
<td>3</td>
<td>TS, TU</td>
<td>1</td>
<td>AA</td>
<td>1. Shoemaker R, Delgado Noguera M. Fundamentos de epidemiología. Editorial Universidad del Cauca. Primera Edición; 2019. 202 p.&nbsp;2. Ruiz Á, Gómez C. Introducción a los diseños de investigación: selección del diseño apropiado. Segunda Ed. Epidemiología Clínica: Investigación Clínica Aplicada. Editorial Médica Panamericana; 2015. p.&nbsp;168. 3. Fletcher R, Fletcher SW, Fletcher Grant S. Epidemiología Clínica. Wolters Kluwer. 5.a edición; 2016. 255p. 4. Guyatt G, Drummond R, Maureen M, Deborah C. User´s Guides to the Medical Literature. 3rd editio. JAMAevidence; 2015. 516 p.&nbsp;5. De Brún C, Pearce-Smith N. Searching Skills Toolkit Finding the Evidence. Second Edi. Heneghan C, Perera R, Badenoch D, editores. BMJ Books; 2014. 159 p.</td>
</tr>
<tr class="even">
<td>Turnos</td>
<td>22</td>
<td>PR</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>67</td>
<td></td>
<td>24</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="section-169" class="level3">
<h3 class="anchored" data-anchor-id="section-169"></h3>
</section>
<section id="cuadro-semanal-de-prácticas-de-infecciosas" class="level3">
<h3 class="anchored" data-anchor-id="cuadro-semanal-de-prácticas-de-infecciosas">CUADRO SEMANAL DE PRÁCTICAS DE INFECCIOSAS</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Lunes</th>
<th></th>
<th>Martes</th>
<th></th>
<th>Miércoles</th>
<th>Jueves</th>
<th></th>
<th>Viernes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7:00</td>
<td>Rotación Clínica 7-12 AM HUSJ Medio grupo Dr.&nbsp;Ordoñez</td>
<td>Rotación Clínica 7-12 AM HUSJ Medio grupo Dra. Bravo</td>
<td>Caso clínico 7-8 AM FCS</td>
<td></td>
<td></td>
<td>Rotación Clínica 7-11 AM HUSJ Medio grupo Dra. Bravo</td>
<td>Rotación Clínica 7-11 AM HUSJ Medio grupo Dra. Muñoz</td>
<td>Ateneo 7-8 AM FCS</td>
</tr>
<tr class="even">
<td>8:00</td>
<td></td>
<td></td>
<td>Rotación clínica 8-12 AM HUSJ Medio grupo Dr.&nbsp;Ordoñez</td>
<td>Rotación clínica 8-12 AM HUSJ Medio grupo Dra. Muñoz</td>
<td>Rotación clínica 8-12 AM CUS Todo el grupo Dr.&nbsp;Ordoñez</td>
<td></td>
<td></td>
<td>Lectura crítica de la literatura 8-12 AM FCS Todo el grupo Dra. Cabra</td>
</tr>
<tr class="odd">
<td>9:00</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>10:00</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>11:00</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>12:00</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>1:00</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>2:00</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>Revisión de Tema 2-4 PM</td>
<td>Revisión de Tema 2-4 PM</td>
<td></td>
<td>AIEPI 2-5 PM FCS</td>
</tr>
<tr class="odd">
<td>3:00</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>4:00</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="anexo-g-rotación-de-urgencias" class="level3">
<h3 class="anchored" data-anchor-id="anexo-g-rotación-de-urgencias">Anexo G — Rotación de Urgencias</h3>
</section>
<section id="section-170" class="level3">
<h3 class="anchored" data-anchor-id="section-170"></h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Capítulos Y Temas</th>
<th>Acompañamiento Directo</th>
<th></th>
<th>Trabajo Independiente</th>
<th></th>
<th>Apoyo bibliográfico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>Hs</td>
<td>Metodología</td>
<td>Hs</td>
<td>Metodología</td>
<td></td>
</tr>
<tr class="even">
<td>AIEPI Urgencias</td>
<td>2</td>
<td>ABP - PR</td>
<td>3</td>
<td>AA</td>
<td>TRAUMA CRANEOENCEFALICO EN EL PACIENTE CRITICOS: 1. Pediatric Head Trauma: A Review and Update. Pediatrics in Review, 2019. Hernández Rastrollo, R. Traumatismos craneoencefálicos. Pediatr Integral 2019; XXIII (1): 6 –14 2. Guidelines for the Management of Pediatric Severe Traumatic Brain Injury, Third Edition: Update of the Brain Trauma Foundation Guidelines, 2019 3. Kochanek P, Tasker R et al.&nbsp;Guidelines for the management of pediatric severe traumatic brain. www.pccmjournal.org. March 2019. Vol 20. Number 3. CRISIS Y ESTATUS CONVULSIVO: 1. Lawton B, David T, et al.&nbsp;An update in the initial management of paediatric status epilepticus. Curr Opin Pediatr 2018, 30:000 – 000. 2. Bauerschmidt A, Martin A, et al.&nbsp;Advancements in the critical care management of status epilepticus. Curr Opin Crit Care 2017, 23:122 – 127. 3. Paz C, Varela X, y col.&nbsp;Revisión del estado epiléptico convulsivo pediátrico y su manejo antiepiléptico. Rev Med Chile 2016; 144: 83-93. STATUS ASMATICO: 1.Global initiative for Asthma. Global Strategy for Asthma Management and Prevention, 2019. Available from: www.ginasthma.org 2. Guideline on management of the acute asthma attack in children by Italian Society of Pediatrics. Ital J Pediatr. 2018 Apr 6;44(1):46. doi: 10.1186/s13052-018-0481-1. 3. Roriguez C., Sossa M.; Valores de referencia de flujo espiratorio pico en niños y adolescentes sanos en la ciudad de Bogotá. Revista Colombiana de Neumología. Volumen 16 N°1. 2004 MANEJO DE LIQUIDOS: 1. ​Colombia. Ministerio de Salud y Protección Social, Colciencias, Universidad de Antioquia. Guía de práctica clínica para prevención, diagnóstico y tratamiento de la enfermedad diarreica aguda en niños menores de 5 años SGSS - 2013 Guía No.&nbsp;8 GPC-EDA. Bogotá,2013 2. Lozano J, Granados C, Hernandez A, Perez H, M. S.Uso y abuso del examen directo de materia fecal (coproscopico) en el manejo de casos de diarrea aguda en tres instituciones de Bogota. Actual pediátr. 1997 7:152-7. 3. Suescun Vargas, J. Recomendaciones Prácticas en el Tratamiento Hídrico en Pediatría. Departamento de Pediatría Universidad del Rosario. https://www.researchgate.net/publication/326020111. DOI: 10.13140/RG.2.2.28889.01127 4. CARRANZA, C.; GÓMEZ J.; WILCHES L.. REHIDRATACIÓN EN EL PACIENTE PEDIÁTRICO. REVISTA MED 24(2): 2016 MANEJO DE ELECTROLITOS: 1. Nefrología Pediátrica. G Gordillo. Tercera edición 2. Intravenous fluids: balancing solutions. J Nephrol. 2017 Aug;30(4):485-492. doi: 10.1007/s40620-016-0363-9. Epub 2016 Nov 29. PATOLOGÍA QUIRÚRGICA 1. Braga LH. Lorenzo AP Romao RLP. Canadian Urological Association-Pediatric Urologists of Canada (CUA-PUC) guideline for the diagnosis, management, and followup of cryptorchidism. Can Urol Assoc J 2017; 11(7): E251 – 60. 2. Radmayr C, Dogan HS, Hoebeke P, Kocvara R, Nijman R, Stein R, Undre S, Tekgul S. Management of undescended testes: European Association of Urology/European Society for Paediatric Urology Guidelines. J Ped Urol 2016; 12: 335-343. 3. Cooper CS, Docimo SG. Undescended testes (cryptorchidism) in children: Clinical features and evaluation. Uptodate, literatura review current through: sep 2018. 4. Cooper CS, Docimo SG. Undescended testes (cryptorchidism) in children: Management. Uptodate, Sep 24, 2018. Up todate 5. Jonathan l Singer,Md Jan E DrutzMD Inguinal hernia in children Sep 2018 6. David E Wesson, MD Sussan B torrey MD, Liver,splen and páncreas injury in children with blunt abdominal trauma Oct 03 2017 up todate 7. Richard A Saladino MD KAvitha Conti Md Pediatric blunt abdominal trauma:Innitial evaluation and stabilization, April 24 2018 up todate 8. Lois K lee MD, Gary R Fleisher MD Trauma management:approach to the unstable child,Aug 13 2018 up todate 9. Lois k Lee MD, Gary Fleisher , MD Trauma management : unique pediatric considerations Dec,2017 up todate 10. Patric j javid, MD Eric M Paul MD Meckel¨s diverticulum Feb 07, 2018 up todate</td>
</tr>
<tr class="odd">
<td>Evaluación del equilibrio hídrico</td>
<td>4</td>
<td>TS - PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="even">
<td>Estatus convulsivo</td>
<td>4</td>
<td>TS</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="odd">
<td>Trauma Craneoencefálico</td>
<td>4</td>
<td>ABP</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="even">
<td>Crisis Asmática</td>
<td>4</td>
<td>MEC - ABP- PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="odd">
<td>Enfermedad diarreica aguda</td>
<td>4</td>
<td>MEC - PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="even">
<td>Intoxicaciones</td>
<td>4</td>
<td>ABP - PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="odd">
<td>Patología Quirúrgica</td>
<td>6</td>
<td>MEC - PR</td>
<td>6</td>
<td>AA</td>
<td></td>
</tr>
<tr class="even">
<td>Otros temas del área de urgencias</td>
<td>9</td>
<td>EC - PR</td>
<td>10</td>
<td>AA</td>
<td></td>
</tr>
<tr class="odd">
<td>Turnos</td>
<td>8</td>
<td>EC-PR</td>
<td>15</td>
<td>PR</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="section-199" class="level3">
<h3 class="anchored" data-anchor-id="section-199"></h3>
</section>
<section id="cuadro-semanal-de-prácticas-de-urgencias" class="level3">
<h3 class="anchored" data-anchor-id="cuadro-semanal-de-prácticas-de-urgencias">CUADRO SEMANAL DE PRÁCTICAS DE URGENCIAS</h3>
<p>Cada grupo de rotación se divide en 2 subgrupos.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>LUNES</th>
<th></th>
<th>MARTES</th>
<th></th>
<th>MIÉRCOLES</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7:00 – 8.00 AM</td>
<td>Dra. Salas (Patología Quirúrgica) B</td>
<td>Dra. Henao A</td>
<td>Actividad académica</td>
<td></td>
<td>Dra. Salas A</td>
</tr>
<tr class="even">
<td>8:00 – 11:00 AM</td>
<td></td>
<td></td>
<td>Dr.&nbsp;Garcés A</td>
<td>Dra. Salas B</td>
<td></td>
</tr>
<tr class="odd">
<td>11:00 AM – 1:00 PM</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>2:00 – 4:00 PM</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>MESA REDONDA</td>
</tr>
</tbody>
</table>
</section>
<section id="anexo-h-rotación-de-consulta-externa" class="level3">
<h3 class="anchored" data-anchor-id="anexo-h-rotación-de-consulta-externa">Anexo H — Rotación de Consulta Externa</h3>
<p>Docentes: Martha Isabel Caicedo Rodríguez (coordinadora), Dolly Vidal Castro, María Eugenia Miño Arango.</p>
</section>
<section id="section-200" class="level3">
<h3 class="anchored" data-anchor-id="section-200"></h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Capítulos Y Temas</th>
<th>Acompañamiento Directo</th>
<th></th>
<th>Trabajo Independiente</th>
<th></th>
<th>Apoyo Bibliográfico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>Hs</td>
<td>Metodología</td>
<td>Hs</td>
<td>Metodología</td>
<td></td>
</tr>
<tr class="even">
<td>CAPITULO GENERALIDADES</td>
<td>10</td>
<td>PG - PR</td>
<td>10</td>
<td>AA</td>
<td>1. Correa J, Gómez J, Posada R. Fundamentos de Pediatría. Generalidades. Tomo 1. CIB 4 Ed. 2012. 2. Atención integrada a las enfermedades prevalentes de la infancia. Libro clínico, Manual de Procedimientos 2016. 3. Manual de Neurología Infantil. A. Verdú 2da Edición. Editorial Panamericana. 4. Berman RE, Kliegman RM, Jenson HB. Tratado de pediatría de Nelson. Editorial Saunders, Edición 22. 5. Patrones de crecimiento en la población pediátrica de la OMS año 2008. 6. Manual de Diagnóstico y Terapéutica en Pediatría./ Julio Guerrero Fernández, Antonio Javier Carton, Ana Coral Barreda, et.a]. 6 Ed. - Madrid: Editorial Médica Panamericana, © 2018, disponible en la biblioteca salud. 7. Herramienta clínica para el abordaje inicial de las condiciones prevalentes en la primera infancia. https://herramientaclinicaprimerainfancia.minsalud.gov.co/ 8. El niño con problemas respiratorios./ Claudio Castaños, Pedro B. Rino, Mirta Susana Rodríguez / Coordinadores - Buenos Aires: Editorial Médica Panamericana, © 2018 9. Escala abreviada del desarrollo. Tercera edición. 2018 Ministerio de Salud de Colombia</td>
</tr>
<tr class="odd">
<td>Elaboración de la historia clínica pediátrica anamnesis y examen clínico</td>
<td>2</td>
<td>PG -PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="even">
<td>Examen físico y semiología del paciente pediatrico</td>
<td>2</td>
<td>PG - PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="odd">
<td>Crecimiento y desarrollo del adolescente</td>
<td>2</td>
<td>PG - PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="even">
<td>AIEPI clínico</td>
<td>2</td>
<td>PG – PR</td>
<td>2</td>
<td>AA - PR</td>
<td></td>
</tr>
<tr class="odd">
<td>Neurodesarrollo Escala de Milani Comparetti</td>
<td>2</td>
<td>ABP-PR</td>
<td>2</td>
<td>AA - PR</td>
<td></td>
</tr>
<tr class="even">
<td>Capitulo ENFERMEDADES INFECCIOSAS</td>
<td>16</td>
<td>MEC – PG -PR</td>
<td>8</td>
<td>AA</td>
<td>1. Nelson, tratado de pediatría, 22 edición. 2. Faringoamigdalitis aguda y sus complicaciones, Protocolos diagnósticos y terapéuticos pediatría. 2023;2:51-79, sociedad española de infectologia pediátrica, disponible en https://www.aeped.es/protocolos 3. Sinusitis y sus complicaciones. Celulitis preseptal y orbitaria, Protocolos diagnósticos ter pediatr. 2023;2:51-79, sociedad española de infectologia pediátrica, disponible en https://www.aeped.es/protocolos 4. Otitis media aguda y otitis externa. Mastoiditis, Protocolos diagnosticos ter pediatr. 2023;2:51-79, sociedad española de infectologia pediátrica, disponible en https://www.aeped.es/protocolos 5. National Institute for Health and Care Excellence. Urinary Tract Infection in children Evidence Update October 2018. A summary of selected new evidence relevant to NICE clinical guideline 54 ‘Urinary tract infection in children: diagnosis, treatment and long-term management’ (2007). Disponible: http://guidance.nice.org.uk/CG54 6. ESCANDELL-RICO, Francisco Miguel y PEREZ-FERNANDEZ, Lucía. Infecciones del tracto urinario: etiología y susceptibilidades antimicrobianas. Rev Pediatr Aten Primaria [online]. 2022, vol.24, n.96 [citado 2026-07-28], pp.e355-e362. Disponible en: http://scielo.isciii.es/scielo.php?script=sci_arttext&amp;pid=S1139-76322022000400006&amp;lng=es&amp;nrm=iso 7. J.D.GonzálezRodríguez, G.M.FragaRodríguez, C.J.GarcíaVeraetal. Actualización de la guía de práctica clínica española sobre infección del tracto urinario en la población pediátrica. Síntesis de las recomendaciones sobre diagnóstico, tratamiento y seguimiento. Anales de Pediatría-https://doi.org/10.1016/j.anpedi.2024.06.001</td>
</tr>
<tr class="odd">
<td>Infección Urinaria</td>
<td>6</td>
<td>MEC – PG -PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="even">
<td>Vulvovaginitis</td>
<td>2</td>
<td>PG - PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="odd">
<td>Infección respiratoria alta Resfriado común, faringoamigdalitis, rinosinusitis, otitis media aguda</td>
<td>6</td>
<td>MEG – PG - PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="even">
<td>Infección respiratoria baja y otras neumopatías</td>
<td>2</td>
<td>PG-PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="odd">
<td>Capitulo: ENFERMEDADES POR SISTEMAS</td>
<td>20</td>
<td></td>
<td>10</td>
<td>AA</td>
<td>1. Gina, 2024, Global strategy for asthma management and prevention, pocket guide, disponible en https://ginasthma.org/2024-report/. 2.. Pediatric Neurology http//www.neurologia infantil.tk 3. Asociación Española de pediatría. Protocolos de dermatología. Disponible en: http://www.aeped.es/documentos/protocolos-dermatologia 4. Atopic Dermatitis. Andrea R. Waldman, Jusleen Ahluwalia, Jeremy Udkoff, Jenna F. Borok and Lawrence F. Eichenfield. Pediatrics in Review 2018;39;180. DOI: 10.1542/pir.2016-0169 5. Agüero Ureta, Rosario, López Bravo, Edinson, &amp; Hasbún Zegpi, Maria Trinidad. (2024). Dermatitis atópica severa en la infancia en la era de la medicina personalizada. Andes pediatrica, 95(3), 236- 243. https://dx.doi.org/10.32641/andespediatr.v95i3.5049 6. Paul, Sudip &amp; Nahar, Anjuman &amp; Bhagawati, Mrinalini &amp; Kunwar, Ajaya. (2022). A Review on Recent Advances of Cerebral Palsy. Oxidative Medicine and Cellular Longevity. 2022. 1-20. 10.1155/2022/2622310 7. Cómo leer la Piel Jairo Victoria Chaparro ; Lina María González Duque, Juan Carlos Gómez Hoyos - Medellín : Corporación para Investigaciones Biológicas CIB, 2015 disponible biblioteca FCS.</td>
</tr>
<tr class="even">
<td>Asma Manejo ambulatorio</td>
<td>6</td>
<td>MEC-EC-PR</td>
<td>2</td>
<td>AA-PR</td>
<td></td>
</tr>
<tr class="odd">
<td>Patología de Piel</td>
<td>4</td>
<td>MEC-PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="even">
<td>Parálisis Cerebral</td>
<td>4</td>
<td>MEC-TG-TU-PR</td>
<td>4</td>
<td>AA-TG</td>
<td></td>
</tr>
<tr class="odd">
<td>síndrome Convulsivo</td>
<td>4</td>
<td>PG-PR</td>
<td>1</td>
<td>AA</td>
<td></td>
</tr>
<tr class="even">
<td>Trastornos del aprendizaje</td>
<td>2</td>
<td>PG-PR</td>
<td>1</td>
<td>AA</td>
<td></td>
</tr>
<tr class="odd">
<td>Capitulo NUTRICIÓN</td>
<td>2</td>
<td></td>
<td>2</td>
<td>AA - TU</td>
<td>1. Herramienta clínica para el abordaje inicial de las condiciones prevalentes en la primera infancia. https://herramientaclinicaprimerainfancia.minsalud.gov.co/</td>
</tr>
<tr class="even">
<td>Temas: Evaluación del estado nutricional y antropometría</td>
<td>2</td>
<td>PG-PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="odd">
<td>Capítulo: OTROS TEMAS DEL ÁREA DE CONSULTA EXTERNA</td>
<td>7</td>
<td>PG-PR-EC</td>
<td>4</td>
<td>AA</td>
<td></td>
</tr>
<tr class="even">
<td>Turnos</td>
<td>8</td>
<td>EC-PR</td>
<td>15</td>
<td>PR</td>
<td></td>
</tr>
<tr class="odd">
<td>TOTAL HORAS</td>
<td>63</td>
<td></td>
<td>49</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="cuadro-semanal-de-prácticas-de-consulta-externa" class="level3">
<h3 class="anchored" data-anchor-id="cuadro-semanal-de-prácticas-de-consulta-externa">CUADRO SEMANAL DE PRÁCTICAS DE CONSULTA EXTERNA</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>LUNES</th>
<th>MARTES</th>
<th>MIERCOLES</th>
<th>JUEVES</th>
<th>VIERNES</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CONSULTA DE PEDIATRÍA - HUSJ DRA CAICEDO 7 am-12 m NEUROPEDIATRIA- FISIOSALUD DRA MIÑO 9 am-12:30 pm</td>
<td>Actividad académica Pediatría 7-8 am CONSULTA DE PEDIATRÍA - CUS DRA MOLANO 8 am-12 m NEUROPEDIATRIA – HUSJ DRA MIÑO 9 am-12:30m</td>
<td>CONSULTA DE PEDIATRÍA - HUSJ DRA CAICEDO 7 am-12 m NEUMOLOGÍA PEDIATRICA Consulta Externa HSLV - Sede San Camilo DRA VIDAL 7am – 12m</td>
<td>NEUMOLOGÍA PEDIATRICA Consulta Externa HUSJ DRA VIDAL 8am – 12m NEUROPEDIATRIA - FISIOSALUD DRA MIÑO 9am – 12.30 pm</td>
<td>Actividad académica Pediatría 7- 8 am CONSULTA DE PEDIATRÍA - HUSJ DRA CAICEDO 8 am-12 m NEUMOLOGÍA PEDIATRICA HSLV DRA VIDAL 9 am – 12m</td>
</tr>
<tr class="even">
<td>T</td>
<td>A</td>
<td>R</td>
<td>D</td>
<td>E</td>
</tr>
<tr class="odd">
<td>Administración</td>
<td>Administración</td>
<td>Revisión de tema</td>
<td>Revisión de tema</td>
<td>Curso AIEPI</td>
</tr>
</tbody>
</table>
<p><strong>Sitios de práctica:</strong></p>
<p>Consulta externa de Pediatría General (consultorio 24), segundo piso del Hospital Universitario San José.</p>
<p>Centro Universitario de Salud “Alfonso López”, ubicado en la calle 13.</p>
<p>Consulta externa en el HUSJ, según el consultorio asignado para cada especialidad pediátrica.</p>
<p>Hospital Susana López de Valencia, situado en el barrio La Ladera.</p>
<p>Consulta externa del HSLV, sede San Camilo (Carrera 8 # 9-66, sector Centro).</p>
<p>Consulta externa en Fisiosalud del Cauca (Carrera 11 No.&nbsp;17N-59, barrio Antonio Nariño).</p>
</section>
<section id="anexo-i-rotación-de-neonatología" class="level3">
<h3 class="anchored" data-anchor-id="anexo-i-rotación-de-neonatología">Anexo I — Rotación de Neonatología</h3>
<p>Docentes: Ana María Velasco (coordinadora), Alex Jair Ortiz Bolaños, Gloria Martínez Orozco, María Alejandra Palma</p>
</section>
<section id="section-201" class="level3">
<h3 class="anchored" data-anchor-id="section-201"></h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Capítulos y Temas</th>
<th>Acompañamiento Directo</th>
<th></th>
<th>Trabajo Independiente</th>
<th></th>
<th>Apoyo bibliográfico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>Hs</td>
<td>Metodología</td>
<td>Hs</td>
<td>Metodología</td>
<td></td>
</tr>
<tr class="even">
<td>NEONATOLOGÍA</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1. Avery &amp; MacDonald’s Neonatology: Pathophysiology and Management of the Newborn (8th ed.) Boardman, J. P., Groves, A. M., &amp; Ramasethu, J. (Eds.). (2021) 2. Cloherty and Stark’s Manual of Neonatal Care (9th ed.) Eichenwald, E. C., Hansen, A. R., Martin, C. R., &amp; Stark, A. R. (Eds.). (2023) 3. Atención Integrada a las Enfermedades Prevalentes de la Infancia (AIEPI): Libro clínico (3.ª ed). Organización Panamericana de la Salud 4. Remington and Klein’s Infectious Diseases of the Fetus and Newborn Infant (9th ed.).Maldonado, Y. A., Nizet, V., Barnett, E. D., Edwards, K. M., &amp; Malley, R. (Eds.). (2024) 5. Donor human milk versus infant formula for low-risk infants: a systematic review European society for pediatric 2024</td>
</tr>
<tr class="odd">
<td>Semiología Neonatal</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Historia clínica Neonatal – Examen físico del Recién nacido – Clasificación por peso, por edad gestacional y por peso/edad gestacional Diagnóstico Neonatal - Signos y síntomas de riesgo en el recién nacido</td>
<td>8</td>
<td>PG - PR</td>
<td>8</td>
<td>AA</td>
<td></td>
</tr>
<tr class="odd">
<td>Lactancia Materna</td>
<td>4</td>
<td>PG - PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="even">
<td>Puericultura Neonatal</td>
<td>4</td>
<td>PG – PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="odd">
<td>CUIDADO INTENSIVO NEONATAL</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1. Avery &amp; MacDonald’s Neonatology: Pathophysiology and Management of the Newborn (8th ed.) Boardman, J. P., Groves, A. M., &amp; Ramasethu, J. (Eds.). (2021) 2. Cloherty and Stark’s Manual of Neonatal Care (9th ed.) Eichenwald, E. C., Hansen, A. R., Martin, C. R., &amp; Stark, A. R. (Eds.). (2023) 3. Atención Integrada a las Enfermedades Prevalentes de la Infancia (AIEPI): Libro clínico (3.ª ed). Organización Panamericana de la Salud 4. Remington and Klein’s Infectious Diseases of the Fetus and Newborn Infant (9th ed.). Maldonado, Y. A., Nizet, V., Barnett, E. D., Edwards, K. M., &amp; Malley, R. (Eds.). (2024) 5. Volpe’s Neurology of the Newborn (7th ed.). Volpe, J. J., &amp; Inder, T. E. (Eds.). (2024) 6. Gomella’s Neonatology: Management, Procedures, On-Call Problems, Diseases, and Drugs (8th ed.). McGraw Hill Education. Gomella, T. L., Cunningham, M. D., &amp; Eyal, F. G. (2020) 7. Fanaroff and Martin’s Neonatal-Perinatal Medicine: Diseases of the Fetus and Infant (12th ed., 2 vols.) Martin, R. J., Fanaroff, A. A., &amp; Walsh, M. C. (Eds.). (2025) 8. Textbook of Neonatal Resuscitation (NRP). 9th ed.&nbsp;Itasca, IL: American Academy of Pediatrics; 2025 . 9ª. Ed</td>
</tr>
<tr class="even">
<td>Temas</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Prematuro</td>
<td>4</td>
<td>PG - PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="even">
<td>Dificultad respiratoria</td>
<td>4</td>
<td>PG - PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="odd">
<td>Asfixia perinatal</td>
<td>4</td>
<td>PG - PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="even">
<td>Hipoglicemia</td>
<td>4</td>
<td>PG - PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="odd">
<td>Cuidado Intermedio Neonatal</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1. Avery &amp; MacDonald’s Neonatology: Pathophysiology and Management of the Newborn (8th ed.) Boardman, J. P., Groves, A. M., &amp; Ramasethu, J. (Eds.). (2021) 2. Cloherty and Stark’s Manual of Neonatal Care (9th ed.) Eichenwald, E. C., Hansen, A. R., Martin, C. R., &amp; Stark, A. R. (Eds.). (2023) 3. Atención Integrada a las Enfermedades Prevalentes de la Infancia (AIEPI): Libro clínico (3.ª ed). Organización Panamericana de la Salud 4. Remington and Klein’s Infectious Diseases of the Fetus and Newborn Infant (9th ed.). Maldonado, Y. A., Nizet, V., Barnett, E. D., Edwards, K. M., &amp; Malley, R. (Eds.). (2024) 5. Volpe’s Neurology of the Newborn (7th ed.). Volpe, J. J., &amp; Inder, T. E. (Eds.). (2024) 6. Gomella’s Neonatology: Management, Procedures, On-Call Problems, Diseases, and Drugs (8th ed.). McGraw Hill Education. Gomella, T. L., Cunningham, M. D., &amp; Eyal, F. G. (2020) 7. Fanaroff and Martin’s Neonatal-Perinatal Medicine: Diseases of the Fetus and Infant (12th ed., 2 vols.) Martin, R. J., Fanaroff, A. A., &amp; Walsh, M. C. (Eds.). (2025)</td>
</tr>
<tr class="even">
<td>Temas</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Ictericia</td>
<td>4</td>
<td>PG - PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="even">
<td>Sepsis</td>
<td>4</td>
<td>PG -PR</td>
<td>2</td>
<td>AA</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Recién nacido afectado por condiciones maternas ( TORCHS)</td>
<td>4</td>
<td>PG - PR</td>
<td>2</td>
<td>AA</td>
<td>1. Red Book 2024: Report of the Committee on Infectious Diseases (Red Book Report of the Committee on Infectious Diseases) 33rd Edición</td>
</tr>
<tr class="odd">
<td>REVISIONES DE TEMAS MORBILIDAD NEONATAL</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Asfixia Perinatal Síndrome de Dificultad Respiratoria en el Recién Nacido -Enfermedad de Membrana Hialina -Broncoaspiración de Meconio -Taquipnea transitoria del Recién nacido -Neumonía Neonatal Signos y Síntomas de Riesgo en el Recién Nacido</td>
<td>2 2 2</td>
<td>MEC MEC CM</td>
<td>2 2 0</td>
<td>AA AA</td>
<td>1. Avery &amp; MacDonald’s Neonatology: Pathophysiology and Management of the Newborn (8th ed.) Boardman, J. P., Groves, A. M., &amp; Ramasethu, J. (Eds.). (2021) 2. Cloherty and Stark’s Manual of Neonatal Care (9th ed.) Eichenwald, E. C., Hansen, A. R., Martin, C. R., &amp; Stark, A. R. (Eds.). (2023) 3. Atención Integrada a las Enfermedades Prevalentes de la Infancia (AIEPI): Libro clínico (3.ª ed). Organización Panamericana de la Salud 4. Remington and Klein’s Infectious Diseases of the Fetus and Newborn Infant (9th ed.). Maldonado, Y. A., Nizet, V., Barnett, E. D., Edwards, K. M., &amp; Malley, R. (Eds.). (2024) 5. Volpe’s Neurology of the Newborn (7th ed.). Volpe, J. J., &amp; Inder, T. E. (Eds.). (2024) 6. Gomella’s Neonatology: Management, Procedures, On-Call Problems, Diseases, and Drugs (8th ed.). McGraw Hill Education. Gomella, T. L., Cunningham, M. D., &amp; Eyal, F. G. (2020) 7. Fanaroff and Martin’s Neonatal-Perinatal Medicine: Diseases of the Fetus and Infant (12th ed., 2 vols.) Martin, R. J., Fanaroff, A. A., &amp; Walsh, M. C. (Eds.). (2025)</td>
</tr>
<tr class="odd">
<td>GENETICA CLINICA Historia clínica Genética Dogma central de la biología molecular, Ciclo celular, Cromosomas Anormalidades, Cromosómicas, Mutaciones, Patones de Herencias Genealogía Nomenclatura Diagnósticos moleculares</td>
<td>2 2</td>
<td>ABP- CM - PR MEC</td>
<td>2 2</td>
<td>AA AA</td>
<td>1. mery and Rimoin’s Principles and Practice of Medical Genetics, 6th Edition. Elservier. 2. Biología molecular. Fundamentos y aplicaciones en las ciencias de la salud. 2013. McGRAW-HILL 3. INTERAMERICANA EDITORES, S.A. de C. V. 4. Oxford Desk Reference. Clinical genetics. (Oxford Desk Reference Series) 1st Edition 5. Thompson &amp; Thompson Genetica en medicina , 8th Edition. Elservier. 6. Handbook of Physical measurements. Oxford University.Second Edition. 2007 BASES DE DATOS INTERNACIONALES https://www.orpha.net/es https://omim.org/about https://pubmed.ncbi.nlm.nih.gov/</td>
</tr>
</tbody>
</table>
</section>
<section id="section-203" class="level3">
<h3 class="anchored" data-anchor-id="section-203"></h3>
</section>
<section id="section-204" class="level3">
<h3 class="anchored" data-anchor-id="section-204"></h3>
</section>
<section id="cuadro-semanal-de-prácticas-de-neonatos" class="level3">
<h3 class="anchored" data-anchor-id="cuadro-semanal-de-prácticas-de-neonatos">CUADRO SEMANAL DE PRÁCTICAS DE NEONATOS</h3>
</section>
<section id="section-205" class="level3">
<h3 class="anchored" data-anchor-id="section-205"></h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>LUNES</th>
<th>MARTES</th>
<th>MIÉRCOLES</th>
<th>JUEVES</th>
<th>VIERNES</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7:00 a 12:00 M. Unidad neonatal Hospital Universitario san José Dra. Ana María Velasco</td>
<td>8:00 a 12 AM. Mitad del grupo Revisión de tema, Facultad Ciencias de la Salud Dra. Gloria Martínez. Mitad del grupo Hospital Universitario san José Dra. María Alejandra palma.</td>
<td>7:00 a 11 AM Mitad del grupo Unidad neonatal y sala de Puerperio Clínica La estancia Dr.&nbsp;Alex Ortiz Mitad del grupo Hospital Universitario san José Dra. María Alejandra palma.</td>
<td>8:00 a 12 AM Mitad del grupo Unidad neonatal y sala de Puerperio Clínica La estancia Dr.&nbsp;Alex Ortiz Mitad del grupo Revisión de tema Facultad Ciencias de la Salud Dra. Gloria Martínez.</td>
<td>8:00 a 12:00 AM. Unidad neonatal Hospital Susana López de Valencia Dra. Ana María Velasco</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>2:00 a 4:00 PM Revisión mesa redonda Asesoría Dra. Ana Maria Velasco, Dra. Gloria Martínez, Dr.&nbsp;Alex Ortiz</td>
<td>2:00 a 4:00 PM Revisión mesa redonda Asesoría Dra. Ana Maria Velasco, Dr.&nbsp;Alex Ortiz</td>
<td>CAPACITACIÓN DE AIEPI</td>
</tr>
</tbody>
</table>
</section>
<section id="section-227" class="level3">
<h3 class="anchored" data-anchor-id="section-227"></h3>
</section>
<section id="anexo-j-programación-taller-de-estrategia-aiepi" class="level3">
<h3 class="anchored" data-anchor-id="anexo-j-programación-taller-de-estrategia-aiepi">Anexo J — Programación Taller de estrategia AIEPI</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>FECHA</th>
<th>TEMA</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Agosto 21 2-4 p.m.</td>
<td>Inicio, Módulo uno Clasificación inicial niño o niña menor de 3 meses - EVALÚE ENFERMEDAD GRAVE, Módulo dos Clasificación del niño o niña de 3 meses a 5 años - EVALÚE ENFERMEDAD GRAVE</td>
<td>Dr.&nbsp;Manuel Santiago Ordóñez.</td>
</tr>
<tr class="even">
<td>Agosto 28 2-6 p.m.</td>
<td>Módulo tres Generalidades valoración antropométrica y módulo ocho Desnutrición aguda</td>
<td>Dr.&nbsp;Álvaro I Narváez</td>
</tr>
<tr class="odd">
<td>Septiembre 4 2-6 pm</td>
<td>Módulo 4 a Abordaje del niño o niña menor de 3 meses. Evaluar y clasificar al niño con hipoglicemia: signos generales de alarma, evaluar factores de riesgo, Interrogar, verificar, clasificar, tratar, notificar, canalizar Evaluar y clasificar al niño con ictericia neonatal: definición, clasificación, etiología, factores de riesgo, evaluación clínica, signos generales de alarma, evaluar factores de riesgo, Interrogar, verificar, clasificar, tratar, notificar, canalizar Sindrome de hipoalimentación definición, factores de riesgo, prevención, examen físico, BRUE definición, factores de riesgo, factores protectores, evaluación: interrogue, verifique, clasifique Evaluación de la alimentación: beneficios de la lactancia materna, prácticas que protegen la lactancia materna, técnicas de amamantamiento, posiciones para el amamantamiento, habilidades de consejería en lactancia materna, observación de la lactancia materna, dificultades para el amamantamiento, etiología de los trastornos de la alimentación, clasificación, factores de riesgo, evaluación clínica, evaluar al niño con trastornos de la alimentación</td>
<td>Dra. Ana María Velasco</td>
</tr>
<tr class="even">
<td>Septiembre 11 2-6 pm</td>
<td>Módulo 4 b Abordaje del niño o niña menor de 3 meses Clasifique la condición Sepsis neonatal Meningitis Evaluar al niño con riesgo de sepsis neonatal Interrogue, Verifique, Clasifique Enterocolitis necrotizante: Definición, factores de riesgo, evaluar al niño con riesgo de ECN, interrogue, verifique, clasifique Neumonía, bronquiolitis lo envía al módulo 6 y enfermedad diarreica aguda lo envía al módulo 7 (se revisarían en el módulo correspondiente) Evaluar y clasificar al niño con hipotiroidismo: Interrogar, verificar, clasificar, tratar, notificar, canalizar.</td>
<td>Dra. Gloria Martínez</td>
</tr>
<tr class="odd">
<td>Septiembre 25 2-6 pm</td>
<td>Módulo 4 c Abordaje del niño o niña menor de 3 meses. Dificultades en el cuidado de los niños y niñas menores de dos meses: llanto intenso, cólico del lactante, reflujo gastroesofágico y vómito Depresión perinatal: evaluación, interrogue, verifique, clasifique Infección local: Infecciones locales de la piel, conjuntivitis, otitis, candidiasis oral, evalúe, interrogue, clasifique Condiciones normales del recién nacido: mancha mongólica, fisuras anales, fosa sacra, caderas, cuidados del ombligo y piel, orina y deposiciones, Lesiones de piel no infecciosas, Eritema tóxico. Dermatitis del área del pañal – “Pañalitis”. Miliaria. Dermatitis Seborreica. Hiperplasia de glándulas sebáceas. Dermatitis atópica. Perlas de Epstein y Nódulos de Bohn. Dientes natales y neonatales. Ictericia fisiológica Muerte Súbita: Evaluación del niño interrogue, verifique, tratar</td>
<td>Dr.&nbsp;Alex Jair Ortiz</td>
</tr>
<tr class="even">
<td>Octubre 2 2-6 pm</td>
<td>Módulo 5 Fiebre, ETV y zoonosis</td>
<td>Dra. Lorena Benavides</td>
</tr>
<tr class="odd">
<td>Octubre 9 2-6 pm</td>
<td>Módulo 6 Infección respiratoria aguda – Enfermedad respiratoria aguda</td>
<td>Dra. Dolly Vidal</td>
</tr>
<tr class="even">
<td>Octubre 16 2-6 pm</td>
<td>Módulo 7 Enfermedad diarreica aguda</td>
<td>Dra. Tatiana Henao</td>
</tr>
<tr class="odd">
<td>Octubre 30 2-6 pm</td>
<td>Módulo 9 Abordaje inicial de la salud bucal</td>
<td>Dra. Andrea Salas</td>
</tr>
<tr class="even">
<td>Noviembre 6 2-6 pm</td>
<td>Módulo 10 Abordaje inicial del cáncer Infantil</td>
<td>Dra. Olga Cújar</td>
</tr>
<tr class="odd">
<td>Noviembre 13 2-6 pm</td>
<td>Módulo 11 Abordaje inicial de la epilepsia</td>
<td>Dra. Ma. Eugenia Miño</td>
</tr>
<tr class="even">
<td>Noviembre 20 2-6 pm</td>
<td>Módulo 12 Abordaje de la salud mental desde el desarrollo.</td>
<td>Dra. Alicia Ortega</td>
</tr>
<tr class="odd">
<td>Noviembre 23 7 a.m.</td>
<td>Evaluación AIEPI</td>
<td>Docentes AIEPI</td>
</tr>
</tbody>
</table>
</section>
<section id="anexo-k-cronograma-de-rotaciones-exámenes-parciales-final-y-casos-clínicos" class="level3">
<h3 class="anchored" data-anchor-id="anexo-k-cronograma-de-rotaciones-exámenes-parciales-final-y-casos-clínicos">Anexo K — Cronograma de rotaciones, exámenes parciales, final y casos clínicos</h3>
<p><strong>PROGRAMACIÓN DE ROTACIONES CLÍNICAS PARA ESTUDIANTES DE X SEMESTRE</strong></p>
<p><strong>CASOS CLINICOS – 3 de agosto al 20 de noviembre de 2026</strong></p>
<p><strong>PERIODO ACADÉMICO 2026-2</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>PERIODO DE ROTACIÓN</th>
<th>RECIÉN NACIDOS</th>
<th>CONSULTA EXTERNA</th>
<th>MEDICINA INTERNA</th>
<th>PEDIATRÍA SOCIAL</th>
<th>URGENCIAS</th>
<th>INFECTOLOGÍA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Martes 11 de agosto al miércoles 26 de agosto (11 días hábiles)</td>
<td>G 1</td>
<td>G 2</td>
<td>G 3</td>
<td>G 4</td>
<td>G 5</td>
<td>G 6</td>
</tr>
<tr class="even">
<td>Jueves 27 de agosto al domingo 13 de septiembre (11 días hábiles)</td>
<td>G 2</td>
<td>G 1</td>
<td>G 4</td>
<td>G 3</td>
<td>G 6</td>
<td>G 5</td>
</tr>
<tr class="odd">
<td>NOTAS: - PALS 12, 13 Y 14 de agosto 2 a 6 p.m. - VI Encuentro de Semilleros y Jornada de Investigación Científica de la Facultad de Ciencias de la Salud: jueves 27 de agosto - Examen clases iniciales martes 18 de agosto 8:00 a.m. - NO TURNOS JUEVES 10 DE SEPTIEMBRE - Evaluaciones formativas: miércoles 26 de agosto, viernes 11 de septiembre - Primer parcial escrito viernes 11 de septiembre: 7:00 a.m.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Lunes 14 al miércoles 30 de septiembre (11 días hábiles)</td>
<td>G 3</td>
<td>G4</td>
<td>G 5</td>
<td>G 6</td>
<td>G1</td>
<td>G2</td>
</tr>
<tr class="odd">
<td>Jueves 1 de octubre al domingo 18 de octubre (11 días hábiles)</td>
<td>G 4</td>
<td>G3</td>
<td>G 6</td>
<td>G 5</td>
<td>G2</td>
<td>G 1</td>
</tr>
<tr class="even">
<td>NOTAS: - XXVIII Jornadas de Pediatría jueves 17 y viernes 18 de septiembre - NO TURNOS EL JUEVES 15 DE OCTUBRE - Evaluaciones formativas: miércoles 30 de septiembre, viernes 16 de octubre - Segundo parcial escrito viernes 16 de octubre: 7:00 a.m.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Lunes 19 de octubre al miércoles 4 de noviembre (11 días hábiles)</td>
<td>G 5</td>
<td>G 6</td>
<td>G 1</td>
<td>G 2</td>
<td>G 3</td>
<td>G 4</td>
</tr>
<tr class="even">
<td>Jueves 5 al viernes 20 de noviembre (11 días hábiles)</td>
<td>G 6</td>
<td>G 5</td>
<td>G 2</td>
<td>G 1</td>
<td>G 4</td>
<td>G 3</td>
</tr>
<tr class="odd">
<td>NOTAS: - Jornadas RICO Buentrato viernes 23 de octubre - TURNOS HASTA EL MIÉRCOLES 18 DE NOVIEMBRE INCLUSIVE - Evaluaciones formativas miércoles 4 de noviembre y viernes 20 de noviembre - Tercer parcial escrito: viernes 20 de noviembre: 7:00 a.m. - Examen AIEPI: lunes 23 de noviembre 7:00 a.m. - Semana Universitaria 23 al 27 de noviembre</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>EXAMEN FINAL PRÁCTICO ECOE: MARTES 1 DE DICIEMBRE EXAMEN FINAL ESCRITO: VIERNES 4 DE DICIEMBRE 7:00 a.m.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>PROGRAMACIÓN DE CASOS CLÍNICOS DE ESTUDIANTES 2026-2</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 36%">
<col style="width: 40%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;">Fecha</td>
<td style="text-align: center;">Caso clínico</td>
<td>Docente asesor</td>
</tr>
<tr class="even">
<td style="text-align: center;">4 de septiembre</td>
<td style="text-align: center;">Grupo 1. Consulta Externa</td>
<td>Dra. Dolly Vidal</td>
</tr>
<tr class="odd">
<td style="text-align: center;">8 de septiembre</td>
<td style="text-align: center;">Grupo 2. Neonatos</td>
<td>Dra. Ana María Velasco</td>
</tr>
<tr class="even">
<td style="text-align: center;">9 de octubre</td>
<td style="text-align: center;">Grupo 6. Medicina Interna</td>
<td>Dra. Olga Prado</td>
</tr>
<tr class="odd">
<td style="text-align: center;">13 de octubre</td>
<td style="text-align: center;">Grupo 5. Pediatría Social</td>
<td>Dra. Claudia Guzmán</td>
</tr>
<tr class="even">
<td style="text-align: center;">13 de noviembre</td>
<td style="text-align: center;">Grupo 4. Urgencias</td>
<td>Dra. Andrea Salas</td>
</tr>
<tr class="odd">
<td style="text-align: center;">17 de noviembre</td>
<td style="text-align: center;">Grupo 3. Infectología</td>
<td>Dra. Manuel Santiago Ordóñez</td>
</tr>
</tbody>
</table>
</section>
<section id="anexo-l-formatos-de-evaluación-cualitativa" class="level3">
<h3 class="anchored" data-anchor-id="anexo-l-formatos-de-evaluación-cualitativa">Anexo L — Formatos de evaluación cualitativa</h3>
<p><strong>EVALUACIÓN CUALITATIVA</strong></p>
<p>Universidad del Cauca – Programa de Medicina</p>
<blockquote class="blockquote">
<p><strong>1.</strong> <strong>FORMATO PARA SEGUIMIENTO DEL ESTUDIANTE</strong></p>
</blockquote>
<p><strong>ASIGNATURA PEDIATRÍA (diligencia el Docente)</strong></p>
<p>Universidad del Cauca – Programa de Medicina</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>INDICADOR</th>
<th>Medicina Interna</th>
<th>Infecto logia</th>
<th>Recién Nacidos</th>
<th>Pediatría Social</th>
<th>Urgencia</th>
<th>Consulta externa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Grado de conocimientos prácticos y teóricos.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Grado de capacidad del estudiante para identificar los problemas clínicos prioritarios, realizar diagnósticos diferenciales, y usar métodos diagnósticos pertinentes.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Grado de capacidad para determinar las conductas terapéuticas más apropiadas y pertinentes para los diagnósticos dados.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Capacidad del estudiante para interrelacionarse adecuadamente con el paciente y su familia, sus compañeros de estudio, el personal médico y paramédico que desempeña en las actividades de docencia y cuidado del enfermo.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Valoración de la motivación, iniciativa e interés mostrada en el proceso de aprendizaje alrededor de las habilidades y competencias clínicas.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Grado de cumplimiento y puntualidad en las labores asignadas como parte del proceso de aprendizaje.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>2.</strong> <strong>FORMATO DE AUTOEVALUACIÓN DEL ESTUDIANTE</strong></p>
</blockquote>
<p><strong>ASIGNATURA PEDIATRÍA</strong></p>
<p>Universidad del Cauca – Programa de Medicina</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;">Indicador</td>
<td>Medicina Interna</td>
<td>Infectología</td>
<td>Recién Nacidos</td>
<td>Pediatría Social</td>
<td>Urgencias</td>
<td>Consulta Externa</td>
</tr>
<tr class="even">
<td style="text-align: center;">Cómo catalogó el grado de conocimientos prácticos y teóricos alcanzados.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Cómo catalogó la capacidad alcanzada para identificar los problemas clínicos prioritarios, realizar diagnósticos diferenciales, y usar métodos diagnósticos pertinentes.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td style="text-align: center;">Cómo catalogó la capacidad alcanzada para determinar las conductas terapéuticas más apropiadas y pertinentes para los diagnósticos dados.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Cómo catalogó mi capacidad para interrelacionarme con el paciente, su familia, mis compañeros de estudio, el personal médico y paramédico que desempeña actividades de docencia.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td style="text-align: center;">Cómo fue la motivación, iniciativa e interés que mostré en el proceso de aprendizaje.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Cómo fue mi cumplimiento y puntualidad en las labores que me fueron asignadas.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>3. FORMATO DE EVALUACIÓN DE ASIGNATURA POR EL ESTUDIANTE</strong></p>
</blockquote>
<p><strong>ÁREAS CLÍNICAS</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Indicador</th>
<th>Medicina Interna</th>
<th>Infectología</th>
<th>Recién Nacidos</th>
<th>Pediatría Social</th>
<th>Urgencias</th>
<th>Consult Externa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Entrega de información inicial adecuada sobre el programa, objetivos a cumplir en la asignatura y sistema de evaluación.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Metodología didáctica utilizada por los profesores</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Cumplimiento y puntualidad en las actividades programadas.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Cumplimiento de objetivos trazados al inicio de la asignatura.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Interrelación personal de los docentes con el estudiante.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Métodos evaluativos pertinentes y adecuados para los objetivos perseguidos.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./0297092-seminario-de-desastres.html" class="pagination-link" aria-label="Seminario de Desastres">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Seminario de Desastres</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./0297102-administracion-en-salud.html" class="pagination-link" aria-label="Administración en Salud">
        <span class="nav-page-text"><span class="chapter-title">Administración en Salud</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>